---
title: "Applied Machine Learning"
output: html_document
date: "2024-09-02"
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
  line-height: 150%;
  }
  .main-container {
  max-width: 800px !important;
  margin: auto;
  }
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Political Science Academy Homepage](https://politicalscience.github.io)

*S*ometimes in political science, we are more concerned with prediction accuracy, rather than causality or explainability. This course is a rigorous introduction to machine learning prediction methods that have been adopted in the social sciences.

Prerequisites: Topics covered in [Intro to Statistical Inference](#intro_stats) and [Regression Analysis](#regression). Some working knowledge of R and Maths to the level of [Workshop: R Fundamentals](#r) and [Maths for Political Science](#maths) is also helpful.

<br />

### Chapter 1: Prediction Models

| Lesson                                                                                | Topics                                                                        |
|-----------------------------|-------------------------------------------|
| [**1.1 Polynomial Models**](https://politicalscience.github.io/ml/1-1.html)           | Introduction to Non-Linear Models, Polynomial Regression, Implementation in R |
| [**1.2 Step Functions and Splines**](https://politicalscience.github.io/ml/1-2.html)  | Step Functions, Splines, Implementation in R                                  |
| [**1.3 Local Linear Regression**](https://politicalscience.github.io/ml/1-3.html)     | Local Linear Regressions, Implementation in R                                 |
| [**1.4 Generalised Additive Models**](https://politicalscience.github.io/ml/1-4.html) | Generalised Additive Models, Impelemntation in R                              |
| [**1.5 Regression Trees**](https://politicalscience.github.io/ml/1-5.html)            | Regression Trees, Implementation in R                                         |
| [**1.6 Bagging and Random Forest**](https://politicalscience.github.io/ml/1-6.html)   | Bootstrap, Bagging and Random Forest, Importance Plots,                       |

<br />

### Chapter 2: Classification Methods

| Lesson                                                                                        | Topics                                                                      |
|-----------------------------|-------------------------------------------|
| [**2.1 Naive Bayes Classifier**](https://politicalscience.github.io/ml/2-1.html)              | Introduction to Classification, Naive Bayes Classifier, Implementation in R |
| [**2.2 Tree-Based Classifiers**](https://politicalscience.github.io/ml/2-2.html)              | Bagging and Random Forest Classifiers                                       |
| [**2.3 Evaluation of Classification Models**](https://politicalscience.github.io/ml/2-3.html) | Error Rate, False Positive and Negative, Sensitivity and Specificity        |

: <br />

### Chapter 3: Model Selection and Validation

| Lesson                        | Topics                                            |
|-----------------------------|-------------------------------------------|
| 3.1 Training and Testing Sets | Bias/Variance Tradeoff, Training and Testing Sets |
| 3.2 K-Fold Cross Validation   |                                                   |
| 3.3 Bootstrap Sampling        |                                                   |
| 3.4 Regularisation            | Ridge Regression, Lasso Regression                |

<br />

### Chapter 4: Unsupervised Learning

| Lesson               | Topics |
|----------------------|--------|
| 4.1 Cluster Analysis |        |

<br />

------------------------------------------------------------------------

[Political Science Academy Homepage](https://politicalscience.github.io)
