---
title: "Very Applied Econometrics for Social Scientists"
subtitle: "Methods for Political Science: Notes and Guides on Quantitative Methods"
format:
    html:
        page-layout: article
        grid:
          sidebar-width: 300px
          body-width: 750px
          margin-width: 250px
          gutter-width: 2em
        fontsize: 12.5pt
        theme: yeti
        toc: TRUE
        toc-depth: 2
        toc-location: left
        toc-expand: true
        toc-title: "Econometric Methods (for Social Scientists)"
        mainfont: "Computer Modern"
        title-block-banner: true
        classoption: fleqn
        html-math-method: katex
---

[Homepage](https://politicalscience.github.io)

## Syllabus

This is a beginner course on econometrics for those interested in using statistical/econometric causal inference methods for social science research.

This course, as the name suggests, is very applied, and I will take every effort to avoid mathematics (although it is not possible to completely avoid math). If you already have a background in mathematics or econometrics/statistics, the second course - econometric methods for social scientists, may be more useful (although I recommend going through this course prior).

**Prerequisites:** A basic understanding of algebra, including linear lines in the form of $y= mx + b$.

<br />

## Chapters

1.  Introduction to Causal Inference
2.  Potential Outcomes and Selection Bias
3.  The Gold Standard: Randomised Controlled Trials
4.  Intuition of Hypothesis Testing for Causal Inference
5.  Into the Observational World: Relationships with Regression
6.  Getting Closer to Causality: Multiple Linear Regression
7.  Instrumental Variables as the Solution to Many Issues
8.  Regression Discontinuity Designs
9.  Differences-in-Differences Designs
