---
title: "Mathematics (for Social Scientists)"
subtitle: "Methods for Political Science: Notes and Guides on Quantitative Methods"
format:
    html:
        page-layout: article
        grid:
          sidebar-width: 300px
          body-width: 750px
          margin-width: 250px
          gutter-width: 2em
        fontsize: 12.5pt
        theme: yeti
        toc: TRUE
        toc-depth: 2
        toc-location: left
        toc-expand: true
        toc-title: "Econometric Methods (for Social Scientists)"
        mainfont: "Computer Modern"
        title-block-banner: true
        classoption: fleqn
        html-math-method: katex
---

[Homepage](https://politicalscience.github.io)

## Syllabus

These notes provide the mathematical background needed for methodology in political science and the social sciences. These notes serve as a companion to the other notes in this guide.

This course is split into 3 parts, with each part having a series of chapters (which include sections).

1.  Essential Mathematics: essential skills that are needed to succeed in the social sciences.
2.  Further Mathematics: optional but useful skills.
3.  Abstract Mathematics: only really useful for advanced applications.

**Prerequisites**: Strong skills in algebra and single variable calculus. Basic linear algebra is helpful. You can undertake this course without these skills, but you may struggle a little.

<br />

## Part I: Essential Mathematics

1.  Set Theory and Algebra Review
2.  Precalculus: Functions and Limits
3.  Derivatives and Partial Derivatives
4.  Simple Optimisation
5.  Single Variable Integration
6.  Introductory Probability Theory

## Part II: Further Mathematics

7.  Basics of Vectors and Matrices
8.  General Linear Systems
9.  Vector Spaces
10. Linear Operators and Diagonalisation
11. Multivariate Calculus: Derivatives
12. Multivariate Calculus: Optimisation

## Part III: Abstract Mathematics

13. Mathematical Statements, Proofs, and Logic
14. Set Theory
15. Structures, Natural Numbers, and Proof by Induction
16. Functions and Counting
17. Equivalence Relations and Rational Numbers
18. Real and Complex Numbers
19. Analysis: Real Numbers
20. Analysis: Sequences and Limits
21. Analysis: Continuity
