---
title: "Kevin's Guide to Political Science"
subtitle: "Lesson 1.2: Dominant Strategies and Equilibrium"
format:
    html:
        page-layout: article
        grid:
          sidebar-width: 300px
          body-width: 750px
          margin-width: 250px
          gutter-width: 2em
        fontsize: 12.5pt
        theme: yeti
        toc: TRUE
        toc-depth: 2
        toc-location: left
        toc-expand: true
        toc-title: "Lesson 1.2: Dominant Strategies and Equilibrium"
        mainfont: "Computer Modern"
        title-block-banner: true
        classoption: fleqn
        html-math-method: katex
---

::: callout-note
## Lesson Overview

In this lesson, we introduce the idea of strictly and weakly dominated strategies, and introduce our first equilibrium solution concept: dominant strategy equilibrium.

This lesson covers the following topics:

-   Definitions of dominant strategies and the famous prisoner's dilemma game.
-   Equilibrium concepts and dominant strategy equilibrium.
-   Using elimination to find equilibrium.
:::

<br />

------------------------------------------------------------------------

[Homepage](https://politicalscience.github.io)

# 1.2.1: Dominant Strategies and the Prisoner's Dilemma

In lesson 1.1, we discussed how game theory is the study of how one player's actions affects another player's outcomes/gains/payoffs. Thus, players have to anticipate what their opponents will do, and adjust their decisions/actions accordingly.

However, in some games, one action/strategy is always better than the other strategies, no matter what an opponent plays. That strategy which is always better than the other strategies, is called a **dominant strategy**.

::: callout-tip
## Definition: Strictly Dominant Strategy

A **strictly dominant strategy**, notated $s_i^D$, is indeed a dominant strategy, if no matter what the opponent does, the payoff/utility for player $i$ is highest when they play $s_i^D$. Mathematically:

$$
u_i(s_i^D, s_{-i})>u_i(s_i', s_{-i})
$$

Or more intuitively, the utility of player $i$ choosing their dominant strategy $s_i^D$, is always greater than the utility of player $i$ choosing another strategy $s_i'$, no matter the strategies chosen by the opponents $s_{-i}$.
:::

If player $i$ has a dominant strategy $s_i^D$, then the other strategies $s_i'$ of player $i$ are considered to be **strictly dominated**.

<br />

A good example to introduce the idea of strictly dominant strategies is the **Prisoner's Dilemma Game**.

::: callout-note
## Game: Prisoner's Dilemma

Two suspects are arrested. If they both remain quiet (cooperate with each other), then both will be convicted for minor offences and sentenced to 1 month in jail. If both rat each other out (defect), then both will be sentenced to jail for 8 months. Finally, if one defects but the other does not, then the confessor is immediately released and the other is sentenced to 10 months.
:::

We can represent this game in matrix form, where player 1 chooses between the *row* strategies, and player 2 chooses between the *column* strategies. The numbers below represent the payoffs, in the form (player 1's payoff, player 2's payoff):

$$
\begin{matrix}
& \text{Cooperate} (P2) & \text{Defect} (P2) \\
\text{Cooperate} (P1) & -1, -1 & -10, 0 \\
\text{Defect} (P1) & 0, -10 & -8, -8
\end{matrix}
$$

<br />

Now, let us look only at player 1's choice of strategy. To do this, let us *hold fixed* player 2's strategy.

Holding player 2's strategy as *Cooperate* (by only showing the cooperate P2 column), player 1 has the following choice:

$$
\begin{matrix}
& \text{Cooperate} (P2) \\
\text{Cooperate} (P1) & -1, -1 \\
\text{Defect} (P1) & 0, -10
\end{matrix}
$$

Here, we can see if player 1 picks *cooperate*, they get a payoff of -1. When player 1 picks *defect*, they get 0, which is a higher payoff. Thus, player 1 prefers to *defect* given player 2 holds their strategy *cooperate* constant.

<br />

Now, let us hold player 2's strategy as *Defect* (by only showing the defect P2 column). Player 1 has the following choice:

$$
\begin{matrix}
& \text{Defect} (P2) \\
\text{Cooperate} (P1) & -10, 0 \\
\text{Defect} (P1) & -8, -8
\end{matrix}
$$

Here, we can see that if player 1 picks *cooperate*, they get a payoff of -10. When player 1 picks *defect*, they get a payoff of -8, which is a higher payoff. Thus, player 1 prefers to *defect* given player 2 holds their strategy *defect* constant.

<br />

Thus, we have come to the following conclusions when holding player 2's strategy constant:

1.  Player 1 prefers to *defect* given player 2 holds their strategy *cooperate* constant.
2.  Player 1 prefers to *defect* given player 2 holds their strategy *defect* constant.

Notice how player 1 always prefers the strategy *defect*, no matter if player 2 decides to play *cooperate* or *defect*. Thus, player 1 prefers *defect* no matter the strategy of player 2, and thus, *defect* is a **strictly dominant strategy**.

Because the prisoner's dilemma is symmetrical, this is also the same for player 2 - *defect* is a strictly dominant strategy for both players.

<br />

<br />

------------------------------------------------------------------------

[Homepage](https://politicalscience.github.io)

# 1.2.2: Solutions and Equilibrium Concepts

So far, we have focused on strategies and the actions of players. However, we are often more interested in the actual outcomes of the games.

When we create games/models, we are often interested in its likely outcome. This is because we often model economic and political situations, and we want to know the likely outcomes of these situations to inform our understanding of the world, and implement new policies.

Thus, we need to find some *solution* to the games/models that we create. An **equilibrium** is a potential solution to the games, that restricts the set of all possible strategies to the most *reasonable* ones.

<br />

However, what is a *reasonable* strategy and outcome? To define *reasonable* strategies to find a equilibrium, we must make assumptions about reasonableness:

1.  Players are **rational** - they aim to maximise their utility/payoffs. In other words, a utility of $a$ is preferred to $b$ if $a > b$.
2.  Any equilibrium (and set of reasonable strategies) must be **self-enforcing** - i.e. players will reach the supposed solution/equilibrium without external forces telling them to do so, as they rationally want to enter the equilibrium.

<br />

As we will explore in this course, there are many different equilibrium concepts - different ways to define equilibrium. Each equilibrium concept has its advantages and disadvantages. We typically evaluate equilibrium concepts with a few key concepts:

1.  **Existence**: how often does the equilibrium actually exist in a game? If an equilibrium defined by a equilibrium concept does not exist in most games, then it is not very useful, since it does not tell us the solution for most games.
2.  **Uniqueness**: How many equilibrium of this equilibrium concept exist in a game? If a equilibrium concept has too many equilibria for a given game, then that is not very useful for prediction, since we do not know which equilibria is more likely. We would prefer unique equilibria/solutions to our games.
3.  **Robustness**: How sensitive is the equilibrium of this equilibrium concept to small changes? After all, in the real world, people are not perfectly rational. Our models also simplify the complexity of the world. We want to be sure that slightly changing our model, or introducing slight imperfection in player behaviour, does not completely throw away our equilibrium predictions.

<br />

Throughout this course, we will explore many different types of equilibrium concepts, their advantages and disadvantages, and what games they can be applied to.

<br />

<br />

------------------------------------------------------------------------

[Homepage](https://politicalscience.github.io)

# 1.2.3: Dominant Strategy Equilibrium

The first solution concept we will introduce is the **Dominant Strategy Equilibrium**. A dominant strategy equilibrium occurs when all players play dominant strategies.

-   After all, if everyone has a strictly dominant strategy (i.e. a preferred strategy regardless of the opponents strategy), then if everyone plays that preferred dominant strategy, that is probably a likely outcome of the game.

We can define dominant strategy equilibrium more formally:

::: callout-tip
## Definition: Dominant Strategy Equilibrium

A strategy profile for all players $S^D = (S_1^D, S_2^D, \dots, S_N^D)$ is a **dominant strategy equilibrium**, if for all players $i$, $u_i (S_i^D, s_{-i})>u_i(s_i', s_{-i})$.

Or more intuitively, a strategy profile is a dominant strategy equilibrium, given every player $1, \dots, N$ is playing a dominant strategy.
:::

<br />

For example, let us return to the Prisoner's Dilemma Game:

$$
\begin{matrix}
& \text{Cooperate} (P2) & \text{Defect} (P2) \\
\text{Cooperate} (P1) & -1, -1 & -10, 0 \\
\text{Defect} (P1) & 0, -10 & -8, -8
\end{matrix}
$$

We already established that for both player 1 and player 2, *defect* is a dominant strategy.

We know that a dominant strategy equilibrium is when both players both play a dominant strategy. Thus, the dominant strategy equilibrium is when both players play *defect*, which results in an outcome of (-8, -8). We can notate this equilibrium as (Defect, Defect).

<br />

One important note is that a [equilibrium is a strategy profile]{.underline}, not a payoff. So, in the Prisoner's dilemma, the equilibrium IS **NOT** (-8, -8), as -8 is not a strategy profile. Instead, the equilibrium is (Defect, Defect).

-   (-8, -8), or any other payoffs of an equilibrium, are considered the **equilibrium outcome**, not the equilibrium.

<br />

Is a dominant strategy equilibrium a good solution concept? Let us evaluate its existence, uniqueness, and robustness:

1.  Existence: Dominant strategy equilibrium is not good by this metric. This is because dominant strategies often do not exist (as we will see in the next lesson). Thus, dominant strategy equilibrium can only be used to find the solution in a small set of games.
2.  Uniqueness: When a dominant strategy equilibrium does exist, it is guaranteed to be unique. This is because by definition, each player can only have one dominant strategy in a game (since that dominant strategy must always have a higher payoff than the other strategies). Thus, it is very unique, which is useful for prediction.
3.  Robustness: Dominant strategies are relatively robust.

<br />

<br />

------------------------------------------------------------------------

[Homepage](https://politicalscience.github.io)

# 1.2.4: Dominated Strategies and Iterated Dominance

So far, we have focused on strictly **dominant strategies**, which are always better than other strategies, no matter the opponents strategy.

However, we can also consider the opposite: **strictly dominated strategies**. These are strategies that always give a worse payoff than another strategy, no matter the opponents strategy.

If a strategy is strictly dominated, that means it always gives a worse payoff than another strategy. That implies that if a player has a strictly dominated strategy, they will never choose that strategy, since another strategy is always better.

Thus, we can also find equilibrium through eliminating strictly dominated strategies, since we know they will never be chosen.

Once we eliminate strictly dominated strategies, we will often notice that other strategies also become strictly dominated for other players. By continuing the cycle, we can sometimes reach a single outcome - an equilibrium. This method is called **iterated dominance**.

<br />

For example, suppose we have the following game. Player 1 has two strategies: up or down. Player 2 has three strategies: Left, Middle, and Right:

$$
\begin{matrix}
& \text{Left} & \text{Middle} & \text{Right} \\
\text{Up} & 1,0 & 1,2 & 0,1 \\
\text{Down} & 0,3 & 0,1 & 2,0
\end{matrix}
$$

Are there any strictly dominated strategies? Yes - for player 2 - strategy *right* is strictly dominated by strategy *middle*.

-   Why? We can see if we hold player 1's strategy fixed as *up*, player 2 playing *right* gets a payoff of 1, and player 2 playing *middle* gets a payoff of 2 which is better. If we hold player 1's strategy fixed as *down*, once again, *middle* is better than *right*. Thus, *right* always gives a worse payoff than *middle*, no matter the opponents strategy.

<br />

That means we can eliminate *right* (by deleting the column). Now, we have this game after our first elimination:

$$
\begin{matrix}
& \text{Left} & \text{Middle} \\
\text{Up} & 1,0 & 1,2 \\
\text{Down} & 0,3 & 0,1
\end{matrix}
$$

Is there another strictly dominated strategy? Yes - for player 1, strategy *down* is now strictly dominated by strategy *up*.

-   We can see that if holding player 2's strategy fixed as *left*, player 1 playing *up* results in a better payoff (1 \> 0). When holding player 2's strategy fixed as *middle*, player 1 playing *up* results in a better payoff (1 \> 0). Thus, *down* always results in a worse payoff than *up*, no matter the opponents strategy.

<br />

That means, we can eliminate *down* (by deleting the row). Now, we have this game after our second elimination:

$$
\begin{matrix}
& \text{Left} & \text{Middle} \\
\text{Up} & 1,0 & 1,2
\end{matrix}
$$

Now, is there another strictly dominated strategy? Yes - for player 2, *left* is strictly dominated. This is because when holding player 1's strategy constant (well of course, there is only one strategy left for player 1), *left* has a higher payoff for player 2 than *middle*. Thus, *middle* always results in a worse payoff that *left*, so it is strictly dominated.

<br />

Thus, after eliminating middle, we are left with (Up, Left), which is our equilibrium. We obtained this equilibrium simply by eliminating implausible strategies.

<br />

<br />

------------------------------------------------------------------------

[Homepage](https://politicalscience.github.io)

# 1.2.5: Example

<br />

------------------------------------------------------------------------

[Homepage](https://politicalscience.github.io)

# 1.2.6: Weak Dominance
