project:
  type: website
  output-dir: docs

website:
  title: "Political Science & Political Economy"
  back-to-top-navigation: true
  sidebar:
    - id: side
      title: "Kevin's PSPE Resources"
      search: false
      style: "docked"
      contents:
        - text: "---"
        - text: "Guide to Game Theory"
          href: games.qmd
        - text: "---"
        - text: "Introductory Mathematics"
        - text: "Linear Algebra"
          href: linear.qmd
        - text: "Calculus"
          href: calc.qmd
        - text: "---"
        - text: "Quantitative Methods (Causal Inference)"
        - text: "1 Introductory Statistics"
          href: 1.qmd
        - text: "2 Multiple Linear Regression"
          href: 2.qmd
        - text: "3 Classic Least Squares Theory"
          href: 3.qmd
        - text: "4 Causal Frameworks"
          href: 4.qmd
        - text: "5 Randomised Controlled Trials"
          href: 5.qmd
        - text: "6 Selection on Observables"
          href: 6.qmd
        - text: "7 Instrumental Variables"
          href: 7.qmd
        - text: "8 Regression Discontinuity"
          href: 8.qmd
        - text: "9 Differences-in-Differences"
          href: 9.qmd
        - text: "10 New Advances in Causal Inference"
          href: 10.qmd
        - text: "---"
        - text: "Further Statistical Models"
        - text: "Logistic Regression Models"
          href: 11.qmd
        - text: "Regression for Counts"
          href: 12.qmd
        - text: "Random Forests and Bagging"
          href: 13.qmd
        - text: "Principle Components Analysis"
          href: 14.qmd
        - text: "Factor Analysis Models"
          href: 15.qmd
        - text: "Latent Trait Models"
          href: 16.qmd
        - text: "Latent Class Models"
          href: 17.qmd
        - text: "Cluster Analysis"
          href: 18.qmd
        - text: "Structural Equation Models"
          href: 19.qmd
format:
  html:
    theme: materia
    css: styles.css
    page-layout: article
    grid:
      sidebar-width: 325px
      body-width: 700px
      margin-width: 400px
      gutter-width: 4em
    mainfont: "Times New Roman"
    fontsize: 12pt
    toc: true
    toc-depth: 3
    toc-location: right
    toc-expand: true
    toc-title: "On This Page"
    html-math-method: mathjax
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
editor: visual

