project:
  type: website
  output-dir: docs

website:
  title: "Political Science & Political Economy"
  back-to-top-navigation: true
  sidebar:
    - id: side
      title: "Kevin's PSPE Resources"
      search: true
      style: "docked"
      pinned: true
      contents:
        - text: "---"
        - text: "Quantitative Methods (Causal Inference)"
        - text: "1 The Classical Linear Model"
          href: clm.qmd
        - text: "2 Causal Frameworks"
          href: causal.qmd
        - text: "3 Randomised Controlled Trials"
          href: rct.qmd
        - text: "4 Selection on Observables"
          href: soo.qmd
        - text: "5 Instrumental Variables"
          href: iv.qmd
        - text: "6 Regression Discontinuity"
          href: rd.qmd
        - text: "7 Differences-in-Differences"
          href: did.qmd
        - text: "---"
        - text: "Guide to Game Theory"
          href: games.qmd
        - text: "Background Mathematics"
          href: math.qmd
        - text: "Background Statistics"
          href: stats.qmd
        - text: "---"


format:
  html:
    theme: default
    css: styles.css
    page-layout: article
    grid:
      sidebar-width: 325px
      body-width: 700px
      margin-width: 400px
      gutter-width: 2em
    mainfont: "Times New Roman"
    fontsize: 12pt
    toc: true
    toc-depth: 3
    toc-location: right
    toc-expand: true
    toc-title: "On This Page"
    html-math-method: mathjax
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
editor: visual

