project:
  type: book
  output-dir: docs

book:
  title: "Kevin's PSPE Resources"
  subtitle: "Kevin's Collection on PSPE Methodology"
  author: "Kevin Lingfeng Li"
  search: true
  cover-image: lse.png
  chapters:
    - index.qmd
    - "---"
    - part: "Theoretical Statistics"
      chapters:
        - random.qmd
        - inference.qmd
        - mle.qmd
        - ols.qmd
        - causal.qmd
    - "---"
    - part: "Applied Statistics"
      chapters:
        - thecauses.qmd
        - glm.qmd
        - multivariate.qmd
    - "---"
    - part: "Game Theory"
      chapters:
        - games.qmd
    - "---"
    - part: "Mathematics"
      chapters:
        - linear.qmd
        - calc.qmd
    - part: "Changing Soon"
      chapters: 
        - identify.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
    css: styles.css
    toc: true
    toc-depth: 2
    grid:
      sidebar-width: 225px
      body-width: 700px
      margin-width: 275px
      gutter-width: 1em
    html-math-method: mathjax
    crossref:
      eq-prefix: eq.
      def-prefix: definition
      thm-prefix: theorem
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
  pdf:
    documentclass: scrreprt
editor: visual

