project:
  type: website
  output-dir: docs

website:
  title: "Political Science & Political Economy"
  back-to-top-navigation: true
  sidebar:
    - id: side
      title: "Kevin's PSPE Resources"
      search: true
      style: "docked"
      pinned: true
      contents:
        - text: "---"
        - text: "Guide to Game Theory"
          href: games.qmd
        - text: "Essential Mathematics"
          href: math.qmd
        - text: "---"
        - text: "Quantitative Methods (Causal Inference)"
        - text: "1 Introductory Statistics"
          href: quant1.qmd
        - text: "2 Multiple Linear Regression"
          href: quant2.qmd
        - text: "3 Classical Least Squares Theory"
          href: quant3.qmd
        - text: "4 Causal Frameworks"
          href: quant4.qmd
        - text: "5 Randomised Controlled Trials"
          href: quant5.qmd
        - text: "6 Selection on Observables"
          href: quant6.qmd
        - text: "7 Instrumental Variables"
          href: quant7.qmd
        - text: "8 Regression Discontinuity"
          href: quant8.qmd
        - text: "9 Differences-in-Differences"
          href: quant9.qmd
        - text: "---"
        - text: "More Statistical Models"
        - text: "Logistic Regression Models"
          href: model1.qmd
        - text: "Regression for Counts"
          href: model2.qmd
        - text: "Supervised Learning Methods"
          href: model3.qmd
        - text: "Unsupervised Learning Methods"
          href: model4.qmd
        - text: "Factor Analysis Models"
          href: model5.qmd
        - text: "Latent Trait Models"
          href: model6.qmd
        - text: "Latent Class Models"
          href: model7.qmd
        - text: "Structural Equation Models"
          href: model9.qmd

format:
  html:
    theme: default
    css: styles.css
    page-layout: article
    grid:
      sidebar-width: 325px
      body-width: 700px
      margin-width: 400px
      gutter-width: 2em
    mainfont: "Times New Roman"
    fontsize: 12pt
    toc: true
    toc-depth: 3
    toc-location: right
    toc-expand: true
    toc-title: "On This Page"
    html-math-method: mathjax
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
editor: visual

