project:
  type: website
  output-dir: docs

website:
  title: "Political Science & Political Economy"
  back-to-top-navigation: true
  sidebar:
    - id: side
      title: "Kevin's PSPE Resources"
      search: true
      style: "docked"
      pinned: true
      contents:
        - text: "---"
        - text: "Quantitative Methods"
        - section: "Fundamentals"
          contents:
            - text: "1 The Classical Linear Model"
              href: clm.qmd
            - text: "2 The Generalised Linear Model"
              href: glm.qmd
        - section: "Causal Inference"
          contents:
            - text: "3 Causal Frameworks"
              href: causal.qmd
            - text: "4 Randomised Controlled Trials"
              href: rct.qmd
            - text: "5 Selection on Observables"
              href: soo.qmd
            - text: "6 Instrumental Variables"
              href: iv.qmd
            - text: "7 Regression Discontinuity"
              href: rd.qmd
            - text: "8 Differences-in-Differences"
              href: did.qmd
        - section: "Prediction and Measurement"
          contents:
            - text: " 9 Forecasting and Prediction Models"
              href: predict.qmd
            - text: "10 Unsupervised Learning Methods"
              href: unsupervised.qmd
            - text: "11 Factor Analysis Models"
              href: factor.qmd
            - text: "12 Latent Trait and Class Models"
              href: latent.qmd
            - text: "13 Structural Equation Models"
              href: sem.qmd
        - text: "---"
        - text: "Guide to Game Theory"
          href: games.qmd
        - text: "Background Mathematics"
          href: math.qmd
        - text: "Background Statistics"
          href: stats.qmd
        - text: "---"


format:
  html:
    theme: default
    css: styles.css
    page-layout: article
    grid:
      sidebar-width: 325px
      body-width: 700px
      margin-width: 400px
      gutter-width: 2em
    mainfont: "Times New Roman"
    fontsize: 12pt
    toc: true
    toc-depth: 3
    toc-location: right
    toc-expand: true
    toc-title: "On This Page"
    html-math-method: mathjax
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
editor: visual

