---
title: "Political Science Academy"
output: html_document
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
  line-height: 175%;
}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Welcome to the Political Science Academy

This is a collection of free materials and information on political science topics and methods that I have compiled over my years of studying political science. This website consists of 6 courses and 2 workshops, each covering a different topic in political science methodology.

# **THIS PAGE IS IN BETA - I WILL BE UPDATING THIS CONSTANTLY THROUGHOUT 2024-2025 SCHOOL YEAR. A LOT OF CONTENT IS MISSING.**

[About the Creator](#creator) \| [More Resources](#resources)

<br />

# Courses {#courses}

+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Course                                                         | Description                                                                                                                                                                                                                                                                               |
+================================================================+===========================================================================================================================================================================================================================================================================================+
| [**Stats I: Introduction to Stats and Probability**](#stats1)  | Introduction to basic probability theory and statistics needed for more advanced methods. Topics include Bayes' Rule, Probability Density Functions, Cumulative Density Functions, Expected Value, Distributions, Simple Hypothesis Testing.                                              |
+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [**Stats II: Regression Analysis**](#stats2)                   | Rigorous introduction to regression methods frequently used in the social sciences. Topics include Linear, Logistic, Poisson, and Negative Binomial Regressions.                                                                                                                          |
|                                                                |                                                                                                                                                                                                                                                                                           |
| (Coming Winter 2024)                                           |                                                                                                                                                                                                                                                                                           |
+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [**Stats III: Causal Inference and Research Design**](#stats3) | Rigorous introduction to experimental design and causal inference in political science. Topics include Selection on Observables, Randomised Experiments, Instrumental Variables, Regression Discontinuity, Differences in Differences, and Survey Experiments.                            |
|                                                                |                                                                                                                                                                                                                                                                                           |
| (Coming Winter 2024)                                           |                                                                                                                                                                                                                                                                                           |
+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [**Machine Learning I: Prediction Methods**](#machine1)        | Rigorous introduction to machine learning prediction methods that have been adopted in the social sciences. Topics include GAMs, Tree-Based Models, Cross Validation, Naive Bayes Classifier, Regularisation, Cluster Analysis, and Dimensional Reduction.                                |
+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [**Machine Learning II: Test Analysis**](#machine2)            | Rigorous introduction to the machine learning field of quantitative text analysis. Topics include Feature Selection, Dictionary Methods and Sentiment Analysis, Similarity Metrics, Classification for Text, Topic Models.                                                                |
+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [**Game Theory and Formal Modelling**](#games)                 | Rigorous introduction to Game Theory (Formal Modelling), and how these mathematical models can contribute to political science research. Topics include Nash Equilibrium, Electoral Competition Models, Mixed Strategies, Dynamic Games, Bayesian Games and Perfect Bayesian Equilibrium. |
|                                                                |                                                                                                                                                                                                                                                                                           |
| (Coming Winter 2024)                                           |                                                                                                                                                                                                                                                                                           |
+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [**Workshop: R Fundamentals**](#r)                             | This workshop provides some basics on R, including how to install packages, import and manage data, as well as visualise data.                                                                                                                                                            |
+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [**Workshop: Topics in Maths for Political Science**](#maths)  | This workshop provides a basic overview of essential mathematical topics in political science. Topics include Functions, Exponents and Logs, Summation and Product Notation, Derivatives, Partial Derivatives, Integrals, Probability Theory, Random Variables.                           |
+----------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Stats I: Introduction to Stats and Probability {#stats1}

*This is a basic introduction to statistical thinking and probability for Political Science. This course focuses on building the foundations for the applied methods taught in the subsequent Stats II: Regression Analysis and Stats III: Causal Inference and Research Design courses.*

Prerequisites: None, but an understanding of Algebra and some familiarity with topics covered in [Workshop: Topics in Maths for Political Science](#maths) would be recommended.

<br />

+---------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Lesson                                      | Topics                                                                                                             |
+=============================================+====================================================================================================================+
| **Data and Measurement**                    | Types of Variables, Operationalisation, Descriptive Statistics                                                     |
+---------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| **Probability I: Basic Probability Theory** | Counting, Sets, Probability, Bayes' Rule, Independence                                                             |
+---------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| **Probability II: Random Variables**        | Random Variables, Discrete and Continuous Distributions, Probability Density Function, Cumulative Density Function |
+---------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| **Probability III: Distributions**          | Expected Value, Variance, Uniform Distribution, Normal Distribution, Binomial Distribution, Joint Distributions.   |
+---------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| **Samples and Populations**                 | Sampling, Inference and Population, Data Visualisation                                                             |
+---------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| **Statistical Inference**                   | Hypothesis Testing, Chi-Square Tests, Difference in Means, Confidence Intervals                                    |
+---------------------------------------------+--------------------------------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

[Course List](#courses)

# Stats II: Regression Analysis {#stats2}

*Regression is one of the primary methods used in the social sciences to establish relationships between variables. This course is a rigorous introduction to regression techniques frequently used in the social sciences to find relationships between variables.*

*This course will utilise the **R language**. We will be using the **Tidyverse** package extensively. Other packages will be used for specific topics.*

Prerequisites: Topics covered in [Stats I: Introduction to Stats and Probability](#stats1). Some working knowledge of R and Maths to the level of [Workshop: R Fundamentals](#r) and [Workshop: Topics in Maths for Political Science](#maths) is also helpful.

<br />

+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Lesson                                                        | Topics                                                                                                    |
+===============================================================+===========================================================================================================+
| **Linear Regression I: Continuous Explanatory Variables**     | Simple Linear Regression and Multivariate Linear Regression with Continuous Explanatory Variables.        |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Linear Regression II: Complex Explanatory Variables**       | Categorical Explanatory Variables, Interaction/Moderating Effect, Non-Linear Relationships.               |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Linear Regression III: Hypothesis Testing and Assumptions** | Hypothesis Testing, Residual Diagnostics, Heteroscedasticity, Ourtiers, Adjusted $r^2$.                   |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Linear Regression IV: Non-Independent Data**                | Hierarchical Data, Multilevel Data, Panel Data, Fixed Effects Models, Pooled Regressions, Random Effects. |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Logistic Regression I: Binomial**                           | Binomial Logistic Regression, Estimation, Odds Ratios                                                     |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Logistic Regression II: Applications**                      | Fitted Probabilities, Classification, Likelihood Ratio Test                                               |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Logistic Regression III: Multinomial and Ordinal**          | Multinomial Logistic Regression, Ordinal Logistic Regression                                              |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Regression for Counts**                                     | Count Outcomes, Poisson Regression, Negative Binomial Regression.                                         |
+---------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+

<br />

OLD Pages (Accurate, but I will reorganise the content over the next school year).

1.  [**Single and Multivariate OLS Regression**](https://politicalscience.github.io/r/regression.html)
    -   Simple OLS Regression, Categorical X Variables, Multivariate OLS Regression
2.  [**Logistic Regression**](https://politicalscience.github.io/r/logistic.html)
    -   Binomial Logistic Regression, Odds Ratios/Relative Risk Ratio, Mutlinomial Logistic Regression

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Stats III: Causal Inference and Research Design {#stats3}

*In political science, we are primarily interested in establishing causal relationships. This course is a rigorous introduction to methods to establish causality, experimental design, and how to make causal inferences in political science.*

*This course will utilise the R language. We will be using the Tidyverse package extensively. Other packages will be used for specific topics.*

Prerequisites: Topics covered in [Stats I: Introduction to Stats and Probability](#stats1) and [Stats II: Regression Analysis](#stats2). Some working knowledge of R and Maths to the level of [Workshop: R Fundamentals](#r) and [Workshop: Topics in Maths for Political Science](#maths) is also helpful.

<br />

+------------------------------------+--------------------------------------------------------------------------+
| Lesson                             | Topics                                                                   |
+====================================+==========================================================================+
| **Causal Inference**               | Statistical Inference, Potential Outcomes Framework, Selection Bias      |
+------------------------------------+--------------------------------------------------------------------------+
| **Selection on Observables**       | Control Variables, Assumptions, Estimate of Average Treatment Effect.    |
+------------------------------------+--------------------------------------------------------------------------+
| **Randomised Controlled Trials**   | Randomised Experiments, Estimation, Standard Error, Blocking.            |
+------------------------------------+--------------------------------------------------------------------------+
| **Instrumental Variables**         | Instrumental Variable Framework, Identifying Assumptions, Estimation.    |
+------------------------------------+--------------------------------------------------------------------------+
| **Regression Discontinuity**       | Regression Discontinuity, Estimation, Bandwidth Selection, Validation    |
+------------------------------------+--------------------------------------------------------------------------+
| **Differences in Differences**     | Differences in Differences, Estimation, Threats to Validity, Application |
+------------------------------------+--------------------------------------------------------------------------+
| **Survey Experiments**             | Surveys, Vignette Experiments, List Experiments, Conjoint Experiments    |
+------------------------------------+--------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Machine Learning I: Prediction Methods {#machine1}

*Sometimes in political science, we are more concerned with prediction accuracy, rather than causality or explainability. The traditional OLS regression and Logistic regression, while good for finding relationships and easy to interpret, often lack in accuracy compared to more modern machine learning methods. This course is a rigorous introduction to machine learning prediction methods that have been adopted in the social sciences. This course focuses on supervised learning, but includes a few topics of unsupervised learning.*

*This course will utilise the R language. We will be using the Tidyverse package extensively. Other packages will be used for specific topics.*

Prerequisites: Topics covered in [Stats I: Introduction to Stats and Probability](#stats1) and [Stats II: Regression Analysis](#stats2). Some working knowledge of R and Maths to the level of [Workshop: R Fundamentals](#r) and [Workshop: Topics in Maths for Political Science](#maths) is also helpful.

<br />

+-------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
| Lesson                                                                                                | Topics                                                                                                                          |
+=======================================================================================================+=================================================================================================================================+
| **Non-Linear Methods and Generalised Additive Models**                                                | Polynomial Regressions, Step Functions, Splines, Local Linear Regression, Generalised Additive Models                           |
+-------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
| **Model Selection, Validation, and Resampling**                                                       | Bias/Variance, Training/Testing Sets, K-Fold Cross Validation, Bootstrap Sampling                                               |
+-------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
| [**Tree-Based Prediction Methods**](https://politicalscience.github.io/machine_learning_1/trees.html) | Regression Trees, Bagging (Bootstrap Aggregation), Random Forest, Importance Plots                                              |
+-------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
| **Classification Prediction Models**                                                                  | Naive Bayes Classifier, Tree-Based Classifiers, Evaluation of Classification Models (Confusion Matrix, Sensitivity/Specificity) |
+-------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
| **Regularisation Methods**                                                                            | Ridge Regression, Lasso Regression, Tuning Grid for Lambda Parameter                                                            |
+-------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
| **Unsupervised Learning I: Cluster Analysis**                                                         | K-Means Clustering, Hierarchical Clustering                                                                                     |
+-------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+
| **Unspervised Learning II:Dimensional Reduction**                                                     | Principle Component Analysis                                                                                                    |
+-------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Machine Learning II: Text Analysis {#machine2}

*A lot of modern political data takes the form of text: constitutions, political manifestos, political platforms, and political speeches. The development of quantitative text analysis methods in machine learning allows us to analyse textual data on a large scale relatively efficiently. This course is a rigorous introduction to the machine learning field of quantitative text analysis, allowing us to quantify texts and documents to better understand textual data.*

*This course will utilise the R language. We will be using two packages extensively: Tidyverse and Quanteda.*

Prerequisites: Topics covered in [Machine Learning I: Prediction Methods](#machine1), as well as [Stats I: Introduction to Stats and Probability](#stats1) and [Stats II: Regression Analysis](#stats2). Some working knowledge of R and Maths to the level of [Workshop: R Fundamentals](#r) and [Workshop: Topics in Maths for Political Science](#maths) is also helpful.

<br />

+-----------------------------------------------+-------------------------------------------------------------------+
| Lesson                                        | Topics                                                            |
+===============================================+===================================================================+
| **Feature Selection**                         | Document Feature Matrices (DFMs), Bag of Words, N-grams, Trimming |
+-----------------------------------------------+-------------------------------------------------------------------+
| **Dictionary Methods and Sentiment Analysis** |                                                                   |
+-----------------------------------------------+-------------------------------------------------------------------+
| **Similarity Metrics**                        |                                                                   |
+-----------------------------------------------+-------------------------------------------------------------------+
| **Classification Methods for Text**           | Naive Bayes Classifier                                            |
+-----------------------------------------------+-------------------------------------------------------------------+
| **Topic Modelling**                           | Latent Dirichlet Allocation, Structural Topic Models              |
+-----------------------------------------------+-------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Game Theory and Formal Modelling {#games}

*Game Theory is a branch of mathematics, originally created to solve games like Chess. However, social scientists began noticing that games - or instances involving strategic interaction - were all over the social sciences. For example, competition in an oligopoly, competition of political parties, competition between world superpowers, are all examples of strategic interaction. Game Theory models these strategic interactions assuming individuals act rationally, which allows us to see model outcomes of strategic competition, and also identify when actors do not act rationally.*

*This course introduces Game Theory (Formal Modelling), and how these mathematical models can contribute to political science research.*

Prerequisites: Working Knowledge of Algebra. Some working knowledge of maths to the level of [Workshop: Topics in Maths for Political Science](#maths) is also helpful, but not required.

<br />

+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lesson                                    | Topics                                                                                                                                               |
+===========================================+======================================================================================================================================================+
| **Essential Definitions**                 | Key Definitions, Preferences, Definitions.                                                                                                           |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Nash Equilibria**                       | Prisoner's Dilemma Game, Dominant Strategy, Solution Concepts, Definition of Nash Equilibrium.                                                       |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Applications of Nash Equilibria**       | Assurance Game, Cournot Equilibria                                                                                                                   |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Electoral Competition Models**          | Hotelling Model, Downsian Models and Median Voter Theory, Model of Public Finance                                                                    |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Mixed Strategies**                      | Mixed Strategy Definition, Mixed strategy Equilibria, Valence Politics Model                                                                         |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Dynamic Games of Complete Information** | Dynamic/Sequential Games, Extensive Form, Subgame Perfect Nash Equilibria, Legislative Models.                                                       |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Repeated Games**                        | Equilibria of Finitely Repeated Games, Infinitely Repeated Games, Nash Threats Folk Theorem, Minimax Threats Folk Theorem, Collusive Industry Model. |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Static Bayesian Games**                 | Incomplete Information, Battle of the Sexes, Bayesian Nash Equilibrium, BNE and Mixed Strategy Equilibria.                                           |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Dynamic Bayesian Games**                | Dynamic Bayesian Games, Player Beliefs, Restriction of Beliefs, Perfect Bayesian Equilibrium.                                                        |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Advanced Applied Game Theory**          | Rentseeking, Tullock Paradox, Selection and Incentives in Elections, Other Applications.                                                             |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Workshop: R Fundamentals {#r}

*R is a programming language that is commonly used for statistics and data science, particularly in academia. As you will probably have noticed, many of the courses in this website utilise R. This section will have some R guides on some fundamental techniques needed for the other courses.*

*This course is not meant to be a complete and full introduction to R. It is best to view this course as a reference guide after you have the basics of R down. [Resources for learning R](#resources).*

Prerequisites: none.

<br />

+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| **Lesson**                                                                          | Col2                                                                                                |
+=====================================================================================+=====================================================================================================+
| **Fundamentals of R**                                                               | How to install and load packages, variable types, assignment and pipe operator, other operators.    |
+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| [**Managing Data in R**](https://politicalscience.github.io/r/managing_data.html)   | Import data into R, selecting and filtering, adding columns, renaming columns, merging datasets.    |
+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| [Visualizing Data in R](https://politicalscience.github.io/r/visualizing_data.html) | Ggplot package, Histograms, boxplots, and scatterplots with best fit lines, pairs and correlations. |
+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| **Long and Wide Data in R**                                                         | Long and wide data formats, pivot longer, pivot wider.                                              |
+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Workshop: Topics in Maths for Political Science {#maths}

*While most political scientists will not need to be math wizards, it is useful to have a baseline understanding of some math to help with the statistics and data science approaches commonly used in political science.*

*This course is more of a refresher course for mathematics: consult it to refresh your memory on some core mathematics topics. If you want to learn mathematics topics for the first time, Khan Academy has great videos and practice exercises. MIT also offers Calculus courses for free on MIT Coursewear.*

<br />

+-----------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Lesson                                                                                              | Topics                                                                                                                                  |
+=====================================================================================================+=========================================================================================================================================+
| [**Topics in Algebra for Political Science**](https://politicalscience.github.io/math/algebra.html) | Definition of Function, Zeroes and Roots, Limits and Continuity, Exponent Rules, Logarithm Rules, Summation Notation, Product Notation. |
+-----------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| **Calculus I: Derivatives**                                                                         | Simple Derivatives, Composite Functions and Chain Rule, Partial Derivatives                                                             |
+-----------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| **Calculus II: Integration**                                                                        | Definite Integrals, Indefinite Integrals                                                                                                |
+-----------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| **Constrained Optimisation**                                                                        | Maximia and Minima, Constrained Optimisation                                                                                            |
+-----------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| **Probability Theory**                                                                              | Sets, Probability Basics, Bayes Rule, Random Variables and Distributions                                                                |
+-----------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

# Further Information

#### About the Creator {#creator}

This handbook was created by Kevin Lingfeng Li, in R-Markdown!

-   [LinkedIn](https://www.linkedin.com/in/kevinlingfengli/) \| [Personal Website](https://kevinli03.github.io)

I completed my undergraduate in BSc Politics at King's College London, focusing on statistical methods and game theory, obtaining a First-Class Honours (US equivalent: Summa Cum Laude) classification. I then went on to pursue a MSc in Political Science & Political Economy at the London School of Economics (LSE).

I created this handbook as a helpful guide while studying for my Masters degree. I realised that I had learned a ton of methods, but could not remember the syntax for all of them. Online resources often over-complicated the functions needed for political science analysis. Thus, in my free time, I created this handbook as a quick guide to implementing common statistical techniques.

I do my best to update this handbook: it is a tool not only for my classmates and other political science students, but for me myself. However, as a full-time student with an internship, I may not be able to update this site at a fast enough pace.

<br />

------------------------------------------------------------------------

#### Resources for Learning Statistics and R-Programming {#resources}

-   For those who need an introduction to statistics, I recommend the **Khan Academy** course on AP Stats for a mathematical introduction: <https://www.khanacademy.org/math/ap-statistics>

-   There is also a terrific free textbook on **Statistical learning with applications to R**: <https://www.statlearning.com>

-   **BurkeyAcademy** provides free online econometrics courses and implementations in R: <https://www.burkeyacademy.com/statistics-econometrics>

-   For more advanced individuals who want to learn more in-depth about statistics, see this excellent **MIT lecture series**: <https://www.youtube.com/playlist?list=PLUl4u3cNGP61ATaGTFcSp7bhogloD2wHP>

-   A free resource to learn R with is **CodeAcademy**: <https://www.codecademy.com/enrolled/courses/learn-r>

-   For those who have spare cash to spend, there is an excellent R programming course **(Data Analysis with R) offered by IBM on Coursera**, which teaches R and statistics: <https://www.coursera.org/learn/data-analysis-with-r>

-   I also highly recommend those who can afford it, to attend the **London School of Economic (LSE) Summer School**, which has an excellent course - **ME314 Introduction to Data Science and Machine Learning**. Many of these methods are covered in depth in this course, and the course is run by one of the developers of Quanteda, the main textual-analysis R package.

------------------------------------------------------------------------

The contents of this handbook are advisory: they should not be taken as gospel. The contents of this handbook are accurate to the best of my ability, as of August 2024. Later updates to R and packages may result in errors.
