---
title: "Political Science Academy"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
---

### Welcome to the Political Science Academy

This is a collection of free materials and information on political science topics and methods that I have compiled over my years of studying political science. This website consists of 8 courses and 1 workshop, each covering a different topic in political science methodology.

**THIS PAGE IS INCOMPLETE - I WILL BE UPDATING THIS CONSTANTLY THROUGHOUT 2024-2025 SCHOOL YEAR.**

[About the Creator](#creator) \| [More Resources](#resources)

------------------------------------------------------------------------

# Courses {#courses}

#### Introductory Courses:

+:--------------------------------------------------------------------------:+:-------------------------------------------------------------------------------:+
| [**Maths for Political Science**](https://politicalscience.github.io/math) | [**Introductory Statistical Theory**](https://politicalscience.github.io/stats) |
|                                                                            |                                                                                 |
| *The foundational maths needed for Political Science methodology*          | *Basics of statistics and probability needed for most statistical methods.*     |
|                                                                            |                                                                                 |
| 1st Half Lectures Available                                                | Coming Soon                                                                     |
+----------------------------------------------------------------------------+---------------------------------------------------------------------------------+

<br />

#### Standard Method Courses:

+:---------------------------------------------------------------------------------:+:-----------------------------------------------------------------------------:+
| [**Regression Analysis**](#regression)                                            | [**Causal Inference**](#causal)                                               |
|                                                                                   |                                                                               |
| *Detailed analysis of linear and logistic regression, and regression for counts.* | *Topics in experimental design and causal inference techniques for research.* |
|                                                                                   |                                                                               |
| Coming Fall/Winter 2024                                                           | Coming Fall/Winter 2024                                                       |
+-----------------------------------------------------------------------------------+-------------------------------------------------------------------------------+

<br />

#### Advanced Method Courses:

+:---------------------------------------------------------------------:+:----------------------------------------------------------------:+
| [**Applied Machine Learning**](https://politicalscience.github.io/ml) | **Multivariate Analysis**                                        |
|                                                                       |                                                                  |
| *More accurate prediction methods beyond the simple linear models.*   | *Advanced topics in dimensional reduction and latent variables.* |
|                                                                       |                                                                  |
| 1st Half Lectures Available                                           | Coming Spring 2025                                               |
+-----------------------------------------------------------------------+------------------------------------------------------------------+

<br />

#### Other Methods:

+:-----------------------------------------------------------------------:+:------------------------------------------------------------------------:+
| [**Game Theory and Formal Modelling**](#games)                          | [**Quantitative Text Mining**](#text)                                    |
|                                                                         |                                                                          |
| *Using mathematics to model decision making and strategic competition.* | *Using machine learning and R to quantify and numerically analyse text.* |
|                                                                         |                                                                          |
| Coming Fall/Winter 2024                                                 | Coming Spring 2024                                                       |
+-------------------------------------------------------------------------+--------------------------------------------------------------------------+

<br / >

Also, a short [**Workshop: R Fundamentals**](#r) to introduce the R language.

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Regression Analysis {#regression}

*This course is a rigorous introduction to regression techniques frequently used in the social sciences to find relationships between variables.*

Prerequisites: Topics covered in [Intro to Statistical Inference](#intro_stats). Some working knowledge of R and Maths to the level of [Workshop: R Fundamentals](#r) and [Maths for Political Science](#maths) is also helpful.

<br />

+----------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Lesson                                             | Topics                                                                                                    |
+====================================================+===========================================================================================================+
| **Linear I: Continuous Explanatory Variables**     | Simple Linear Regression and Multivariate Linear Regression with Continuous Explanatory Variables.        |
+----------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Linear II: Complex Explanatory Variables**       | Categorical Explanatory Variables, Interaction/Moderating Effect, Non-Linear Relationships.               |
+----------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Linear III: Hypothesis Testing and Assumptions** | Hypothesis Testing, Residual Diagnostics, Heteroscedasticity, Ourtiers, Adjusted $r^2$.                   |
+----------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Linear IV: Non-Independent Data**                | Hierarchical Data, Multilevel Data, Panel Data, Fixed Effects Models, Pooled Regressions, Random Effects. |
+----------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Logistic I: Binomial**                           | Binomial Logistic Regression, Estimation, Odds Ratios                                                     |
+----------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Logistic II: Applications**                      | Fitted Probabilities, Classification, Likelihood Ratio Test                                               |
+----------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Logistic III: Multinomial and Ordinal**          | Multinomial Logistic Regression, Ordinal Logistic Regression                                              |
+----------------------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Regression for Counts**                          | Count Outcomes, Poisson Regression, Negative Binomial Regression.                                         |
+----------------------------------------------------+-----------------------------------------------------------------------------------------------------------+

<br />

OLD Pages (Accurate, but I will reorganise the content over the next school year).

1.  [**Single and Multivariate OLS Regression**](https://politicalscience.github.io/r/regression.html)
    -   Simple OLS Regression, Categorical X Variables, Multivariate OLS Regression
2.  [**Logistic Regression**](https://politicalscience.github.io/r/logistic.html)
    -   Binomial Logistic Regression, Odds Ratios/Relative Risk Ratio, Mutlinomial Logistic Regression

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Causal Inference {#causal}

*This course is a rigorous introduction to methods to establish causality, experimental design, and how to make causal inferences in political science.*

Prerequisites: Topics covered in [Intro to Statistical Inference](#intro_stats) and [Regression Analysis](#regression). Some working knowledge of R and Maths to the level of [Workshop: R Fundamentals](#r) and [Maths for Political Science](#maths) is also helpful.

<br />

+----------------------------------+--------------------------------------------------------------------------+
| Lesson                           | Topics                                                                   |
+==================================+==========================================================================+
| **Causal Inference**             | Statistical Inference, Potential Outcomes Framework, Selection Bias      |
+----------------------------------+--------------------------------------------------------------------------+
| **Selection on Observables**     | Control Variables, Assumptions, Estimate of Average Treatment Effect.    |
+----------------------------------+--------------------------------------------------------------------------+
| **Randomised Controlled Trials** | Randomised Experiments, Estimation, Standard Error, Blocking.            |
+----------------------------------+--------------------------------------------------------------------------+
| **Instrumental Variables**       | Instrumental Variable Framework, Identifying Assumptions, Estimation.    |
+----------------------------------+--------------------------------------------------------------------------+
| **Regression Discontinuity**     | Regression Discontinuity, Estimation, Bandwidth Selection, Validation    |
+----------------------------------+--------------------------------------------------------------------------+
| **Differences in Differences**   | Differences in Differences, Estimation, Threats to Validity, Application |
+----------------------------------+--------------------------------------------------------------------------+
| **Survey Experiments**           | Surveys, Vignette Experiments, List Experiments, Conjoint Experiments    |
+----------------------------------+--------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Game Theory and Formal Modelling {#games}

*Game Theory uses mathematical modelling of strategic interactions, assuming individuals act rationally, to see model outcomes of strategic competition. This course introduces Game Theory (Formal Modelling), and how these mathematical models can contribute to political science research.*

Prerequisites: Working Knowledge of Algebra. Some working knowledge of maths to the level of [Maths for Political Science](#maths) is also helpful, but not required.

<br />

+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lesson                                    | Topics                                                                                                                                               |
+===========================================+======================================================================================================================================================+
| **Essential Definitions**                 | Key Definitions, Preferences, Definitions.                                                                                                           |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Nash Equilibria**                       | Prisoner's Dilemma Game, Dominant Strategy, Solution Concepts, Definition of Nash Equilibrium.                                                       |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Applications of Nash Equilibria**       | Assurance Game, Cournot Equilibria                                                                                                                   |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Electoral Competition Models**          | Hotelling Model, Downsian Models and Median Voter Theory, Model of Public Finance                                                                    |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Mixed Strategies**                      | Mixed Strategy Definition, Mixed strategy Equilibria, Valence Politics Model                                                                         |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Dynamic Games of Complete Information** | Dynamic/Sequential Games, Extensive Form, Subgame Perfect Nash Equilibria, Legislative Models.                                                       |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Repeated Games**                        | Equilibria of Finitely Repeated Games, Infinitely Repeated Games, Nash Threats Folk Theorem, Minimax Threats Folk Theorem, Collusive Industry Model. |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Static Bayesian Games**                 | Incomplete Information, Battle of the Sexes, Bayesian Nash Equilibrium, BNE and Mixed Strategy Equilibria.                                           |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Dynamic Bayesian Games**                | Dynamic Bayesian Games, Player Beliefs, Restriction of Beliefs, Perfect Bayesian Equilibrium.                                                        |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Advanced Applied Game Theory**          | Rentseeking, Tullock Paradox, Selection and Incentives in Elections, Other Applications.                                                             |
+-------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Quantitative Text Mining {#text}

*A lot of modern political data takes the form of text: constitutions, political manifestos, political platforms, and political speeches. This course is a rigorous introduction to the machine learning field of quantitative text analysis, allowing us to quantify texts and documents to better understand textual data.*

Prerequisites: Topics covered in [Applied Machine Learning](#machine), as well as [Intro to Statistical Inference](#intro_stats) and [Regression Analysis](#regression). Some working knowledge of R and Maths to the level of [Workshop: R Fundamentals](#r) and [Topics in Maths for Political Science](#maths) is also helpful.

<br />

+--------------------------------------------------+-------------------------------------------------------------------------------------+
| Lesson                                           | Topics                                                                              |
+==================================================+=====================================================================================+
| **Description Statistics and Feature Selection** | Summary Measures, Document Feature Matrices (DFMs), Bag of Words, N-grams, Trimming |
+--------------------------------------------------+-------------------------------------------------------------------------------------+
| **Dictionary Methods and Sentiment Analysis**    | Automated dictionary methods, Applications of dictionaries.                         |
+--------------------------------------------------+-------------------------------------------------------------------------------------+
| **Classification Methods for Text**              | Naive Bayes Classifier, Validation, Applications.                                   |
+--------------------------------------------------+-------------------------------------------------------------------------------------+
| **Supervised Scaling Models**                    | Wordscores method, Link between Classification and Scaling                          |
+--------------------------------------------------+-------------------------------------------------------------------------------------+
| **Unsupervised Scaling Models**                  | Poisson Distributed Methods (Wordfish ans Wordshoal), Correspondence Analysis       |
+--------------------------------------------------+-------------------------------------------------------------------------------------+
| **Similarity and Clustering Methods**            | Similarity metrics, hierarchical clustering, K-means clustering, weighting methods. |
+--------------------------------------------------+-------------------------------------------------------------------------------------+
| **Topic Models**                                 | Latent Dirichlet Allocation, Structural Topic Models                                |
+--------------------------------------------------+-------------------------------------------------------------------------------------+
| **Word Embeddings**                              | Word Embeddings                                                                     |
+--------------------------------------------------+-------------------------------------------------------------------------------------+
| **Intro to Neural Network Models**               | Neural Network Models.                                                              |
+--------------------------------------------------+-------------------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

[Course List](#courses)

# Workshop: R Fundamentals {#r}

*R is a programming language that is commonly used for statistics and data science, particularly in academia. This section will have some R guides on some fundamental techniques needed for the other courses.*

*This course is not meant to be a complete and full introduction to R. It is best to view this course as a reference guide after you have the basics of R down. [Resources for learning R](#resources).*

Prerequisites: none.

<br />

+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| **Lesson**                                                                          | Col2                                                                                                |
+=====================================================================================+=====================================================================================================+
| **Fundamentals of R**                                                               | How to install and load packages, variable types, assignment and pipe operator, other operators.    |
+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| [**Managing Data in R**](https://politicalscience.github.io/r/managing_data.html)   | Import data into R, selecting and filtering, adding columns, renaming columns, merging datasets.    |
+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| [Visualizing Data in R](https://politicalscience.github.io/r/visualizing_data.html) | Ggplot package, Histograms, boxplots, and scatterplots with best fit lines, pairs and correlations. |
+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| **Long and Wide Data in R**                                                         | Long and wide data formats, pivot longer, pivot wider.                                              |
+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

# Further Information

#### About the Creator {#creator}

This handbook was created by Kevin Lingfeng Li, in R-Markdown!

-   [LinkedIn](https://www.linkedin.com/in/kevinlingfengli/)

I am a candidate for a MSc in Political Science & Political Economy at the London School of Economics (LSE). Prior to my Masters, I completed a BSc in Politics at King's College London, focusing on statistical methods and game theory, obtaining a First-Class Honours (US equivalent: Summa Cum Laude) classification.

I created this handbook as a helpful guide while studying for my Masters degree. I realised that it would be useful for me, and for my fellow students, to have a collection of Political Science resources in one place.

I do my best to update this handbook: it is a tool not only for my classmates and other political science students, but for me myself. However, as a full-time student with an internship, I may not be able to update this site at a fast enough pace.

<br />

------------------------------------------------------------------------

#### Resources for Learning Statistics and R-Programming {#resources}

-   For those who need an introduction to statistics, I recommend the **Khan Academy** course on AP Stats for a mathematical introduction: <https://www.khanacademy.org/math/ap-statistics>

-   There is also a terrific free textbook on **Statistical learning with applications to R**: <https://www.statlearning.com>

-   **BurkeyAcademy** provides free online econometrics courses and implementations in R: <https://www.burkeyacademy.com/statistics-econometrics>

-   For more advanced individuals who want to learn more in-depth about statistics, see this excellent **MIT lecture series**: <https://www.youtube.com/playlist?list=PLUl4u3cNGP61ATaGTFcSp7bhogloD2wHP>

-   A free resource to learn R with is **CodeAcademy**: <https://www.codecademy.com/enrolled/courses/learn-r>

-   For those who have spare cash to spend, there is an excellent R programming course **(Data Analysis with R) offered by IBM on Coursera**, which teaches R and statistics: <https://www.coursera.org/learn/data-analysis-with-r>

-   I also highly recommend those who can afford it, to attend the **London School of Economic (LSE) Summer School**, which has an excellent course - **ME314 Introduction to Data Science and Machine Learning**. Many of these methods are covered in depth in this course, and the course is run by one of the developers of Quanteda, the main textual-analysis R package.

------------------------------------------------------------------------

The contents of this handbook are advisory: they should not be taken as gospel. The contents of this handbook are accurate to the best of my ability, as of August 2024. Later updates to R and packages may result in errors.