---
title: "Topics in Algebra"
subtitle: "Module 1, Mathematics for Political Science"
format:
    html:
        theme: lumen
        max-width: 800px
        toc: TRUE
        toc-depth: 3
        toc-location: left
        toc-title: Chapters
        toc-expand: TRUE
---

**Description**: This module will provide the foundations of algebra, that are essential for the remainder of the modules

-   We start off with set theory - which provides important notation and concepts for the rest of the course, and for all political science methods

-   Then, we discuss key algebra concepts needed for more advanced concepts

-   Finally, we introduce functions and limits, which are the building blocks of calculus, game theory, and statistics

**Prerequisites**: High-School level Algebra

------------------------------------------------------------------------

[Mathematics for Political Science Homepage](https://politicalscience.github.io/#mathematics-for-political-science)

# 1: Set Theory

### 1.1: Sets

A set, is any collection of objects

-   It could be a collection of all oranges in a basket

-   It could be a set of all possible fruits in the store

-   It could be the set of all things in the universe

The **set** is the collection of objects, while the **elements** of the set are the specific objects within a set

<br />

Sets have a formal way of being notated:

-   A capital letter represents a set. For example, the set $A$

-   A lowercase letter represents an element in that set. For example, element $a$ within set $A$

-   We can use any letters - just be consistent - the elements of a set should be the same as the letter of the set (ex. $b$ and $B$)

<br />

Common types of sets we use include:

-   $N$: Natural numbers - numbers we use to count 1 onwards $\{1, 2, 3, ... \}$

-   $W$: Whole numbers - counting numbers from 0 onwards $\{ 0, 1, 2, ... \}$

-   $Z$: Integers - non-decimal numbers both negative and positive $\{ ... ,-2, -1, 0, 1, 2, ... \}$

-   $Q$: Rational numbers - numbers that can be written as fractions

-   $R$: Real numbers: any numbers on the real number line, including irrational ones like $\pi$

-   $C$: Complex numbers - values with an imaginary pane (ex. $3 + 4i$)

<br />

### 1.2: Defining Sets

To define a set, we need some additional notation the following notation:

-   The symbol $\in$ means "in" or "belongs to"

    -   For example $a \in A$ means element $a$ belongs to set $A$

-   The symbol $:$ means "such that" - often used to specify a criteria

-   The symbol $\equiv$ means "is equivalent to" or "represents"

We also need to introduce interval notation:

-   $()$ parentheses on an interval imply not including the boundaries

    -   For example, interval $(a,b)$ implies $a < x < b$

-   $[]$ brackets on an interval imply including boundaries

    -   For example, interval $[a,b]$ implies $a ≤ x ≤ b$

-   We can also mix and match them, for example, $[a,b)$

<br />

We can define sets in many different ways.

-   We can list out all the elements of a set

    -   For example, $A = \{ 1, 2, 3, 4, 6, 9 \}$

-   We can define them with an interval

    -   For example, $A = [0,1]$

-   We can also define them in a very formal way as follows:

    -   For example, $A = \{x : 0 ≤ x ≤ 1, x \in R \}$

    -   That basically means, set $A$ is defined as the values of $x$ such that $x$ is between or equals $0$ and $1$, and $x$ belongs to the set of all real numbers $R$

<br />

### 1.3: Set Operators

There are a few different set operators that are important to understand.

**Intersection**: The overlap between two sets

-   The intersection of set $A$ and $B$ is notated as $A \cap B$

-   Basically, this means the set of elements that are contained in both set $A$ and $B$

-   For example, if $A = \{1,2,3 \}$, and $B = \{ 2, 3, 4 \}$, then $A \cap B = \{ 2, 3 \}$

-   If there is no overlap between $A$ and $B$, then we notate it as $A \cap B = \varnothing$

<br />

**Union**: The combination of two sets

-   The union of set $A$ and $B$ is notated as $A \cup B$

-   Basically, this means the combination of all elements in $A$ and $B$

-   For example, if $A = \{1,2,3 \}$, and $B = \{ 2, 3, 4 \}$, then $A \cup B = \{ 1,2,3,4 \}$

<br />

**Complement**: Everything not in a set

-   The complement of set $A$ is notated as $A'$ or $A^c$

-   Basically, this means all elements that are not in set $A$, but are part of the universal set

    -   Universal set basically means all the elements that are plausible in our current situation

-   So, if the universal set contains $\{ 1,2,3,4,5 \}$, and $A = \{ 1, 2 \}$, then $A^c = \{ 3,4,5 \}$

<br />

**Subset**: Meaning a set's elements, belongs entirely within another set

-   If $A$ is a subset of $B$, that means all elements of $A$ belong to $B$

-   There are two types of subsets - proper subsets, and improper subsets

-   Proper subsets are a subset, when the number of elements in $A$ is less than the number of elements in $B$

    -   In mathematically terms, $|A| < |B|$

    -   Proper subsets are notated as $A \subset B$

-   Improper subsets are a subset, when the number of elements in $A$ is less than OR EQUAL to the number of elements in $B$

    -   In mathematical terms, $|A| ≤ |B|$

    -   Improper subsets are notated as $A \subseteq B$

<br />

### 1.4: Properties of Set Operations

Set operations have a few key properties, that are important to understand. They are commonly used in probability and statistics.

**Commutative Property**: For unions and intersections, the order of the sets in which we do the operation does not matter

-   Essentially, $A \cup B = B \cup A; A \cap B = B \cap A$

<br />

**Associative Property**: For unions and intersections, the way sets are grouped does not change the result of the operation

-   Essentially, $A \cup (B \cup C) = (A \cup B) \cup C$

-   Also, $A \cap (B \cap C) = (A \cap B) \cap C$

<br />

**Distributive Property**: For unions and intersections, the following distributions apply:

-   $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$

-   $A \cup (B \cap C) = (A \cup B) \cap (A \cup C)$

<br />

**De Morgan's Law**: this critical law allows us to work with complements. It says the following:

-   $(A \cup B)^c = A^c \cap B^c$

-   $(A \cap B)^c = A^c \cup B^c$

<br />

------------------------------------------------------------------------

[Mathematics for Political Science Homepage](https://politicalscience.github.io/#mathematics-for-political-science)

# 2: Algebra Fundamentals

### 2.1: Equations and Inequalities

To solve an equation with 1 variable, we look to isolate the variable on one side. We do this by:

-   Adding/subtracting to both sides of the equation

-   Multiplying/Dividing the equation on both sides by the same value

<br />

**Example**:

Take the following equation: $\frac{x+3}{4} = 6$

1.  Multiply both sides by 4: $4 \left( \frac{x+3}{4} \right) = 6 \times 4$
2.  Now we have: $x+3 = 24$
3.  Then, subtract 3 from both sides: $x+3-3 = 24-3$
4.  Thus, we get: $x = 21$

<br />

For inequalities, we do the same, with one change:

-   If we multiply both sides by a negative number, we flip the direction of the sign

-   Ex. $-x < 1$, we multiply both sides by -1, and we get $x>-1$ with the sign flipped

<br />

### 2.2: System of Equations

To solve a system of equations, we do the following:

1.  With one of the equations, solve for one of the variables
2.  Subsitute that into the other equation - this will make it an equation with one variable
3.  Solve that equation for the remaining variable
4.  Then, plug the variable we have found, into either one of the equations, and find the value of the other variable

There are other ways to do this, such as elimination, but we will not worry about that for now.

<br />

**Example:**

Solve the following system of 2 equations:

$$
3x+2y = 13, \space x-2y = 3
$$

1.  First, let us solve one of the equations for one of the variables.
    -   Let us choose the second equation: $x-2y = 3$
    -   Solve for $x$: $x=2y+3$
2.  Now, plug the solution of $x$ into the other equation
    -   The other equation is $3x+2y=13$
    -   Plug in the $x$ we found: $3(2y+3) + 2y = 13$
3.  Now, solve that equation for the remaining variable
    -   The equation is $3(2y+3)+2y = 13$
    -   Expand the equation: $6y + 9 + 2y = 13$
    -   Combine like terms: $8y + 9 = 13$
    -   Isolate $y$: $8y = 4$
    -   Thus, $y = 1/2$
4.  Now, plug $y$ back into either equation to find $x$
    -   Let us use the equation: $x - 2y = 3$
    -   Plug in $y$: $x - 2(1/2) = 3$
    -   Simplify: $x - 1 = 3$
    -   Solve for $x$: $x = 4$

Thus, our solution is $(x = 4, y = 1/2)$

<br />

### 2.3: Factorisation and Difference of Squares

Factorisation is the process of changing an equation in the form of $ax^2+bx+c$, into the form of $(x+d)(x+e)$

How do we do this?

-   We need to find 2 numbers, $d$ and $e$, that sum to $b$, and multiply to $c$

-   Then, once we have found the 2 numbers $d$ and $e$, input them into the form above

<br />

**Factoring Example:**

Let us factor $x^2+5x+6$

-   We need to find two numbers, that add to 5, and multiply to get 6

    -   How do we do this? Well, think of all the possible numbers that can multiply to get 6

    -   These can include {1,6}, {2,3}, {-1,-6}, {-2,-3} (remember to consider negatives!)

    -   Now, which one of these adds to 5?

    -   Of course, {2,3} add to 5

-   Now we know the two numbers are 2 and 3, let us put it in the factor format $(x+d)(x+e)$

-   Thus, the factored answer is $(x+2)(x+3)$

<br />

There is a special case of factoring: **difference of squares**

Essentially, any expression that takes the form of $a^2 - b^2$, can be rewritten as $(a+b)(a-b)$

-   For example, the expression $x^2 - 9$ can be rewritten as $(x+3)(x-3)$

<br />

### 2.4 Multiplication Expansion

We can check our factorisation by expanding out $(x+2)(x+3)$

How do we multiply these two?

1.  Multiply the 1st element of the 1st group by the 1st element of the 2nd group: $x \times x$
2.  Multiply the 1st element of the 1st group by the 2nd element of the 2nd group: $x \times 3$
3.  Multiply the 2nd element of the 1st group by the 1st element of the 2nd group: $x \times 2$
4.  Multiply the 2nd element of the 1st group by the 2nd element of the 2nd group: $2 \times 3$

Basically - multiply each element of each group by all the other elements in the other group

Thus, the expansion is equal to:

$$
(x \times x) + (x \times 3) + (2 \times x) + (2 \times 3)
$$

$$
= x^2 + 3x + 2x + 6
$$

$$
=x^2 + 5x + 6
$$

And see that we have gotten the same answer as the original equation before factoring!

<br />

We can also use multiplication expansion to prove the difference of squares we explored in the previous section:

-   DIfference of squares says that $x^2-9$ can be rewritten as $(x+3)(x-3)$

-   Is this true? We can prove this by expanding $(x+3)(x-3)$, and see if it equals $x^2 - 9$

    -   We do the same process of expansion as above:

    -   $=(x \times x) + (x \times -3) + (3 \times x) + (3 \times -3)$

    -   $= x^2 -3x + 3x -9$

    -   $= x^2 - 9$, so indeed, difference of squares does work

<br />

------------------------------------------------------------------------

[Mathematics for Political Science Homepage](https://politicalscience.github.io/#mathematics-for-political-science)

# 3: Exponents & Logarithms

### 3.1: Exponents Properties

There are a few key properties of exponents that you need to keep in mind:

-   Product of exponents with same base: $a^x \times a^y = a{x + y}$

-   Negative exponents: $a^{-x} = \frac{1}{a^x}$

-   Division of exponents with same base: $a^x / a^y = a^{x-y}$

-   Exponent to an exponent: $(a^x)^y = a^{xy}$

-   Power of 0 is equal to 1: $a^0 = 1$

-   Power of a product: $(a \times b)^n = a^n \times b^n$

-   Power of a quotient: $(a/b)^n = a^n / b^n$

<br />

### 3.2: Solving Exponential Bases

Sometimes, you will have an equation that takes the form of $x^n = a$. To solve $x$, the solution is as follows:

$x = a^{(1/n)}$

How do we know this?

1.  Start with $x^n = a$. How can we get rid of the $n$ and isolate $x$?
2.  We know that $n \times \frac{1}{n} = 1$. But how do we multiply that when $n$ is in the exponent?
3.  Well, we have the property that $(a^x)^y = a^{xy}$. Thus, we know that $(x^n)^{(1/n)} = x^1 = x$
4.  But, if we take one side to the power of $1/n$, we must take the other side to the same power. Thus, we have the equation $(x^n)^{(1/n)} = a^{(1/n)}$
5.  Simplify, and we get $x = a^{(1/n)}$

<br />

**Example:**

Solve for $x$ in the equation $x^{0.7} = 5$

1.  We know the solution of an equation in the form of $x^n = a$ will be $x = a^{(1/n)}$
2.  So, let us identify $n$ and $a$. We know $n = 0.7$ and $a=5$ in the original equation
3.  Thus, the answer will be $x = 5^{(1/0.7)} = 5^{1.4828}$

<br />

### 3.3: Logarithms

Logarithms can be thought of the inverse for exponential functions. The relationship between the two are as follows:

$$
y = \log_a (x) \rightarrow a^y = x
$$

Or in more intuitive terms: $y=log_2(8)$ is basically asking, what power $y$ should I take $2$ to, in order to get a result of $8$

-   The answer, of course, is $3$

<br />

Logarithms have the following properties:

1.  Product within logs: $\log(xy) = \log(x) + \log(y)$
2.  Power within logs: $\log(x^y) = y \times log(x)$
3.  Negative logs: $- \log(x) = \log(1/x)$
4.  Division within logs: $\log(x/y) = \log(x) - \log(y)$
5.  Log of 1 is 0: $\log(1) = \log(e^0) = 0$

<br />

We can also change the base of logarithms with the following formula:

$$
\log_b (x) = \frac{ \log_a (x) }{ \log_a (b)}
$$

<br />

------------------------------------------------------------------------

[Mathematics for Political Science Homepage](https://politicalscience.github.io/#mathematics-for-political-science)

# 4: Sum & Product Notation

### 4.1: Summation Notation

Summation Notation is a way of expressing the sums of many values, and is commonly used in statistical techniques.

Summation notation is defined as the following:

$$
\sum\limits_{i=1}^n x_i = x_1 + x_2 + x_3 + ... + x_n
$$

-   $i=1$ indicates that we start summing at the index $i=1$. Sometimes, you will see $i=0$, and rarely, $i$ will be something else

-   $n$ is the value of the index at which we stop summing. This is often the sample size

-   $x_i$ is the value of set $X$ with index $i$. For example, if $i=1$, $x_i = x_1$ will be the 1st element in the set of $X$

    -   For example, if you have a dataset with 100 observations ( $n = 100$ ), you will have 100 elements within the set $X$, with $x_1$ being the 1st element, $x_2$ being the 2nd element, and $x_i$ being the $i$th element

<br />

Summation Notation has the following properties:

1.  Common factor within summation can be taken out: $\sum cx_i = c \sum x_i$
2.  Sum within summation: $\sum (x_i + y_i) = \sum x_i + \sum y_i$
3.  Summation of a constant: $\sum\limits_{i=1}^n c = n \times c$

<br />

### 4.2: Product Notation

Product notation is a short-hand way of expressing the products of many values, commonly used in Maximum Likelihood Estimation (MLE)

Product Notation is defined as the following:

$$
\prod\limits_{i=1}^n x_i = x_1 \times x_2 \times x_3 \times ... \times x_n
$$

-   $i=1$ indicates that we start multiplying at the index $i=1$. Sometimes, you will see $i=0$, and rarely, $i$ will be something else

-   $n$ is the value of the index at which we stop multiplying. This is often the sample size

-   $x_i$ is the value of set $X$ with index $i$. For example, if $i=1$, $x_i = x_1$ will be the 1st element in the set of $X$

    -   For example, if you have a dataset with 100 observations ( $n = 100$ ), you will have 100 elements within the set $X$, with $x_1$ being the 1st element, $x_2$ being the 2nd element, and $x_i$ being the $i$th element

<br />

Product Notation has the following properties:

1.  Constant within product notation: $\prod c x_i = c^n \prod x_i$
2.  Product of a constant: $\prod\limits_{i=1}^n c = c^n$

<br />

### 4.3 Converting Between Sum and Product

We can transition between summation notation and product notation with logarithms and their properties:

$$
\log \left( \prod\limits_{i=1}^n x_i \right) = \log(x_1 \times x_2 \times ... \times x_n)
$$

$$
= \log(x_1) + \log(x_2) + ... + \log(x_n)
$$

$$
= \sum\limits_{i=1}^n \log(x_i)
$$

<br />

We can also add a constant $c$ for a more general rule:

$$
\log \left( \prod\limits_{i=1}^n cx_i \right) = \log(cx_1 \times cx_2 \times ... \times cx_n)
$$

$$
= \log(c^n \times x_1 \times x_2 \times ... \times x_n)
$$

$$
= \log(c^n) + \log(x_1) + \log(x_2) + ... + \log(x_n)
$$

$$
=n \log(c) + \sum\limits_{i=1}^n \log(x_i)
$$

<br />

------------------------------------------------------------------------

[Mathematics for Political Science Homepage](https://politicalscience.github.io/#mathematics-for-political-science)

# 5: Functions

### 5.1 Dimensionality

$R^1$ is a one dimensional line - it is the set of all real numbers $R$ between $-∞$ and $∞$

-   In other words, it is just a normal number line

<br />

We can increase the number of dimensions to more than 1

-   $R^2$ is a two dimensional plane: Dimension 1 is the set of all real numbers $R$ between $-∞$ and $∞$, and dimension 2 is another set of all real numbers $R$ between $-∞$ and $∞$

    -   Think of a cartesian plane, where we graph lines in 2 dimensions, $x$ and $y$

-   Simlarly, $R^3$ is a 3 dimensional space

    -   Think of a 3D coordinate system with latitude, longitude, and height, 3 dimensions of $x$, $y$, and $z$

-   $R^n$ is a $n$-dimensional space, where there are $n$ different axes, each the set of all real numbers between $-∞$ and $∞$

    -   This is referred to as the Euclidean Space

<br />

### 5.2 Definition of Functions

A function is a rule that takes an input of $R^n$, and returns one, and only one number in $R^1$

-   Basically, for any specific input value(s), there must be only one output value

<br />

A function can have one variable input $R^1$, and an output of $R^1$

-   For example, $f(x) = x + 1$

-   The function takes an input of some $x$ in one dimension $R^1$, and outputs a real number in $R^1$

A function can have two variable input $R^2$, and an output of $R^1$

-   For example, $f(x,y) = x^2 + y^2$

-   This function takes inputs of both $x$ and $y$, a two dimensional space $R^2$, and outputs a real number in $R^1$

<br />

In political science, we commonly use $X$ to represent the input variable(s), and $Y$ to represent the output variable

-   If we have more than one dimension of input $R^n$ where $n > 1$, then we put subscripts on the $X$ to indicate additional input variables - $X_1, X_2, X_3...$

<br />

Key features of a function include:

-   The **domain**: The set of numbers in $X$ at which $f(x)$ is defined (produces a valid output)

-   The **range**: The set of elements $Y$ assigned by $f(x)$ to elements of $X$

    -   This is sometimes called the **image**, if the input of the function has more than 1 dimension

<br />

### 5.3: Types of Functions

Here are a few common types of functions that are commonly seen in Political Science applications:

-   **Monomials**: functions in the form of $f(x) = ax^k$

-   **Polynomials**: sums of multiply polynomials

    -   For example, $f(x) = ax^2 + bx + c$

    -   The "degree" of a polynomial is the $x^n$ term with the highest $n$

    -   Linear functions are polynomials with degree 1

-   Rational functions: the ratio of two polynomials

-   **Exponential functions**: when $x$ is in the exponent

    -   For example, $f(x) = 2^x$

-   Trigonometric functions: $f(x) = \cos(x), f(x) = \sin(x)$, etc.

    -   These are relatively uncommon in political science

<br />

Another type of function is **composite functions**:

-   Composite functions are when the output of one function, is used as the input of another

-   Basically, one function nested in another

Composite functions are defined as the following:

$$
f \circ g = f[g(x)]
$$

For example, if $h(x) = x^2$, and $f(x) = x-5$, then $f \circ h = (x)^2 - 5$

<br />

### 5.4: Zeroes and Roots

The zeroes/roots of functions, are the values of the input of the function, where the output of the function equals 0

-   Essentially, what $x$ values get you the output $f(x) = 0$

To solve for Zeroes/Roots, simply set the function equal to 0, and solve for $x$

-   Note: Some functions can have multiple roots (especially polynomials), so make sure to check you have gotten all the roots

<br />

For example, find the root of $f(x) = x - 5$

-   Set the function equal to 0: $0 = x - 5$

-   Solve for $x$: $x = 5$

<br />

For [quadratic functions]{.underline} (polynomials with a degree of 2), roots can be found in 2 different ways.

First, you can use **factorisation**: if a polynomial is factorisable, you can solve for the roots easily.

-   See section 2.3 Factorisation and Difference of Squares for information on how to do this

-   For example, find the roots of $f(x)=x^2+5x+6$

    1.  Set equation equal to 0: $0 = x^2+5x+6$

    2.  Factor: $0 = (x+2)(x+3)$

    3.  Now, find what $x$ values will get the equation to equal 0. This is quite easy - since $0 \times$ anything is $0$, we just need to either make $(x+2)=0$ and $(x+3) = 0$

    4.  Thus, our roots are $x = -2, x= -3$

Second, you can use the [quadratic formula]{.underline} for un-factorisable equations. Given a quadratic in the form of $ax^2 + bx + c$, the roots are:

$$
x = \frac{ -b ± \sqrt{b^2 - 4ac} }{2a}
$$

-   Note: the quadratic formula frequently returns 2 real zeroes/roots, but this is always not the case. Make sure to check both the $+$ and $-$ in the numerator

-   Note: sometimes, the quadratic formula returns imaginary roots - we will not worry about this as it has minimal applications in political science

<br />

------------------------------------------------------------------------

[Mathematics for Political Science Homepage](https://politicalscience.github.io/#mathematics-for-political-science)

# 6: Limits and Continuity

### 6.1 Definition of Limits

A limit is when a function approaches some specific output $y$ value $L$, as the input $x$ moves closer towards some value $c$

-   Often, $L$ is either $L=0$ or $L = ± ∞$

-   Approaching, basically means that as the $x$ value becomes infinitely closer towards $c$, the $y$ value approaches $L$

Limits are notated as follows:

$$
\lim\limits_{x \rightarrow c} f(x) = L
$$

<br />

For a limit to exist, it must approach the same $y$ value $L$, from both sides of $x=c$

-   For example, if from the left and right side as $x$ approaches $c$, $y$ approaches $∞$, we have a limit

-   Howevrer, if from the left side as $x$ approaches $c$, $y$ approaches $∞$, while from the right side as $x$ approaches $c$, $y$ approaches $-∞$, we do not have a limit, since they approach different values

Importantly, $f(x)$ does not need to be defined at point $x=c$ for the limit to exist. It just needs to approach the same value from both sides of $x=c$ until it gets infinitely close to $x=c$

<br />

If a limit does not exist because the function approaches a different $L$ from either side of $x=c$, we can still notate a [one-sided-limit]{.underline} as follows:

-   From the right side only: $\lim\limits_{x^+ \rightarrow c} f(x) = L$

-   From the left side only: $\lim\limits_{x^- \rightarrow c} f(x) = L$

<br />

Limits can take several different properties - which allow us to play with them algebraically:

Let us assume that $f$ and $g$ are functions, with $\lim\limits_{x \rightarrow c} f(x) = A$, and $\lim\limits_{x \rightarrow c} g(x) = B$. The following properties are thus true:

1.  $\lim\limits_{x \rightarrow c} [f(x) + g(x)] = \lim\limits_{x \rightarrow c} f(x) + \lim\limits_{x \rightarrow c} g(x)$
2.  $\lim\limits_{x \rightarrow c} c f(x) = c \lim\limits_{x \rightarrow c} f(x)$
3.  $\lim\limits_{x \rightarrow c} f(x) \times g(x) = [\lim\limits_{x \rightarrow c} f(x)] \times [\lim\limits_{x \rightarrow c} g(x)]$
4.  $\lim\limits_{x \rightarrow c}[f(x)/g(x)] = [\lim\limits_{x \rightarrow c} f(x)] / [\lim\limits_{x \rightarrow c} g(x)]$

<br />

### 6.2: Continuity

Continuity is quite intuitive - if a function has no breaks or jumps within a certain interval, then it is continuous in that interval.

However, we can give a more formal definition using limits

Suppose that function $f$ has an interval containing point $c$. $f$ is continuous at point $c$, if these 2 criteria are both met:

1.  $\lim\limits_{x \rightarrow c} f(x)$ exists
2.  $\lim\limits_{x \rightarrow c} f(x) = f(c)$

<br />

Why is this the definition of limits?

1.  If the first criteria is met, we know that the function is approaching the same $y$ value, when it gets closer to $x=c$ on both sides.
    -   This makes sense, as if a function didn't approach the same value on both sides of a point, then there would be a jump, and thus, it would not be continuous
2.  If the second criteria is met, we know that the function at $x=c$ is defined, and is the same as the limit
    -   This makes sense - a function has to be defined at $c$ to be continuous at $c$, or else, there would be some kind of gap
    -   This also makes sense, as if the value at $c$ was different than the value it was approaching at $c$, then there would be some kind of jump, and the function would not be continuous

<br />

Continuity has a few properties:

1.  If function $f$ and $g$ are both continuous at $c$, then the following is true:
    1.  $f(x) + g(x)$ is continuous at $c$
    2.  $f(x) - g(x)$ is continuous at $c$
    3.  $f(x) \times g(x)$ is continuous at $c$
    4.  $|f(x)|$ is continuous at $c$
    5.  $\alpha f(x)$ is continuous at $c$, where $\alpha$ is a constant
2.  If the function $f$ and $g$ are both continuous at $x=c$, then $f(x)/g(x)$ is continuous at $x=c$, given that $g(c) ≠ 0$
3.  If $f$ is continuous in interval $[a, b]$, then $f$ has a maximum and minimum value within $[a,b]$

<br />

------------------------------------------------------------------------

[Mathematics for Political Science Homepage](https://politicalscience.github.io/#mathematics-for-political-science)