---
title: "1.1 Introduction to Sets"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 1.1, Maths for Political Science"
---

[Course Homepage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

1.  [Definition of Sets](#definition)
2.  [Set Notation](#notation)
3.  [Set Operators](#operators)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Definition of Sets {#definition}

A **set** is any collection of objects.

-   Could be a collection of all oranges in a basket.

-   Could be the set of all possible fruits in the store.

-   Could be the set of all things in the universe.

The **set** is the collection of objects, while the **elements** of the set are each specific object within the set.

<br />

The most common type of set in Political Science, is the set of all values that a particular variable can take.

-   A variable can take multiple values. For example, the GDP of a country can take a large number of values - any real number.

    -   Thus, the GDP is in the set of all real numbers.

-   Net immigration is a variable that can take any integer (whole positive number).

    -   Thus, net immigration is in the set of all integers.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Set Notation {#notation}

To understand statistics in Political Science, we need to understand set notation:

-   A capital letter represents a set. Let us define a set as $A$

-   A lowercase letter represents an element in that set. Let us define an element as $a$

-   We can use any letters - just be consistent: the elements of a set should be the same letter as the set (ex. $b$ and $B$).

<br />

We can represent $a$ as an element of set $A$ with the following notation:

$$
a \in A, \text{ where } \in\ \text{ means in}
$$

<br />

To define a set $A$, the simplest way is to list out all the elements that belong to $A$.

$$
A = \{1,2,3,5,10,11 \}
$$

<br />

We can also define set $A$ in different ways. If we want to write the set of all things within a range, we can write:

$$
A = [0, 1], \text{ set of all things between 0 & 1, including 0 & 1}
$$

$$
A = (0, 1), \text{ set of all things between 0 & 1, excluding 0 & 1}
$$

<br />

Finally, we can define $A$ using a variable $x$, and the operator $|$, which means "such that":

$$
A = \{x | x ≤ 1, x \in R \}
$$

The above means: Set A is equal to $x$, such that $x$ is less than or equal to $1$, and $x$ is in the set of real numbers $R$. We could also rewrite the set to:

$$
A = (-∞, 1]
$$

For the set of real numbers, we use $R$ as convention. Here are other commonly used sets and their notation:

-   Set of Natural Numbers: $N$

-   Set of integers: $Z$

-   Set of rational numbers: $Q$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Set Operators {#operators}

#### Intersection

Lets say that we have two sets: set $A$ and set $B$.

The **intersection** (overlap of the same elements) of $A$ and $B$ is notated:

$$
A \cap B 
$$

If the intersection (overlap of the same elements) of $A$ and $B$ is empty - i.e. the sets do not share any elements in common, the result of $A \cap B$ is the null set $\varnothing$, which simply means the set of nothing.

$$
A \cap B = \varnothing
$$

If the intersection (overlap of the same elements) of $A$ and $B$ does include some elements, we can define set $C$ as the overlap/intersection of $A$ and $B$

$$
A \cap B = C, \space C\text{ being the set of the intersection }
$$

<br />

#### Union

Lets say that we want to define a set $D$, that is the combination of all elements of set $A$ and $B$.

This is called the **union** of $A$ and $B$, and is notated:

$$
A \cup B = D, \space D \text{ containg all elements of } A \text { & } B
$$

<br />

#### Complement

The **complement** of a set $A$, is everything not in set $A$.

$$
A^c \text { or } A'\text{ is the complement of } A
$$

<br />

#### Subsets

The **subset** $A$ is a subset of set $B$, meaning all elements of $A$ also belong to $B$. This means the number of elements in $A$ must be less than or equal to the number of elements in $B$ ( $|A| ≤ |B|$ ).

If we are confident that $|A| < |B|$ and $|A| ≠ |B|$, this is a **proper subset**, where A is **contained** in B.

$$
A \subseteq B, \text{where we are unsure if } |A| < |B|
$$

$$
A \subset B, \text{where we are sure } |A| < |B|, \text{ a proper subset}
$$

$$
A \not\subset B, \text{ where } |A| \subseteq |B| \text{ but } A=B, \text{ not proper subset}
$$

Note: $|A|$ and $|B|$ refer to the number of elements in a set.

<br />

#### Set Difference

Let us say $A \cap B ≠ \varnothing$ (meaning there is some overlap between $A$ and $B$ ). The **set difference** is set $A$, but with all values within set $A$ that also fall into set $B$ removed:

$$
A \setminus B = A - (A \cap B)
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)