---
title: "Functions"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 1.2, Maths for Political Science"
---

[Course Homepage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

1.  [Dimensionality](#dimensionality)
2.  [Definition of Function](#definition)
3.  [Zeroes and Roots](#roots)
4.  [Limits](#limits)
5.  [Continuity](#continuity)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Dimensionality {#dimensionality}

Before we describe functions, we need to understand **Dimensionality**:

-   $R^1$ , is a one dimensional line. It is the set of all real numbers between $-∞$ to $∞$.

    -   In other words, it is the real number line.

<br />

We can increase the number of dimensions to more than 1.

-   $R^2$ is a two dimensional plane. Dimension 1 is the set of all real numbers between $-∞$ and $∞$, and Dimensions 2 is another set of all real numbers between $-∞$ and $∞$.

    -   Think of a cartesian plane where we graph lines in 2 dimensions, $x$ and $y$

-   $R^3$ is a 3-dimensional space, with $x$, $y$, and $z$ axes, each the set of all real numbers between $-∞$ and $∞$.

    -   Think of a coordinate location system, for example, in the game Minecraft. $x$ is longitude, $y$ is latitude, and $z$ is height.

-   $R^n$ is an $n$-dimensional space, where each of the $n$ number of axes contains the set of all real numbers between $-∞$ and $∞$.

    -   This is often referred to as the Euclidean space.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Definition of Function {#definition}

A function is a rule, or a transformation, that takes an input of $R^n$, and returns one, and only one number in $R^1$

-   A function of one variable is an input of $R^1$ , and an output of $R^1$

    -   For example, $f(x) = x + 1$. This function takes an input of some $x$ in $R^1$, and returns a real number in $R^1$

-   A function of two variables is an input of $R^2$, and an output of $R^1$

    -   For example, $f(x,y) = x^2 + y^2$. This function takes an input of some $x$ and $y$ in $R^2$, and returns a real number in $R^1$

<br />

In political science, we often use $x$ to represent the input variable, and $y$ to represent the output variable.

If there are more than one input variables (input $R^n$ when $n > 1$ ), we often put subscripts on the $x$'s, such as: $x_1, x_2, ... , x_p$

Input variables $x$ in the space $R^n$ are called **independent** or **explanatory** variables. The output variable $y$ in space $R^1$ is called a **dependent** or **response** variable.

<br />

Some key properties of functions:

-   The **domain** of $f(x)$ is the set of numbers in $X$ at which $f(x)$ is defined.

-   The **range** of $f(x)$ is the elements of $Y$ assigned by $f(x)$ to elements of $X$

    -   This is sometimes called the **image** when input $R^n$ has $n > 1$

<br />

Common types of functions that we will see in Political Science include:

-   Monomials: in the form of $f(x) = ax^k$

-   Polynomials - the sum of monomials. The degree of a polynomial is its highest powered term.

    -   Example: $f(x) = 5x^3 + 3x^2 + 2x + 4$ is a 3rd degree polynomial

-   Rational Functions: the ratio of two polynomials.

    -   Example: $f(x)=\frac{x2+1}{x2-2x+1}$

-   Exponential Functions: when $x$ is the the exponent

    -   Example: $f(x)=2^x$

-   Linear functions: polynomials with degree 1: $f(x) = mx + b$

    -   These are very important for linear regression.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Zeroes and Roots {#roots}

Zeroes (or Roots) are the values of the input of a function, where the output of the function equals $0$.

-   Essentially, the value of $x$ when $f(x) = 0$

These are important in Political Science, as they are important in finding equilibria, as well as maximum likelihood estimation.

<br />

To solve for Zeroes/Roots, simply set the function $f(x) = 0$, and solve for $x$.

-   Alternatively, you can use a graphing programme, such as Desmos, to plot the function, and find at what $x$ does it cross the line $y = 0$

<br />

Some functions have multiple roots (especially polynomials). For example, consider the function $f(x) = x^2 - 16$. Let us solve for the roots:

$$
f(x) = x^2 - 16
$$

$$
0 = x^2 - 16
$$

$$
x^2 = 16
$$

$$
x = ±4
$$

<br />

For quadratic equations (polynomials of degree 2), there is a formula called the **Quadratic Formula** which solves for the roots:

$$
x = \frac{-b ± \sqrt{b^2-4ac}}{2a}
$$

<br />

Given the quadratic in the form of $f(x)=ax^2+bx+c$

Note: the quadratic formula generally returns 2 real zeroes/roots, but this is not always the case. Remember to check both the $+$ and $-$ in the numerator.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Limits {#limits}

A limit is when a function approaches some specific $y$ value $L$, as $x$ moves toward some value $c$.

-   Often, this specific $y$ value $L$ in question is either $L=0$ or $L=±∞$
-   Approaching basically means the $y$ value becomes infinitely close towards $L$, as the $x$ value becomes infinitely close to $c$

For a limit to exist, it must approach the same $y$ value $L$ from both sides of $x = c$

-   For example, if from the left as $x$ approaches $c$, $y$ approaches $∞$, and if from the right as $x$ appraoches $c$, $y$ approaches $∞$, we have a limit.

-   But, if from the left as $x$ approaches $c$, $y$ approaches $∞$, and if from the right as $x$ appraoches $c$, $y$ approaches $-∞$, we do not have a limit, because the $y$ value being approached on either side is not the same.

If a limit exists, we can say $\lim\limits_{x \rightarrow c} f(x) = L$

-   Note: $f(x)$ does not need to be defined at $x=c$ for the limit to exist. It just must approach the same $y=L$ on both sides infinitely close to $x=c$.

<br />

Let us assume $f$ and $g$ are functions with $\lim\limits_{x \rightarrow c} f(x) = A$ and $\lim\limits_{x \rightarrow c} g(x) = B$. The following properties include:

$$
1. \space\lim\limits_{x \rightarrow c} [f(x)+g(x)] = \lim\limits_{x \rightarrow c} f(x) + \lim\limits_{x \rightarrow c} g(x)
$$

$$
2. \space \lim\limits_{x \rightarrow c} \alpha f(x) = \alpha \lim\limits_{x \rightarrow c} f(x)
$$

$$
3. \space \lim\limits_{x \rightarrow c} f(x) * g(x) = [\lim\limits_{x \rightarrow c} f(x)] * [\lim\limits_{x \rightarrow c} g(x)]
$$

$$
4. \space \lim\limits_{x \rightarrow c} \frac{f(x)}{g(x)} = \frac{\lim\limits_{x \rightarrow c} f(x)}{\lim\limits_{x \rightarrow c} g(x)}, \space given \space \lim_{x \rightarrow c} g(x) ≠ 0
$$

<br />

We will expand on limits in the calculus topics. Limits are important because they lead to our definition of continuity.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Continuity {#continuity}

Continuity is an important concept for statistical applications. Most of us probably have an idea of what continuity is: a function has no breaks or jumps within a certain interval. Let us introduce a more formal definition.

<br />

Suppose that the function $f$ has an interval containing point $c$.

$f$ is continuous at point $c$, if these 2 criteria are both met:

1.  $\lim\limits_{x \rightarrow c} f(x)$ exists (i.e. it approaches the same $y$ value at $x=c$ on both sides.
2.  $\lim\limits_{x \rightarrow c} f(x) = f(c)$ (i.e. the value $f$ approaches on both sides of $x=c$, is also the value of $f$ at point $c$).

<br />

We can test our intuition about continuity with the above mathematical definition:

-   If the function has a break at point $c$, it won't be defined at $f(c)$. Thus, criteria 2 will not be met.

-   If the function has a sudden "jump" at point $c$, then $\lim\limits_{x \rightarrow c} f(x)$ won't exist, since it is approaching point $c$ towards two different $y$ values.

<br />

The following are properties of continuity:

-   If functions $f$ and $g$ are both continuous at $x=c$, and where $\alpha$ represents a constant, then the functions $f + g$, $f - g$, $f * g$ , $|f|$, and $\alpha * f$ are also continuous at $x = c$

-   If functions $f$ and $g$ are both continuous at $x=c$, then $f / g$ is continuous at $x=c$, given that $g(c) ≠ 0$

-   If $f$ is continuous at interval $[a,b]$, then $f$ has a maximum and mininum value within $[a,b]$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)