---
title: "1.3 Summation and Product Notation"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 1.3, Maths for Political Science"
---

[Course Homepage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

1.  Summation Notation
2.  Product Notation
3.  Converting Between Product and Summation Notation

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Summation Notation {#summation}

Summation Notation is a short-hand way of expressing the sums of many values.

Summation Notation is quite important in Political Science, as minimising the **sum of squared errors** is a key topic in Regression and advanced Data Science Techniques.

<br />

Summation Notation is defined as the following:

$$
\sum\limits_{i=1}^{n} x_i = x_1 + x_2 + x_3 + ... + x_n
$$

-   $i=1$ indicates that we start summing at the index $i=1$. Sometimes, you will see $i = 0$, and rarely, $i$ will be equal to something else.

-   $n$ is the value at which we stop summing. This is generally the sample size in statistics.

-   $x_i$ is the $x$ value at index value $i$. When $i = 1$, $x$ is $x_1$, when $i = 2$, $x$ is $x_2$, and so on.

-   What does index mean? Well, lets say you have a sample with 100 observations, so sample size $n=100$. Then, $x_1$ is the $x$ value of the 1st observation, $x_2$ is the $x$ value of the 2nd observation, and so on, until you reach the final observation $x_n$.

<br />

#### Properties of Summation Notation

These are the properties of Summation Notation, where $c$ is some constant number:

$$
1. \space \sum\limits_{i=1}^{n} cx_i = c \sum\limits_{i=1}^{n} x_i
$$

$$
2. \space \sum\limits_{i=1}^{n} (x_i + y_i) = \sum\limits_{i=1}^{n} x_i + \sum\limits_{i=1}^{n} y_i
$$

$$
3. \space\sum\limits_{i=1}^{n} c = n * c
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Product Notation {#product}

Product notation is a short-hand way of expressing the products of many values.

Product notation is quite important in Political Science, specifically in **Maximum Likelihood Estimation (MLE)**, the primary way of determining coefficient values in a Logistic Regression.

<br />

Product Notation is defined as the following:

$$
\prod\limits_{i=1}^{n} x_i = x_1 * x_2 * x_3 * x_4 * ... x_n
$$

-   $i=1$ indicates that we start multiplying at the index $i=1$. Sometimes, you will see $i = 0$, and rarely, $i$ will be equal to something else.

-   $n$ is the value at which we stop multiplying. This is generally the sample size in statistics.

-   $x_i$ is the $x$ value at index value $i$. When $i = 1$, $x$ is $x_1$, when $i = 2$, $x$ is $x_2$, and so on.

-   What does index mean? Well, lets say you have a sample with 100 observations, so sample size $n=100$. Then, $x_1$ is the $x$ value of the 1st observation, $x_2$ is the $x$ value of the 2nd observation, and so on, until you reach the final observation $x_n$.

<br />

#### Properties of Product Notation

These are the properties of Product Notation, where $c$ is some constant number:

$$
1. \space \prod\limits_{i=1}^{n} cx_i = c^n * \prod\limits_{i=1}^{n} x_i
$$

$$
2. \space \prod\limits_{i=1}^{n} c = c^n
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Converting Betwen Summation and Product Notation {#converting}

We can also transition between [Summation Notation](#4001) and Product Notation with Logarithms, which is important in Maximum Likelihood Estimation (MLE).

$$
log( \prod\limits_{i=1}^{n} x_i ) = log(x_1 * x_2 * x_3 * ... * x_n)
$$

$$
= log(x_1) + log(x_2) + log(x_3) + ... + log(x_n)
$$

$$
= \sum\limits_{i=1}^{n} log(x_i)
$$

<br />

We can also add a constant $c$ for a more general rule:

$$
log( \prod\limits_{i=1}^{n} cx_i) = log(cx_1 * cx_2 * ... * cx_n)
$$

$$
= log(c^n * x_1 * x_2 *... *x_n)
$$

$$
= log(c^n) + log(x_1) + log(x_2) + ... + log(x_n)
$$

$$
= n log(c) + \sum\limits_{i=1}^{n} log(x_i)
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)