---
title: 'Introduction to Derivatives'
output: html_document
subtitle: "Lesson 2.1, Maths for Political Science"
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
  line-height: 150%;
  }
  .main-container {
  max-width: 800px !important;
  margin: auto;
  }
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Course Homepage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Definition of Derivative {#definition}

A derivative is a function $f'(x)$, whose value at $x$ is the rate of change of $f(x)$ at $x$.

-   Basically, $f'(x)$ is the measure of the "slope" at any point of $x$ of $f(x)$

-   For linear functions, $f'(x)$ is a constant equivalent to the slope of the line.

-   For curved functions, $f'(x)$ is the slope of the line tangent to the curve at point $x$

<br />

A more formal definition of the derivative of $f$ at point $x$ is:

$$
f'(x) = \lim\limits_{h \rightarrow 0} \frac{f(x+h)-f(x)}{(x+h)-x} = \lim\limits_{h \rightarrow 0} \frac{f(x+h)-f(x)}{h}
$$

This is basically the mathematical representation of calculating the slope, but we change the distance to two points of a line infinitely close to $0$, so we can get the rate of change at a specific point $x$.

<br />

If $f'(x)$ exists at a point $x$, then $f$ is said to be differentiable at $x$.

If $f'(x)$ exists for every point in an interval, then $f$ is differentiable along that interval.

For $f'(x)$ to exist and $f$ to be differentiable, $f$ must be both continuous and smooth at $x$.

-   I.e. $f$ must have a value at $f(x)$, and should not have any sharp edges at $x$

<br />

#### Derivative Notation

So far, we have used the apostrophe $f'(x)$ to identify a derivative. Other alternative notation includes:

-   Prime or Lagrange Notation: $y'$, $f'(x)$

-   Operator Notation: $Dy$, $Df(x)$

-   Leibniz's Notation: $\frac{dy}{dx}$

<br />

It is also possible to take the derivative, of a derivative.

-   These are called Higher-Order Derivatives

For example, take $f(x) = x^3$

-   1st Derivative: $f'(x) = 3x^2$

-   2nd Derivative: $f''(x) = 6x$

-   3rd Derivative: $f'''(x) = 6$, and so on...

<br />

#### Application of Derivatives

Why are we interested in calculus and derivatives?

-   Calculus and Derivatives tell us about change: how does $f(x)$ change is expressed through $f'(x)$

-   Political science (and all social sciences) are about change.

-   For example, how $x \rightarrow y$ causal relationships are established, is how changes in $x$ effect $y$.

Applications of calculus and derivatives in political science includes:

-   Optimisation of Functions, such as in Statistics and Game Theory, when we want to find the maximum utility of a utility function, or minimise the error of our model.

-   Calculus is widely applicable to statistics theory and regression analysis.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Calculating Simple Derivatives {#calculation}

There are a few main rules in calculating simple derivatives. With these main rules, most simple derivatives are calculable.

Suppose that $f$ and $g$ are both differentiable at $x$, and that $\alpha$ is a constant:

$$
1. \space Power \space Rule: [x^k]'=kx^{k-1} 
$$

$$
2. \space Sum \space Rule: [f(x) ± g(x)]' = f'(x) ± g'(x)
$$

$$
3. \space Constant \space Rule:[\alpha f(x)]' = \alpha f'(x)
$$

$$
4. \space Product \space Rule:[f(x)g(x)]' = f'(x)g(x) + f(x)g'(x) 
$$

$$
5. \space Quotient \space Rule: [f(x)/g(x)]' = \frac{f'(x)g(x) - f(x)g'(x)}{[g(x)]^2}, \space given \space g(x)≠0
$$

$$
6. \space Linear \space Rule: [mx]' = m, \space given \space m \space is\space a \space constant
$$

$$
7.  \space Linear \space Rule: [c]' = 0, \space given \space c \space is\space a \space constant
$$

<br />

These rules don't come out of thin air - they are derived using the definition of a derivative, and plugging in $f(x)$ and $f(x+h)$:

$$
f'(x) = \lim\limits_{h \rightarrow 0} \frac{f(x+h)-f(x)}{(x+h)-x} = \lim\limits_{h \rightarrow 0} \frac{f(x+h)-f(x)}{h}
$$

We aren't going to prove the rules you saw above for calculating derivatives. But, if you have the time, you can plug the following functions in and manually solve for these rules above.

<br />

#### Example 1:

Find $f'(x)$ if $f(x) = 5x^4$

1.  Constant rule with $\alpha = 5$: $f'(x) = 5 * [x^4]'$
2.  Power rule $k=4$ the second part: $f'(x) =5 * 4x^3$
3.  Now, simplify: $f'(x) = 20x^3$

<br />

#### Example 2:

Find $f'(x)$ if $f(x) = 5x^4 - 6x^3 + x^2 - 4x + 6$

-   We know that the sum rule says: $[f(x) ± g(x)]' = f'(x) ± g'(x)$

-   So, we know in this case: $f'(x) = [5x^4]' - [6x^3]' + [x^2]' - [4x]' + [6]'$

-   Now, we apply the constant and power rule like in example 1 to every individual monomial: $f'(x) = 20x^3 - 18x^2 + 2x - 4 + 0$

-   Simplify: $f'(x) = 20x^3 - 18x^2 + 2x - 4$

<br />

#### Example 3:

Find $f'(x)$ if $f(x) = (x^3)(2x^4)$

-   We actually have two ways to find the derivative.

-   Let us first use the product rule: $[f(x)g(x)]' = f'(x)g(x) + f(x)g'(x)$

    -   We can make $f(x) = x^3$, and $g(x) = 2x^4$

    -   Then using constant and power rule like in example 1 to both monomials: $f'(x) = 3x^2$, and $g'(x) = 8x^3$

    -   Then, product rule: $[f(x)g(x)]' = (3x^2)(2x^4) + (x^3)(8x^3)$

    -   $[f(x)g(x)]' = 3*2*x^2*x^4 + 8*x^3*x^3$

    -   $[f(x)g(x)]' = 6x^6 + 8x^6 = 14x^6$

    -   Thus, $f'(x) = 14x^6$

-   We can check our answer with the constant + power rule method:

    -   First, let us simplify $f(x)$: $f(x) = (x^3)(2x^4) = 2x^7$

    -   Now, apply constant and power rule like in example 1: $f'(x) = 14x^6$

-   We get $f'(x) = 14x^6$ with both methods.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)
