---
title: "Chain Rule Derivatives"
output: html_document
subtitle: "Lesson 2.2, Maths for Political Science"
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
  line-height: 150%;
  }
  .main-container {
  max-width: 800px !important;
  margin: auto;
  }
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Course Homepage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

1.  [Composite Functions](#composite)
2.  [Chain Rule](#chain)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Composite Functions {#composite}

Composite functions are when we substitute one function into another.

-   For example, take $f(x) = x^2$, and $g(x) = 2x$

-   We could insert $g(x)$ as the input of $f(x)$

-   This would get us $f[g(x)] = (2x)^2$

<br />

We use the following notation to indicate composite functions:

$$
(f \circ g)(x) = f[g(x)]
$$

<br />

Please note, $(f \circ g)(x)$ and $(g \circ f)(x)$ are different functions.

$$
(g \circ f)(x) = g[f(x)]
$$

<br />

To from $(f \circ g)(x)$, the range of $g$ (the outputs of function $g$ ) must be contained, at least in part, within the domain of $f$.

-   Why? Well if none of the outputs of $g$ are in the domain of $f$, that means none of the inputs of $f(x)$ will be within its domain, meaning that there are no valid outputs of $(f \circ g)(x)$

-   The domain of $(f \circ g)(x)$ is all the points in the domain of $g$, for which the output of $g(x)$ is also the domain of $f$.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Chain Rule {#chain}

Chain Rule solves derivatives of $f$ that are in the form of composite functions. Chain Rule States:

$$
[(f \circ g)(x)]' = f'[g(x)] * g'(x)
$$

<br />

We can also create a Generalised Power Rule dealing with composite function $(f \circ g)(x)$ when $f(x)$ takes the form of $x^k$

$$
\frac{d}{dx} [g(x)]^k = k[g(x)]^{k-1} g'(x)
$$

<br />

#### Example 1:

Find $f'(x)$ if $f(x) = (2x)^2$

-   We have two ways to find the derivative.

-   Let us first use the chain rule: $[(f \circ g)(x)]' = f'[g(x)] * g'(x)$

    -   $f(x) = (2x)^2$ is the composite function $(f \circ g)(x)$ if $f(x) = x^2$ and $g(x) = 2x$

    -   Then, by power rule, $f'(x) = 2x$, and $g'(x) = 2$

    -   Now, apply chain rule: $[(f \circ g)(x)]' = 2(2x)*2$

    -   Simplify: $[(f \circ g)(x)]' = 8x$

-   We can also use the constant + power rule:

    -   Let us first rewrite $f(x)$: $f(x) = (2x)^2 = (2x)(2x) = 4x^2$

    -   Now, let us apply constant + power rule: $f'(x) = 8x$

-   We get $f'(x) = 8x$ with both methods.

<br />

#### Example 2:

Find $f'(x)$ if $f(x) = (3x^2 + 5x - 7)^6$

-   We have two ways to find the derivative.

-   First, let us use the chain rule: $[(f \circ g)(x)]' = f'[g(x)] * g'(x)$

    -   $f(x) = (3x^2 + 5x - 7)^6$ is the composite function $(f \circ g)(x)$ if $f(x) = x^6$ and $g(x) = 3x^2 + 5x - 7$

    -   Using power rule, we know $f'(x) = 6x^5$

    -   Using Sum Rule with constant + power rule on each monomial, we know that $g'(x)=6x + 5$

    -   Now, apply chain rule: $[(f \circ g)(x)]' = 6(3x^2+5x-7)^5*(6x+5)$

-   Second, let us use the generalised power rule: $\frac{d}{dx} [g(x)]^k = k[g(x)]^{k-1} g'(x)$

    -   In this format, we know $g(x)$ is what is in the base of the polynomial: $g(x) = 3x^2 + 5x - 7$

    -   Now, apply generalised power rule where $k=6$ : $\frac{d}{dx} [g(x)]^k = 6(3x^2+5x-7)^5 * (6x+5)$

-   For both, we get $f'(x) = 6(3x^2+5x-7)^5 * (6x+5)$

-   This isn't a very elegant solution, but it is difficult to simplify. We could multiply out the $(6x+5)$ to get $f'(x) = 36x(3x^2+5x-7)^5+30(3x^2+5x-7)^4$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)
