---
title: "Exponent and Log Derivatives"
output: html_document
subtitle: "Lesson 2.3, Maths for Political Science"
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
  line-height: 150%;
  }
  .main-container {
  max-width: 800px !important;
  margin: auto;
  }
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Course Homepage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

1.  D[erivatives of Exponential Functions](#exponentials)
2.  [Derivatives of Logarithms](#logarithms)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Derivatives of Exponential Functions {#exponentials}

Here are the main properties for derivatives of exponential functions with base $e$

$$
1. \space \frac{d}{dx} e^x = e^x 
$$

$$
2. \space \frac{d}{dx} \alpha e^x = \alpha e^x
$$

$$
3. \space \frac{d}{dx} e^{u(x)} = e^{u(x)}u'(x)
$$

<br />

One final property for non-base $e$, for any positive base $b$:

$$
\frac{d}{dx} b^x = (\ln{b})(b^x)
$$

<br />

#### Example 1:

Find $f'(x)$ if $f(x) = e^{-3x}$

-   We can use the rule: $\frac{d}{dx} e^{u(x)} = e^{u(x)}u'(x)$

-   We know $u(x)$ in this case: $u(x) = -3x$

-   Using the linear rule, $u'(x) = -3$

-   Thus, applying the format $\frac{d}{dx} e^{u(x)} = e^{u(x)}u'(x)$, we know: $f'(x) = e^{-3x}*-3$

-   Simplified: $f'(x) = -3e^{-3x}$

<br />

#### Example 2:

Find $f'(x)$ if $f(x) = e^{x^2}$

-   We can use the rule: $\frac{d}{dx} e^{u(x)} = e^{u(x)}u'(x)$

-   We know that $u(x)$ in this case: $u(x) = x^2$

-   Using power rule, $u'(x) = 2x$

-   Thus, applying the format $\frac{d}{dx} e^{u(x)} = e^{u(x)}u'(x)$, we know: $f'(x) = e^{x^2}*2x$

-   Simplified: $f'(x) = 2xe^{x^2}$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Derivatives of Logarithms {#logarithms}

Here are the main properties of the derivatives of natural logs:

$$
1. \space \frac{d}{dx} \ln{x} = \frac{1}{x}
$$

$$
2. \space \frac{d}{dx} \ln{x^k} = \frac{d}{dx} k \ln{x} = \frac{k}{x} 
$$

$$
3. \space \frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}
$$

<br />

#### Example 1:

Find $f'(x)$ if $f(x) = \ln(x^2+9)$

-   We can use the rule: $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$

-   We know that $u(x)$ in this case: $u(x) = x^2+9$

-   Using power rule, $u'(x) = 2x$

-   Thus, applying the format $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$, we know: $f'(x) = \frac{2x}{x^2+9}$

<br />

#### Example 2:

Find $f'(x)$ if $f(x) = \ln{(\ln{x})}$

-   We can use the rule: $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$

-   We know that $u(x)$ in this case: $u(x) = \ln x$

-   Using the rule $\frac{d}{dx} \ln{x} = \frac{1}{x}$, we know that $u'(x) = \frac{1}{x}$

-   Thus, applying the format $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$, we know: $f'(x) = \frac{1}{x} * \frac{1}{\ln x}$

-   Simplified: $f'(x) = \frac{1}{x \ln x}$

<br />

#### Example 3:

Find $f'(x)$ if $f(x) = \ln e^x$

-   We have two ways of solving this question:

-   We can use the rule: $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$

    -   We know that $u(x)$ in this case: $u(x) = e^x$

    -   Using the rule $\frac{d}{dx} e^x = e^x$, we know $u'(x) = e^x$

    -   Thus, applying the format $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$, we know: $f'(x) = \frac{e^x}{e^x}$

    -   Simplifying: $f'(x) = 1$

-   Or, we can remember the definition of logarithms: $y = log_a (x) \leftarrow \rightarrow a^y = x$

    -   Our equation is $y = \log_e e^x$, which means $a = e$ and $x = e^x$, so it would be the same as $e^y = e^x$

    -   Thus, $y=x$.

    -   Then, we take the derivative: $\frac{dy}{dx} = 1$

    -   Thus, $f'(x) = 1$

-   We get the same answer $f'(x) = 1$ for both.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)
