---
title: "Partial Derivatives"
output: html_document
subtitle: "Lesson 2.5, Maths for Political Science"
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
  line-height: 150%;
  }
  .main-container {
  max-width: 800px !important;
  margin: auto;
  }
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Course Homepage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

1.  [Partial Derivatives](#partial)
2.  [Application of Partial Derivatives: Regression](#regression)
3.  [Application of Partial Derivatives: Economics](#economics)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Partial Derivatives {#partial}

Suppose that we have a function $f$ with inputs of two or more variables.

-   We want to determine the rate of change relative to one of the variables.

-   To do so, we would employ a partial derivative - since we are only interested in the rate of change relative to one of the variables.

<br />

A partial derivative of the variable $x_i$ is defined mathematically as:

$$
\frac{\partial}{\partial x_i} f(x_1,...,x_i,...,x_n) = \lim\limits_{h \rightarrow 0} \frac{f(x_1,...,x_i + h,...,x_n) - f(x_1,...,x_i,...,x_n)}{h}
$$

<br />

-   Where $x_1, ..., x_n$ are all different input variables of function $f$

-   Where we are interested in the rate of change relative to variable $x_i$ specifically, so we are finding the derivative in respect to $x_i$ specifically: $\frac{d}{dx_i}$

-   Thus, we treat $x_i,...,x_n$ that are not $x_i$ simply as constants (we don't find the derivative in respect to those, treat them like you would treat a constant $c$, like $5$).

Note: we use $\frac{\partial}{\partial x}$ instead of $\frac{d}{dx}$ to indicate partial derivatives (Cyrillic $\partial$ instead of Latin $d$)

<br />

For example, let us take the following function of input variables $x, z$:

$$
f(x,z) = 5x^2z^3 + 2x+ 3z +5
$$

<br />

We can take the derivative of either $x$ or $z$, holding the other variable constant.

<br />

#### Example 1:

Given the function $f(x,z) = 5x^2z^3 + 2x+ 3z +5$, find the derivative in respect to $x$

*We can use the sum rule and power rule to take the derivative of this. Treat all* $z$ *as just some constant (this includes* $z^k$*, which in this scenario, is just a constant to the power of something, also a constant).*

$$
f(x,z) = 5x^2z^3 + 2x+ 3z +5
$$

$$
\frac{\partial}{\partial x} f(x, z) = \frac{\partial}{\partial x}[5x^2z^3] + \frac{\partial}{\partial x} [2x] + \frac{\partial}{\partial x} [3z] + \frac{\partial}{\partial x}[5]
$$

$$
\frac{\partial}{\partial x} f(x, z) = 10z^3 x + 2 +0 + 0
$$

$$
\frac{\partial}{\partial x} f(x,z) = 10z^3 x + 2
$$

<br />

#### Example 2:

Given the function $f(x,z) = 5x^2z^3 + 2x + 3z + 5$, find the derivative in respect to $z$

*We can use the sum rule and power rule to take the derivative of this. Treat all* $x$ *as just some constant (this includes* $x^k$*, which in this scenario, is just a constant to the power of something, also a constant).*

$$
f(x,z) = 5x^2z^3 + 2x + 3z + 5
$$

$$
\frac{\partial}{\partial z} f(x, z) = \frac{\partial}{\partial z}[5x^2z^3] + \frac{\partial}{\partial z} [2x] + \frac{\partial}{\partial z} [3z] + \frac{\partial}{\partial z}[5]
$$

$$
\frac{\partial}{\partial z}f(x,z) = 15x^2z^2 + 0 + 3 + 0
$$

$$
\frac{\partial}{\partial z}f(x,z) = 15x^2z^ + 3
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Application of Partial Derivatives: Regression {#regression}

#### Multivariate OLS Regression

One key use of partial derivatives is the multivariate linear regression model, which will be covered in the course [Regression Analysis](https://politicalscience.github.io/#regression) in more detail. However, let us briefly introduce the use of partial derivatives in this case:

In the equation below, we are predicting the value of $y$ from different independent variables $x_1, x_2, ..., x_p$. The coefficient constants $\beta_0, \beta_1, \beta_2,..., \beta_p$ are not really important now - just know they are values that help us get our prediction of $y$. The multivariate model is as follows:

$$
\hat{y}=\hat{\beta}_0 + \hat{\beta}_1 x_1 + \hat{\beta}_2 x_2 + ... + \hat{\beta}_p x_p
$$

<br />

Lets say we want to interpret and isolate how one specific $x$ variable affects our prediction of $y$. For simplicity, let us say we are interested in how changes in one of our independent variable $x_1$ affects our $y$.

To find the effect of one independent variable $x_1$ on $y$ in this multivariate model, we can simply take the partial derivative in respect to $x_1$, and treat $x_2, x_3,...,x_p$ as constants:

$$
\frac{\partial \hat{y}}{\partial x_1} = \frac{\partial \hat{y}}{\partial x_1}[\hat{\beta}_0] + \frac{\partial \hat{y}}{\partial x_1}[\hat{\beta}_1 x_1] + \frac{\partial \hat{y}}{\partial x_1}[\hat{\beta}_2 x_2] + ... + \frac{\partial \hat{y}}{\partial x_1}[\hat{\beta}_p x_p]
$$

$$
\text{since } x_2,...x_p \text{ are treated as constants}
$$

$$
\frac{\partial \hat{y}}{\partial x_1} = 0 + \hat{\beta}_1 + 0 + ... + 0
$$

$$
\frac{\partial \hat{y}}{\partial x_1} = \hat{\beta}_1
$$

Thus, the rate of change of $y$ in respect to one independent variable $x_1$ in a multivariate model is the coefficient $\hat{\beta}_1$

<br />

#### Moderating Effect Regression

We can also apply this to the moderating/interaction effect regressions. I won't get into too much detail on how those work, please consult the [Regression Analysis](https://politicalscience.github.io/#regression) course for more details. The moderating/interaction effects take the following form:

$$
\hat{y}=\hat{\beta}_0 + \hat{\beta}_1 x_1 + \hat{\beta}_2 x_2 + \hat{\beta}_3 x_1 x_2
$$

<br />

Again, we can find the partial derivative in respect to $x_1$ to see how that specific independent variable $x_1$ affects $y$

$$
\frac{\partial \hat{y}}{\partial x_1} = \frac{\partial \hat{y}}{\partial x_1}[\hat{\beta}_0] + \frac{\partial \hat{y}}{\partial x_1}[\hat{\beta}_1 x_1] + \frac{\partial \hat{y}}{\partial x_1}[\hat{\beta}_2 x_2] + \frac{\partial \hat{y}}{\partial x_1}[\hat{\beta}_3 x_1 x_2]
$$

$$
\text{since } x_2 \text{ is treated as a constant}
$$

$$
\frac{\partial \hat{y}}{\partial x_1} = 0 + \hat{\beta}_1 + 0 + \hat{\beta}_3 x_2
$$

$$
\frac{\partial \hat{y}}{\partial x_1} = \hat{\beta}_1 + \hat{\beta}_3 x_2
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Application of Partial Derivatives: Economics {#economics}

Finally, let us look at another application of Partial Derivatives - Marginal Rate of Technical Subsitution (MRTS) in economics.

Marginal Rate of Technical Subsitution (MRTS) is an economic concept, describing the ability of a producer to subsitute one input for another, while mantaining the same quantity produced.

For example, producers often debate between two production inputs: how much labour they should hire, and how many machines they should use.

-   Thus, it is important to know what different combinations of labour and machines produce the same amount of output (ex. ).

This is illustrated by a Cobbs-Douglas function, which is a production function $Q$

-   Output of function $Q$ is quantity produced

-   inputs of function $Q$ are inputs for production $x$ and $y$ (in economics, often labour and capital)

<br />

From the Cobbs-Douglas function, we can get the marginal product of X and Y.

Marginal product of X, is the change in total output resulting from the next unit of X used.

-   Basically, what is the benefit to production, when you introduce a unit of X.

Marginal Product of X, is the partial derivative of Cobbs-Douglas function $Q$, only in respect to $x$. Vice versa for Y

-   In essense, $MP_x = \frac{\partial}{\partial x}Q(x,y)$, and $MP_y = \frac{\partial}{\partial y}Q(x,y)$

-   This makes sense - $Q$ is a function of production, so the derivative is the rate of change of production. We want to know how much an additional $x$ or $y$ changes production, which is what the derivative is telling us.

<br />

If we hold the output of $Q$ constant, then we can see how we can substitute labour and capital, while achieving the same amount of production.

-   $Q$ being constant essentially means, the same quantity of production.
-   Knowing the different combinations of Labour and Capital that produce the same quantity output, allows you to know your "options" of meeting a certain production target, allowing you to chose which "option" is the most cost efficient.
-   For example, pretend that maybe 5 workers and 3 machines, and 6 machines and 2 workers, produce the same amount of output of $Q$.

<br />

Marginal Rate of Technical Substitution (MRTS) tells us, at what rate can we exchange $x$ to $y$, while holding $Q$ fixed.

-   Essentially, the Marginal Rate of Technical Subsitution is the rate at which $x$ must decrease, and $y$ must increase, to retain the same level of production.

Marginal Rate of Technical Subsitution is the ratio of the marginal products:

$$
MRTS(x, y) = \frac{MP_x}{MP_y}
$$

<br />

Now, let us apply this to an example to better understand this. Take this production function $Q$ for quantity produced, which has inputs $x$ and $y$:

$$
Q(x,y)=2x^{0.3}y^{0.7}
$$

<br />

Now, let us find the Marginal Product of X, which is the derivative of $Q$ in respect to $x$. We use the power rule, keeping $y$ as a constant.

$$
MP_x = \frac{\partial}{\partial x}[2x^{0.3}y^{0.7}] 
$$

$$
MP_x = 0.6y^{0.7}x^{-0.7}
$$

$$
MP_x = \frac{0.6y^{0.7}}{x^{0.7}}
$$

<br />

Now, let us find the Marginal Product of Y, which is the derivative of $Q$ in respect to $y$. We use the power rule, keeping $x$ as a constant.

$$
MP_y = \frac{\partial}{\partial y} [2x^{0.3}y^{0.7}]
$$

$$
MP_y = 1.4x^{0.3}y^{-0.3}
$$

$$
MP_y = \frac{1.4x^{0.3}}{y^{0.3}}
$$

<br />

Now, let us find the marginal product of technical substitution (MRTS)

$$
MRTS(x,y) = \frac{MP_x}{MP_y}
$$

$$
MRTS(x,y) = \frac{0.6y^{0.7}}{x^{0.7}} รท \frac{1.4x^{0.3}}{y^{0.3}}
$$

$$
MRTS(x,y) = \frac{0.6y^{0.7}}{x^{0.7}} * \frac{y^{0.3}}{1.4x^{0.3}}
$$

$$
MRTS(x,y) = \frac{0.6*y^{0.7}*y^{0.3}}{x^{0.7}*x^{0.3}*1.4}
$$

$$
MRTS(x,y) = \frac{0.6y}{1.4x} = \frac{0.429y}{x}
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)
