---
title: "Integrating by Subsitution"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 2.7, Maths for Political Science"
---

[Course Hompage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

1.  [Integration by Subsitution](#substitution)
2.  [Example of U-Subsitution](#example)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)

# Integration by Subsitution {#substitution}

Sometimes, an integral doesn't seem to be solvable based on the rules provided in the lesson [Indefinite Integrals](https://politicalscience.github.io/math/2-5.html). In that case, Integration by Subsitution is a trick we can try (although it is not always possible).

<br />

The idea of integral by substitution is related to chain rule.

Let us say we are interested in finding the indefinite integral of $g(x)$, where $g(x)$ takes the following form:

$$
g(x) = f[u(x)] u'(x)
$$

<br />

If we remember the [chain rule](https://politicalscience.github.io/math/2-2.html) from before:

$$
\frac{d}{dx}f[u(x)] = f[u(x)] u'(x)
$$

<br />

We can reverse the chain rule, and conclude that:

$$
\int f[u(x)]u'(x) = F[u(x)]+c
$$

<br />

#### Solving Integral by Subsitution

Thus, the procedure to solving an indefinite integral by substitution is:

1.  Identify some part of $g(x)$ that we can subsitute for $u$
2.  Once we have identified $u$, take the equation $u$ is equal to its substitute, solve for $x$, then take the derivative in respect to $u$. That is our $du$, we need to multiply it into our integral.
3.  Rewrite our function in terms of $u$ and $du$ (Do not forget $du$ especially when it is $≠1$!)
4.  Solve the indefinite integral with $u$ and $du$ inside
5.  Subsitute the $x$ back in for $u$ to get the final integral.

<br />

This is one of the most difficult topics in calculus, so we will provide several long-form examples below.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)

# Example of U-Subsitution {#example}

Let us solve the following integral:

$$
\int x^2 \sqrt{x+1} \space dx
$$

<br />

Using our basic rules, we don't really know how to solve this integral. There are two approaches to solving this problem, both involving substitution.

<br />

#### Approach 1:

More specifically, we do not know how to deal with the $\sqrt{x+1}$ section. If everything in the equation was just in terms of $x^k$, things would be much easier.

To address this, let us substitute $x+1$ with $u$, which will take out the $+1$ part that prevents us from having everything in terms of something to the power of $k$. We do as follows:

$$
u = x+1
$$

<br />

With the above equation, we also know by solving for $x$, that:

$$
x = u - 1
$$

On the above equation, we thus know that the $du$ (derivative in respect to $u$) is $1$.

<br />

Now we have our substitutions, let us put it into the original integral:

$$
\int x^2 \sqrt{x+1} dx = \int (u-1)^2 * \sqrt{u} \space du
$$

From expanding the $(u-1)^2$ and rewriting $\sqrt{x}$, we get:

$$
= \int (u^2-2u+1) * u^{1/2} \space du
$$

Now, let us multiply the two sections together:

$$
= \int u^2*u^{1/2} - 2u*u^{1/2} + 1*u^{1/2} \space du 
$$

$$
= \int u^{5/2} - 2u^{3/2} + u^{1/2} \space du
$$

<br />

Now with the above form, we have polynomials. We know how to take the integral of these:

$$
= \int u^{5/2} - 2u^{3/2} + u^{1/2} \space du
$$

Using the rule $\int [f(x) + g(x)]dx = \int f(x)dx + \int g(x)dx$, we know:

$$
= \int u^{5/2}du + \int 2u^{3/2}du + \int u^{1/2} du
$$

Using the rule $\int x^n dx = \frac{1}{n+1}x^{n+1}+c$, we know:

$$
= \frac{1}{5/2 + 1} u^{5/2 + 1} + c + 2 * \frac{1}{3/2+1} u^{3/2+1} + c + \frac{1}{1/2+1} u^{1/2+1} + c
$$

$$
= \frac{2}{7}u^{7/2} + \frac{4}{5}u^{5/2} + \frac{2}{3}u^{3/2} + c
$$

We can factor out $2u^{3/2}$ to get:

$$
=2u^{3/2} \left[ \frac{1}{7}u^2 + \frac{2}{5}u + \frac{1}{3} \right] + c
$$

<br />

Now, we finally substitute $u=x+1$ back to get the final integrated function:

$$
\int x^2 \sqrt{x+1} dx = 2(x+1)^{3/2} \left[ \frac{1}{7} (x+1)^2 - \frac{2}{5} (x+1) + \frac{1}{3} \right] + c
$$ <br />

#### Approach 2:

Let us remind ourselves of the original problem:

$$
\int x^2 \sqrt{x+1} \space dx
$$

More specifically, we do not know how to deal with the $\sqrt{x+1}$ section. If everything in the equation was just in terms of $x^k$, things would be much easier.

Instead of substituting $u=x+1$ like the first approach, instead, let us substitute the entire difficult section as follows:

$$
u = \sqrt{x+1}
$$

<br />

Now, let us change our integration problem into terms of $u$.

-   We know that since $u = \sqrt{x+1}, u^2$ would be $u^2 = x+1$, so $x^2$ should be $(u^2 - 1)^2$.

-   Since $u^2=x+1$, thus, $x=u^2-1$, and thus, the $du$ (derivative in respect to $u$) is $2u$

$$
\int x^2 \sqrt{x+1} \space dx = \int (u^2-1)^2*u*2udu
$$

<br />

Now, let us expand the $(u^2-1)^2$ out and multiply the $u$ terms together:

$$
=\int (u^4-2u^2+1)*2u^2du
$$

Multiply out the terms again:

$$
= \int 2u^6 - 4u^4 + 2u^2 du
$$

<br />

Using the rule $\int [f(x) + g(x)]dx = \int f(x)dx + \int g(x)dx$, we know:

$$
= \int 2u^6 du - \int 4u^4du + \int 2u^2 du
$$

Using the rule $\int x^n dx = \frac{1}{n+1}x^{n+1}+c$, we know:

$$
= 2*\frac{1}{6+1}u^{6+1} + c - 4*\frac{1}{4+1}u^{4+1} + c + 2*\frac{1}{2+1}u^{2+1} + c
$$

$$
= \frac{2}{7} u^7 - \frac{4}{5} u^5 + \frac{2}{3} u^3 + c
$$

We can factor out $2u^3$ to get:

$$
=2u^3 \left[ \frac{1}{7} u^4 - \frac{2}{5} u^2 + \frac{1}{3} \right] + c
$$

<br />

Now, we finally substitute $u=\sqrt{x+1}$ back to get the final integrated function:

$$
= 2(\sqrt{x+1})^3 \left[ \frac{1}{7} (\sqrt{x+1})^4 - \frac{2}{5} (\sqrt{x+1})^2 + \frac{1}{3} \right] + c
$$

$$
= 2(x+1)^{3/2} \left[ \frac{1}{7} (x+1)^2 - \frac{2}{5}(x+1) + \frac{1}{3} \right] + c
$$

Which is the same answer we got the first time!

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)