---
title: "Integrating by Parts"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 2.8, Maths for Political Science"
---

[Course Hompage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

1.  [Integration by Parts](#parts)
2.  [Examples](#examples)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)

# Integration by Parts {#parts}

In the previous lessons, we have talked about the [rules of integration](https://politicalscience.github.io/math/2-5.html), and [integration by substitution](https://politicalscience.github.io/math/2-7.html). This lesson will introduce a third method to finding integrals: integration by parts.

<br />

Like how integration by substitution was the "opposite" of the chain rule, integration by parts is the "opposite" of the product rule. The product rule helps us find the derivative of multiplied functions, and states:

$$
[f(x)g(x)]' = f'(x)g(x) + f(x)g'(x) 
$$

<br />

We can "reverse" the rule, to get the following rule:

$$
\int u(x) v'(x)dx = u(x) v(x) - \int v(x) u'(x) dx
$$

<br />

How does this help us find integrals?

-   If we can find expressions for $u(x)$ and $v'(x)$, then we can substitute these into the above equation.

-   Once substituted into the above form, the integral is easier to derive.

<br />

This is a complicated topic, so below are some detailed examples.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)

# Examples {#examples}

#### Example 1:

Our goal is to evaluate the following:

$$
\int \frac{ln(x)}{x^2} dx
$$

<br />

First, let us write the equation in the integration by parts form of $\int u(x) v'(x)dx$:

$$
u(x) = ln(x), \space v'(x) = \frac{1}{x^2}
$$

<br />

With this, we can find $u'(x)$ and $v(x)$ as follows:

$$
u'(x) = \frac{d}{dx}[ln(x)] = \frac{1}{x}
$$

<br />

$$
v(x) = \int \frac{1}{x^2} dx
$$

$$
= \int x^{-2} dx
$$

$$
= \frac{1}{-2 + 1} x^{-2 + 1} + c
$$

$$
= \frac{-1}{x} + c
$$

<br />

With us now knowing $u(x), u'(x), v(x), v'(x)$, we can fit everything into the integration by parts formula:

$$
\int u(x) v'(x)dx = u(x) v(x) - \int v(x) u'(x) dx
$$

$$
\int ln(x) * \frac{1}{x^2} dx = u(x) v(x) - \int v(x) u'(x) dx
$$

$$
= ln(x) * \left( \frac{-1}{x} + c \right) - \int \left[ \frac{-1}{x} * \frac{1}{x} \right] dx
$$

$$
= \frac{-ln(x)}{x} + c - \int \frac{-1}{x^2} dx
$$

$$
= \frac{-ln(x)}{x} + c - \int -x^{-2} dx
$$

$$
= \frac{-ln(x)}{x} + c - \int \frac{1}{-2+1} x^{-2+1} dx
$$

$$
= \frac{-ln(x)}{x} + c - (-x^{-1} + c)$$

$$
= \frac{-ln(x)}{x} + c + \frac{1}{x} - c
$$

$$
= \frac{-ln(x) + 1}{x} + c
$$

<br />

#### Example 2:

Our goal is to evaluate the following:

$$
\int e^x x dx
$$

<br />

First, let us write the equation in the integration by parts form of $\int u(x) v'(x)dx$:

$$
u(x) = e^x, \space v'(x) = x
$$

<br />

With this, we can find $u'(x)$ and $v(x)$ as follows:

$$
u'(x) = \frac{d}{dx} [e^x] = e^x
$$

$$
v(x) = \int xdx = \frac{1}{1+1}x^{1+1} = \frac{x^2}{2}
$$

<br />

With us now knowing $u(x), u'(x), v(x), v'(x)$, we can fit everything into the integration by parts formula:

$$
\int u(x) v'(x)dx = u(x) v(x) - \int v(x) u'(x) dx
$$

$$
\int e^x * x dx = u(x) v(x) - \int v(x) u'(x) dx
$$

$$
= e^x * \frac{x^2}{2} - \int \left[ \frac{x^2}{2} * e^x\right]dx
$$

But, we don't know how to take the integral of that second part - without more integration by parts...

-   We could slug through the second part, but the same issue will appear

-   However, there is a way to fix the problem:

<br />

A solution to this is to simply reverse the assignment of $u(x)$ and $v'(x)$.

-   Instead of $u(x) = e^x$ and $v'(x) = x$,

-   Let us make $u(x) = x$, and $v'(x) = e^x$

<br />

With this, we can find $u'(x)$ and $v(x)$ as follows:

$$
u'(x) = \frac{d}{dx} [x] = 1
$$

$$
v(x) = \int e^xdx = e^x + c
$$

<br />

With us now knowing $u(x), u'(x), v(x), v'(x)$, we can fit everything into the integration by parts formula:

$$
\int u(x) v'(x)dx = u(x) v(x) - \int v(x) u'(x) dx
$$

$$
\int e^x * x dx = u(x) v(x) - \int v(x) u'(x) dx
$$

$$
= x*(e^x+c) - \int [e^x * 1]dx
$$

$$
= xe^x + c - \int e^xdx
$$

$$
= xe^x - e^x + c
$$

We can factor out the common term $e^x$ to get:

$$
= e^x(x-1) + c
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)