---
title: "Matrix Algebra"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 4.4, Maths for Political Science"
---

[Course Hompage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

1.  [Matrix Transpose](#transpose)
2.  [Matrix Addition and Subtraction](#addition)
3.  [Matrix Plain Multiplication](#multiplication)
4.  Kronecker Product

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)

# Matrix Transpose {#transpose}

#### Intuition

The transpose of the matrix, is the matrix flipped around its "axis".

For example, take the matrix below:

$$
B_{3 \times 3} = 
\begin{bmatrix}
2 & 3 & 1 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

The transpose of this matrix, $B^T$, would be as follows:

$$
B_{3 \times 3}^T = 
\begin{bmatrix}
2 & 4 & 7 \\
3 & 5 & 8 \\
1 & 6 & 9
\end{bmatrix}
$$

We just switched the columns into rows. The 1st column in $B$ became the 1st row in $B^T$. Note how the numbers on the main top-left bottom-right diagonal remain the same.

<br />

A **symmetric matrix** is a matrix, where the transpose is the exact same as the original matrix: $A^T = A$

<br />

#### Transposes of Non-Square Matrices

Transpositions not only exist for square matrices, but for any sized matrix, and even vectors.

For example, take the column vector $\overrightarrow{a}$ below:

$$
\overrightarrow{a} = 
\begin{bmatrix}
1 \\
3 \\
5
\end{bmatrix}
$$

The transpose of $\overrightarrow{a}$ is where we switch the columns (in this case, only 1 column) into the rows, getting the transpose $\overrightarrow{a}^T$

$$
\overrightarrow{a}^T = 
\begin{bmatrix}
1 & 3& 5
\end{bmatrix}
$$

<br />

For a non-square matrix, take the following matrix $C$ below:

$$
C_{2 \times 3} = 
\begin{bmatrix}
1 & 3 & 5 \\
2 & 4 & 6
\end{bmatrix}
$$

The transpose $C^T$ is just taking the columns of $C$ and making them rows of $C^T$:

$$
C_{3 \times 2}^T = 
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
$$

<br />

This gives us the more general rule that of transposes: For matrix $A$ and its transpose $A^T$, the element of the transpose $a^T_{ij} = a_{ji}$

-   Or in other words, the coordinate of an element has its rows and columns flipped in its transpose.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)

# Matrix Addition and Subtraction {#addition}

Matrix Addition works the same way as [Vector Addition](https://politicalscience.github.io/math/4-2.html#addition):

-   If you have two matrices with the same numbers of rows and columns, you add the respective elements together (or subtract them, which is just addition with negative numbers).

<br />

For example, take the matrices $A$ and $B$ below:

$$
A_{2 \times 2} = 
\begin{bmatrix}
2 & 3 \\
1 & 4 \\
\end{bmatrix},
B_{2 \times 2} = 
\begin{bmatrix}
5 & 1 \\
6 & 0 \\
\end{bmatrix},
$$

We just add each respective element together that are in the same positions of each matrix as follows:

$$
A_{2 \times 2} + B_{2 \times 2} = 
\begin{bmatrix}
2+5 & 3+1 \\
1+6 & 4+0 \\
\end{bmatrix} =
\begin{bmatrix}
7 & 4 \\
7 & 4 \\
\end{bmatrix}
$$

<br />

Subtraction is the same. Let us continue to use $A$ and $B$ from above for this example:

$$
A_{2 \times 2} - B_{2 \times 2} = 
\begin{bmatrix}
2-5 & 3-1 \\
1-6 & 4-0 \\
\end{bmatrix} =
\begin{bmatrix}
-3 & 2 \\
-5 & 4 \\
\end{bmatrix}
$$

<br />

Remember, the 2 matrices much have the same amount of rows and columns for addition and subtraction to work.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)

# Matrix Scalar Multiplication {#scalar}

Matrix Scalar Multiplication works the same way as [Vector Scalar Multiplication](https://politicalscience.github.io/math/4-2.html#scalar):

-   You just multiply each element of the matrix by the scalar to get the resulting matrix.

-   Remember, a scalar is a single component/element, like a single number.

<br />

For example, let us take the following matrix $A$ and scalar $c$:

$$
A_{2 \times 2} = 
\begin{bmatrix}
3 & 1 \\
5 & 6
\end{bmatrix}, c = 2
$$

To find the product of matrix $A$ and scalar $2$, we multiply every element of matrix $A$ by the scalar as follows:

$$
A_{2 \times 2} \times c = 
\begin{bmatrix}
3 \times 2 & 1 \times 2 \\
5 \times 2 & 6 \times 2 \\
\end{bmatrix} = 
\begin{bmatrix}
6 & 2 \\
10 & 12
\end{bmatrix}
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)

# Matrix Plain Multiplication {#multiplication}

There are many forms of Matrix Multiplication, but the most common is Plain Multiplication.

<br />

To multiply matrices $A$ and $B$ together to get the resulting matrix $C$, the following is the case:

-   Note: $i$ refers to which row an element is in, and $j$ refers to which column an element is in.

-   Thus, element $c_{ij}$ refers to the element within the matrix $C$ that is in the $i$th row and $j$th column.

$$
c_{ij} = \sum\limits_k a_{ik} \times b_{kj}
$$

Where $k$ for a tells us the column number of the element from matrix $a$, and the row number of matrix $b$

-   We stop summing until we run out of rows/columns.

-   Note: for Plain Multiplication to be possible, the number of columns in matrix $A$ must equal the number of rows in matrix $B$ (or else the sum wouldn't work).

<br />

If we have a $3 \times 3$ matrices, then the element $c_{1,1}$ (the element of the matrix $C$ in the 1st row and 1st column) is the following:

$$
c_{1,1} = a_{1,1} b_{1,1} + a_{1,2} b_{2, 1} + a_{1, 3} b_{1,3}
$$

<br />

Or in more intuitive terms, for the element of the result matrix $C$ in the 1st column and 1st row:

-   We multiply the 1st **row** of matrix $A$ with the 1st **column** of matrix $B$

    -   What does this mean? We take the 1st element of the 1st row of matrix $A$, then multiply that with the 1st element of the 1st column of matrix $B$. Then multiply the 2nd element of the two. Do this for all the elements of the 1st row of Matrix $A$ and the 1st column of Matrix $B$ (there should be the same amount of elements).

    -   Then, sum up all the products of the different elements.

    -   This sum is what we put in the 1st column and 1st row of the result matrix $C$.

-   We do this for every other element of the result matrix $C$ - for example, $C_{2,1}$ is where we multiply the 2nd row of matrix $A$ with the 1st column of matrix $B$.

An [example](#example) is done below - but for the meantime, we need to introduce a few properties of plain multiplication.

<br />

#### Properties

There are a number of properties that will be true about $A \times B$, and the resulting matrix $C$:

-   The number of rows in matrix $C$ will be equivalent to the number of rows in matrix $A$

-   The number of columns in matrix $C$ will be equivalent to the number of columns in matrix $B$

-   Thus, the dimensions of $C$ will be the number of rows in $A$ and the number of columns in $B$

-   IMPORTANT: the number of columns of matrix $A$ must be equal to the number of rows in matrix $B$ for multiplication to be possible.

    -   Why? well then the summation wouldn't work, as the number of elements $k$ wouldn't be the same in the summation formula.

-   The commutative property does not generally apply to matrix plain multiplication - i.e. $A \times B ≠ B \times A$

-   However, commutative property can exist with inverse matrices/identity matrices: $A \times I = I \times A$ and $A \times A^{-1} = A^{-1} \times A$

<br />

#### Example {#example}

Let us take the two matrices below:

$$
A_{2 \times 2} = 
\begin{bmatrix}
2 & 1 \\
3 & 5
\end{bmatrix},
B_{2 \times 2} = 
\begin{bmatrix}
6 & 1 \\
2 & 3
\end{bmatrix}
$$

Now let us solve the plain product of matrices $A$ and $B$, where the result is matrix $C$

<br />

Let us start with the element $c_{1,1}$ of the result matrix $C$ (or in other words, the element of the result matrix $C$ in the 1st row and 1st column).

-   To do this, we need to find the product of the 1st row of matrix $A$, and the 1st column of matrix $B$

The first row of matrix $A$ consists of the values $[2 \space 1]$ and the first column of matrix $B$ consists of the values $[6 \space 2]$. Let us find the result using the formula presented earlier: $c_{ij} = \sum\limits_k a_{ik} \times b_{kj}$

$$
c_{1,1} = a_{1,1}b_{1,1} + a_{1,2}b_{2,1}
$$

$$
c_{1,1} = 2 \times 6 + 1 \times 2
$$

$$
c_{1,1} = 12 + 2 = 14
$$

<br />

Now, let us find $c_{1,2}$ (the element of the result matrix $C$ in the 1st row and 2nd column) in the same manner as above:

The first row of matrix $A$ consists of the values $[2 \space 1]$, and the 2nd column of matrix $B$ consists of the values $[1 \space 3]$

$$
c_{1,2} = a_{1,1}b_{1,2} + a_{1,2} b_{2,2}
$$

$$
c_{1,2} = 2 \times 1 + 1 \times 3
$$

$$
c_{1,3} = 2 + 3 = 5
$$

<br />

Now, let us find $c_{2,1}$ (the element of the result matrix $C$ in the 2nd row and 1st column) in the same manner as above:

The 2nd row of matrix $A$ consists of the values $[3 \space 5]$ and the first column of matrix $B$ consists of the values $[6 \space 2]$.

$$
c_{2,1} = a_{2,1}b_{1,1} + a_{2,2}b_{2,1}
$$

$$
c_{2,1} = 3 \times 6 + 5 \times 2
$$

$$
c_{2,1} = 18 + 10 = 28
$$

<br />

Finally, let us find $c_{2,2}$ (the element of the result matrix $C$ in the 2nd row and 2nd column) in the same manner as above:

The 2nd row of matrix $A$ consists of the values $[3 \space 5]$ and the 2nd column of matrix $B$ consists of the values $[1 \space 3]$

$$
c_{2,2} = a_{2,1} b_{1,2} + a_{2,2}b_{2,2}
$$

$$
c_{2,2} = 3 \times 1 + 5 \times 3
$$

$$
c_{2,2} = 3 + 15 = 18
$$

<br />

Now, we have found $c_{1,1}, c_{1,2}, c_{2,1}, c_{2,2}$, so we can create the resulting matrix $C$, which is the product of matrices $A$ and $B$

$$
C_{2 \times 2} = 
\begin{bmatrix}
c_{1,1} & c_{1,2} \\
c_{2,1} & c_{2,2}
\end{bmatrix} = 
\begin{bmatrix}
14 & 5 \\
28 & 18
\end{bmatrix}
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)

# Kronecker Product {#kronecker}

Kronecker Product is another form of matrix multiplication, but less common than plain multiplication.

-   Instead of being denoted by the multiplication sign $\times$, it is denoted with the symbol $\otimes$

<br />

Kronecker Product is defined as follows. Take the example that you have matrix $A$ and matrix $B$ as follows:

$$
A_{2 \times 2} = 
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix},
B_{2 \times 2} = 
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2}
\end{bmatrix},
$$

<br />

Then, the Kronecker Product $A \otimes B$ is as follows:

$$
A \otimes B =
\begin{bmatrix}
C & D \\
E & F
\end{bmatrix}
$$

Where:

$$
C = \begin{bmatrix}
a_{1,1}b_{1,1} & a_{1,1}b_{1,2} \\
a_{1,1}b_{2,1} & a_{1,1}b_{2,2}
\end{bmatrix},
D = \begin{bmatrix}
a_{1,2}b_{1,1} & a_{1,2}b_{1,2} \\
a_{1,2}b_{2,1} & a_{1,2}b_{2,2}
\end{bmatrix},
$$

$$
E = \begin{bmatrix}
a_{2,1}b_{1,1} & a_{2,1}b_{1,2} \\
a_{2,1}b_{2,1} & a_{2,1}b_{2,2}
\end{bmatrix},
F = \begin{bmatrix}
a_{2,2}b_{1,1} & a_{2,2}b_{1,2} \\
a_{2,2}b_{2,1} & a_{2,2}b_{2,2}
\end{bmatrix}
$$

<br />

Or in a more simplified way, we can write $C, D, E, F$ as the results of scalar products:

$$
C = a_{1,1} * B, \space D = a_{1,2} * B,
$$

$$
E = a_{2,1} * B, \space F = a_{2,2} * B,
$$

<br />

Thus, we can redefine the Kronecker Product $A \otimes B$ is as follows:

$$
A \otimes B =
\begin{bmatrix}
a_{1,1} \times B & a_{1,2} \times B \\
a_{2,1} \times B &  a_{2,2} \times B
\end{bmatrix}
$$

<br />

The resulting matrix of a Kronecker Product will have the following dimensions:

$$
A_{n \times m} \otimes B_{p \times q} = C_{np \times mq}
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Hompage](https://politicalscience.github.io/math)