---
title: "Matrix Traces and Determinants"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 4.5, Maths for Political Science"
---

[Course Homepage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

1.  [The Trace of a Matrix](#trace)
2.  [The Determinant of a Matrix](#determinant)
3.  [Butterfly Method](#butterfly)
4.  [Laplace Expansion](#laplace)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# The Trace of a Matrix {#trace}

Before we introduce the Determinant, let us first cover a short topic - the Trace of a matrix.

<br />

The trace of a matrix is the sum of all diagonal elements. Essentially, it is the sum of the value of the element in the 1st row 1st column, 2nd row 2nd column, 3rd row 3rd column, and so on...

Or in more mathematical terms, the trace of a matrix $A$, notated as $Tr(A)$, is defined as the following:

$$
Tr(A) = \sum\limits_i a_{i,i} = a_{1,1} + a_{2,2} + ... + a_{n,n}
$$

<br />

The trace is equal to the sum of the eigen values of a Matrix, but we will discuss that later.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# The Determinant of a Matrix {#determinant}

The determinant tells us if a matrix is singular or not.

-   If the determinant is 0, then the matrix is singular, meaning it does not have an inverse.

-   If the determinant is non-0, then the matrix has an inverse.

<br />

Determinants are indicated with bars (like absolute values). Thus, the determinant of matrix $A$ would be notated as $|A|$

-   While it looks like an absolute value, it is not an absolute value - the determinant can be negative.

Thus, an alternate way of notating a determinant to avoid confusion would be $det(A)$

<br />

The determinant only possible to calculate for square matrices (same number of rows and columns).

<br />

#### Determinant in 2 by 2 Matrix {#2by2}

Let us take a 2 by 2 matrix $A$ as follows:

$$
A_{2 \times 2} = 
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
$$

<br />

Then its determinant $|A|$ is equal to the following:

$$
|A| = a_{1,1} \times a_{2,2} - a_{1,2} \times a_{2,1}
$$

This is applicable to all 2 by 2 matrices.

<br />

For example, take the following matrix $B$:

$$
B_{2 \times 2} = 
\begin{bmatrix}
2 & 3 \\
1 & 4
\end{bmatrix}
$$

Then, its determinant $|B|$, following the formula above, is:

$$
|B| = 2 \times 4 - 3 \times 1 = 8 - 3 = 5
$$

<br />

2 by 2 determinants are relatively straight forward, but as we move towards larger square matrices, things become more complicated, as will be shown by the following 2 sections.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Butterfly Method {#butterfly}

For 2 by 2 matrices, we have a simple formula as shown in the section above.

-   However, things become more complicated as we move to larger matrices.

<br />

The butterfly method is a method to find the determinant of 3 by 3 matrices.

Take the following 3 by 3 matrix $A$:

$$
A_{3 \times 3} = 
\begin{bmatrix}
a_{1,1} & a_{1,2} & a_{1,3} \\
a_{2,1} & a_{2,2} & a_{2,3} \\
a_{3,1} & a_{3,2} & a_{3,3}
\end{bmatrix}
$$

<br />

To get the determinant of this, let us first "copy and paste" the first two columns, creating a duplicate of them to the right of the matrix - getting the following:

$$
\begin{bmatrix}
a_{1,1} & a_{1,2} & a_{1,3} & a_{1,1} & a_{1,2}\\
a_{2,1} & a_{2,2} & a_{2,3} & a_{2,1} & a_{2,2}\\
a_{3,1} & a_{3,2} & a_{3,3} & a_{3,1} & a_{3,2}
\end{bmatrix}
$$

Now, let us draw diagonals of 3 elements from top left to bottom right, starting with the top left $a_{1,1}$. We will get the following 3 diagonals of 3 elements:

-   Diagonal 1: $a_{1,1}, a_{2,2}, a_{3,3}$

-   Diagonal 2: $a_{1,2}, a_{2,3}, a_{3,1}$

-   Diagonal 3: $a_{1,3}, a_{2,1}, a_{3,2}$

<br />

Then, let us draw diagonals of 3 elements from the top right to bottom left, starting with the top right $a_{1,2}$. We will get the following diagonals of 3 elements:

-   Diagonal 4: $a_{1,2}, a_{2,1}, a_{3,3}$

-   Diagonal 5: $a_{1,1}, a_{2,3}, a_{3,2}$

-   Diagonal 6: $a_{1,3}, a_{2,2}, a_{3,1}$

<br />

To find the determinant, we do the following:

-   Find the product of the elements of each diagonal seperately.

-   Then, add together diagonals 1 + 2 + 3, and diagonals 4 + 5 + 6.

-   Then take the sum of diagonals 1 through 3, and subtract the sum of diagonals 4 through 6.

<br />

Or mathematically written out:

$$
|A| = (a_{1,1} \times a_{2,2} \times a_{3,3}) + (a_{1,2} \times a_{2,3} \times a_{3,1}) + (a_{1,3} \times a_{2,1} \times a_{3,2})
$$

$$
- (a_{1,3} \times a_{2,2} \times a_{3,1}) - (a_{1,1} \times a_{2,3} \times a_{3,2}) - (a_{1,2} \times a_{2,1} \times a_{3,3})
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Laplace Expansion {#laplace}

Laplace Expansion is a more general method, that works with almost all sizes of matrices.

-   Basically you choose a row or column of the matrix, and expand out around that row or column to find the determinant of the matrix.

This is a complicated method, so let us take this step by step. Here is a brief overview of the process:

1.  Chose a row, find the submatrix of each element
2.  Find the minor of each element in that row (minor being the determinant of the submatrix)
3.  Then, find the co-factor of each element.
4.  Then find the determinant of the matrix.

<br />

#### Step 1: Submatrices

Let us take the following matrix $A$:

$$
A_{3 \times 3} = 
\begin{bmatrix}
1 & 2 & 1 \\
0 & 1 & 1 \\
5 & 3 & 0
\end{bmatrix}
$$

<br />

Let us expand over the first row of matrix $A$. (you can use any row or any column of any square matrix, and this will work).

-   First, we figure out what are the sub-matrices are of each element in the row.

-   The sub-matrix is the matrix you get, when you remove the row and column corresponding to an individual element.

For example, let us take the element $a_{1,1}$, which is the $1$ in the top left hand corner.

-   That element is in the 1st row and 1st column.

-   So the submatrix is the matrix we would get, when we remove the 1st row and 1st column from matrix $A$.

Thus, the submatrix of element $a_{1,1} = 1$ is:

$$
\begin{bmatrix}
1 & 1 \\
3 & 0
\end{bmatrix}
$$

<br />

#### Step 2: Minor of the Element

What we care about is the determinant of the submatrix.

-   The **minor** of an element in a matrix, is the determinant of that element's submatrix.

So, the **minor** of $a_{1,1} = 1$ is the determinant of the submatrix. Using the equation from [earlier for 2 by 2 determinants](#2by2), we know that the minor is:

$$
|A| = a_{1,1} \times a_{2,2} - a_{1,2} \times a_{2,1}
$$

$$
\text{minor of } a_{1,1} = 1 \times 0 - 1 \times 3 = 0 - 3 = -3
$$

<br />

Let us do this for the other elements of the first row, $a_{1,2} = 2$ and $a_{1,3} = 1$:

The submatrix of $a_{1,2}=2$ (removing the first row and 2nd column), is:

$$
\begin{bmatrix}
0 & 1 \\
5 & 0
\end{bmatrix}, \text{ thus minor is} = 0 \times 0 - 1 \times 5 = -5
$$

The submatrix of $a_{1,3} = 1$ (removing the first row and 3rd column), is:

$$
\begin{bmatrix}
0 & 1 \\
5 & 3
\end{bmatrix}, \text{ thus minor is} = 0 \times 3 - 1 \times 5 = -5
$$

<br />

#### Step 3: Co-Factors of an Element

Now, we convert the minors to co-factors.

-   The co-factor of an element, is the minor of the element, times $(-1)^{i+j}$

-   Basically, depending on the row and column number, the minor of the element is either multiplied by 1 or negative 1.

So, the co-factors of the minors we have found so far:

-   For $a_{1,1} = 1$, $(-1)^{i+j} = (-1)^2=1$, so the co-factor is $-3 \times 1 = -3$

-   For $a_{1,2} = 2$, $(-1)^{i+j} = (-1)^3=-1$, so the co-factor is $-5 \times -1 = 5$

-   For $a_{1,3} = 1$, $(-1)^{i+j} = (-1)^4=1$, so the co-factor is $-5 \times 1 = -5$

<br />

#### Step 4: Finding the Determinant

Now, take each element in the row $a_{i,j}$ and multiply it by its respective co-factor $c_{i,j}$. Then find the sum of the products. For our example:

$$
a_{1,1} c_{1,1} + a_{1,2} c_{1,2} + a_{1,3} c_{1,3}
$$

$$
=(1)(-3) + (2)(5) + (1)(-5)
$$

$$
= -3 + 10 - 5 = 2
$$

<br />

Thus, the determinant of the matrix $A$ is 2.

<br />

#### Extra Notes:

Remember how in the first step, I mentioned you could use any row or column of a square matrix for this method?

-   It always produces the same result.

-   This means that, we can strategically pick a row with more 0's, that will make computations easier. This is because if the element is 0, then when it is multiplied with the co-factor, that product will also be 0.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)