---
title: "Topics in Algebra"
output: html_document
date: "2024-08-29"
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
  line-height: 150%;
}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Course Homepage](https://politicalscience.github.io/#maths)

## Table of Contents {#contents}

-   [Sets](#sets)

-   [Definition of Function](#function)

-   [Zeroes, Limits, and Continuity](#zeroes)

-   [Exponents and Logarithms](#exponents)

-   [Summation and Product Notation](#summation)

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/#maths)

# Sets {#sets}

[Definition of Sets](#001) \| [Set Operators](#003)

### Definition of Sets {#001}

A **set** is any collection of objects.

-   Could be a collection of all oranges in a basket.

-   Could be the set of all possible fruits in the store.

-   Could be the set of all things in the universe.

The **set** is the collection of objects, while the **elements** of the set are each specific object within the set.

<br />

The most common type of set in Political Science, is the set of all values that a particular variable can take.

-   A variable can take multiple values. For example, the GDP of a country can take a large number of values - any real number.

    -   Thus, the GDP is in the set of all real numbers.

-   Net immigration is a variable that can take any integer (whole positive number).

    -   Thus, net immigration is in the set of all integers.

<br />

To understand statistics in Political Science, we need to understand set notation:

-   A capital letter represents a set. Let us define a set as $A$

-   A lowercase letter represents an element in that set. Let us define an element as $a$

-   We can use any letters - just be consistent: the elements of a set should be the same letter as the set (ex. $b$ and $B$).

<br />

We can represent $a$ as an element of set $A$ with the following notation:

$$
a \in A, \text{ where } \in\ \text{ means in}
$$

<br />

To define a set $A$, the simplest way is to list out all the elements that belong to $A$.

$$
A = \{1,2,3,5,10,11 \}
$$

<br />

We can also define set $A$ in different ways. If we want to write the set of all things within a range, we can write:

$$
A = [0, 1], \text{ set of all things between 0 & 1, including 0 & 1}
$$

$$
A = (0, 1), \text{ set of all things between 0 & 1, excluding 0 & 1}
$$

<br />

Finally, we can define $A$ using a variable $x$, and the operator $|$, meaning such that:

$$
A = \{x | x ≤ 1, x \in R \}
$$

The above means: Set A is equal to $x$, such that $x$ is less than or equal to $1$, and $x$ is in the set of real numbers $R$. We could also rewrite the set to:

$$
A = (-∞, 1]
$$

For the set of real numbers, we use $R$ as convention. Here are other commonly used sets and their notation:

-   Set of Natural Numbers: $N$

-   Set of integers: $Z$

-   Set of rational numbers: $Q$

<br />

### Set Operators {#003}

Lets say that we have two sets: set $A$ and set $B$.

The **intersection** (overlap of the same elements) of $A$ and $B$ is notated:

$$
A \cap B 
$$

If the intersection (overlap of the same elements) of $A$ and $B$ is empty - i.e. the sets do not share any elements in common, the result of $A \cap B$ is the null set $\varnothing$, which simply means the set of nothing.

$$
A \cap B = \varnothing
$$

If the intersection (overlap of the same elements) of $A$ and $B$ does include some elements, we can define set $C$ as the overlap/intersection of $A$ and $B$

$$
A \cap B = C, \space C\text{ being the set of the intersection }
$$

<br />

Lets say that we want to define a set $D$, that is the combination of all elements of set $A$ and $B$.

This is called the **union** of $A$ and $B$, and is notated:

$$
A \cup B = C, \space C \text{ containg all elements of } A \text { & } B
$$

<br />

The **complement** of a set $A$, is everything not in set $A$.

$$
A^c \text { or } A'\text{ is the complement of } A
$$

<br />

The **subset** $A$ is a subset of set $B$, means all elements of $A$ belong to $B$. This means the number of elements in $A$ must be less than or equal to the number of elements in $B$. If we are confident that $A < B$, this is a proper subset, where A is contained in B.

$$
A \subseteq B, \text{where we are unsure if } |A| < |B|
$$

$$
A \subset B, \text{where we are sure } |A| < |B|, \text{ a proper subset}
$$

$$
A \not\subset B, \text{ where } |A| \subseteq |B| \text{ but } A=B, \text{ not proper subset}
$$

Note: $|A|$ and $|B|$ refer to the number of elements in a set.

<br />

Let us say $A \cap B ≠ \varnothing$ (meaning there is some overlap between $A$ and $B$. The **set difference** is set $A$, but with all values within set $A$ that also fall into set $B$ removed:

$$
A \setminus B = A - (A \cap B)
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/#maths)

# Definition of Function {#function}

[Dimensionality](#1001) \| [Definition of Function](#1002)

Functions are the backbone of regression and predictive analyses in Political Science. Thus, it is important to understand what functions are.

<br />

### Dimensionality {#1001}

Before we describe functions, we need to understand **Dimensionality**:

-   $R^1$ , is a one dimensional line. It is the set of all real numbers between $-∞$ to $∞$.

    -   In other words, it is the real number line.

<br />

We can increase the number of dimensions to more than 1.

-   $R^2$ is a two dimensional plane. Dimension 1 is the set of all real numbers between $-∞$ and $∞$, and Dimensions 2 is another set of all real numbers between $-∞$ and $∞$.

    -   Think of a cartesian plane where we graph lines in 2 dimensions, $x$ and $y$

-   $R^3$ is a 3-dimensional space, with $x$, $y$, and $z$ axes, each the set of all real numbers between $-∞$ and $∞$.

    -   Think of a coordinate location system, for example, in the game Minecraft. $x$ is longitude, $y$ is latitude, and $z$ is height.

-   $R^n$ is an $n$-dimensional space, where each of the $n$ number of axes contains the set of all real numbers between $-∞$ and $∞$.

    -   This is often referred to as the Euclidean space.

<br />

### Definition of Function {#1002}

A function is a rule, or a transformation, that takes an input of $R^n$, and returns one, and only one number in $R^1$

-   A function of one variable is an input of $R^1$ , and an output of $R^1$

    -   For example, $f(x) = x + 1$. This function takes an input of some $x$ in $R^1$, and returns a real number in $R^1$

-   A function of two variables is an input of $R^2$, and an output of $R^1$

    -   For example, $f(x,y) = x^2 + y^2$. This function takes an input of some $x$ and $y$ in $R^2$, and returns a real number in $R^1$

<br />

In political science, we often use $x$ to represent the input variable, and $y$ to represent the output variable.

If there are more than one input variables (input $R^n$ when $n > 1$ ), we often put subscripts on the $x$'s, such as: $x_1, x_2, ... , x_p$

Input variables $x$ in the space $R^n$ are called **independent** or **explanatory** variables. The output variable $y$ in space $R^1$ is called a **dependent** or **response** variable.

<br />

Some key properties of functions:

-   The **domain** of $f(x)$ is the set of numbers in $X$ at which $f(x)$ is defined.

-   The **range** of $f(x)$ is the elements of $Y$ assigned by $f(x)$ to elements of $X$

    -   This is sometimes called the **image** when input $R^n$ has $n > 1$

<br />

Common types of functions that we will see in Political Science include:

-   Monomials: in the form of $f(x) = ax^k$

-   Polynomials - the sum of monomials. The degree of a polynomial is its highest powered term.

    -   Example: $f(x) = 5x^3 + 3x^2 + 2x + 4$ is a 3rd degree polynomial

-   Rational Functions: the ratio of two polynomials.

    -   Example: $f(x)=\frac{x2+1}{x2-2x+1}$

-   Exponential Functions: when $x$ is the the exponent

    -   Example: $f(x)=2^x$

-   Linear functions: polynomials with degree 1: $f(x) = mx + b$

    -   These are very important for linear regression.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/#maths)

# Zeroes, Limits, and Continuity {#zeroes}

Zeroes \| Limits \| Definition of Continuity

### Zeroes (Or Roots) {#2001}

Zeroes (or Roots) are the values of the input of a function, where the output of the function equals $0$.

-   Essentially, the value of $x$ when $f(x) = 0$

These are important in Political Science, as they are important in finding equilibria, as well as maximum likelihood estimation.

<br />

To solve for Zeroes/Roots, simply set the function $f(x) = 0$, and solve for $x$.

-   Alternatively, you can use a graphing programme, such as Desmos, to plot the function, and find at what $x$ does it cross the line $y = 0$

<br />

Some functions have multiple roots (especially polynomials). For example, consider the function $f(x) = x^2 - 16$. Let us solve for the roots:

$$
f(x) = x^2 - 16
$$

$$
0 = x^2 - 16
$$

$$
x^2 = 16
$$

$$
x = ±4
$$

<br />

For quadratic equations (polynomials of degree 2), there is a formula called the **Quadratic Formula** which solves for the roots:

$$
x = \frac{-b ± \sqrt{b^2-4ac}}{2a}
$$

<br />

Given the quadratic in the form of $f(x)=ax^2+bx+c$

Note: the quadratic formula generally returns 2 real zeroes/roots, but this is not always the case. Remember to check both the $+$ and $-$ in the numerator.

<br />

### Limits {#2002}

A limit is when a function approaches some specific $y$ value $L$, as $x$ moves toward some value $c$.

-   Often, this specific $y$ value $L$ in question is either $L=0$ or $L=±∞$
-   Approaching basically means the $y$ value becomes infinitely close towards $L$, as the $x$ value becomes infinitely close to $c$

For a limit to exist, it must approach the same $y$ value $L$ from both sides of $x = c$

-   For example, if from the left as $x$ approaches $c$, $y$ approaches $∞$, and if from the right as $x$ appraoches $c$, $y$ approaches $∞$, we have a limit.

-   But, if from the left as $x$ approaches $c$, $y$ approaches $∞$, and if from the right as $x$ appraoches $c$, $y$ approaches $-∞$, we do not have a limit, because the $y$ value being approached on either side is not the same.

If a limit exists, we can say $\lim\limits_{x \rightarrow c} f(x) = L$

-   Note: $f(x)$ does not need to be defined at $x=c$ for the limit to exist. It just must approach the same $y=L$ on both sides infinitely close to $x=c$.

<br />

Let us assume $f$ and $g$ are functions with $\lim\limits_{x \rightarrow c} f(x) = A$ and $\lim\limits_{x \rightarrow c} g(x) = B$. The following properties include:

$$
1. \space\lim\limits_{x \rightarrow c} [f(x)+g(x)] = \lim\limits_{x \rightarrow c} f(x) + \lim\limits_{x \rightarrow c} g(x)
$$

$$
2. \space \lim\limits_{x \rightarrow c} \alpha f(x) = \alpha \lim\limits_{x \rightarrow c} f(x)
$$

$$
3. \space \lim\limits_{x \rightarrow c} f(x) * g(x) = [\lim\limits_{x \rightarrow c} f(x)] * [\lim\limits_{x \rightarrow c} g(x)]
$$

$$
4. \space \lim\limits_{x \rightarrow c} \frac{f(x)}{g(x)} = \frac{\lim\limits_{x \rightarrow c} f(x)}{\lim\limits_{x \rightarrow c} g(x)}, \space given \space \lim_{x \rightarrow c} g(x) ≠ 0
$$

<br />

We will expand on limits in the calculus topics. Limits are important because they lead to our definition of continuity.

<br />

### Continuity {#2003}

Continuity is an important concept for statistical applications. Most of us probably have an idea of what continuity is: a function has no breaks or jumps within a certain interval. Let us introduce a more formal definition.

<br />

Suppose that the function $f$ has an interval containing point $c$.

$f$ is continuous at point $c$, if these 2 criteria are both met:

1.  $\lim\limits_{x \rightarrow c} f(x)$ exists (i.e. it approaches the same $y$ value at $x=c$ on both sides.
2.  $\lim\limits_{x \rightarrow c} f(x) = f(c)$ (i.e. the value $f$ approaches on both sides of $x=c$, is also the value of $f$ at point $c$).

<br />

We can test our intuition about continuity with the above mathematical definition:

-   If the function has a break at point $c$, it won't be defined at $f(c)$. Thus, criteria 2 will not be met.

-   If the function has a sudden "jump" at point $c$, then $\lim\limits_{x \rightarrow c} f(x)$ won't exist, since it is approaching point $c$ towards two different $y$ values.

<br />

The following are properties of continuity:

-   If functions $f$ and $g$ are both continuous at $x=c$, and where $\alpha$ represents a constant, then the functions $f + g$, $f - g$, $f * g$ , $|f|$, and $\alpha * f$ are also continuous at $x = c$

-   If functions $f$ and $g$ are both continuous at $x=c$, then $f / g$ is continuous at $x=c$, given that $g(c) ≠ 0$

-   If $f$ is continuous at interval $[a,b]$, then $f$ has a maximum and mininum value within $[a,b]$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/#maths)

# Exponents and Logarithms {#exponents}

[Properties of Exponents](#3001) \| [Logarithms](#3002)

### Properties of Exponents {#3001}

These are some key properties of exponents and exponential functions:

$$
1. \space a^x*a^y = a^{x+y}
$$

$$
2. \space a^{-x} = \frac{1}{a^x}
$$

$$
3.  \space \frac{a^x}{a^y} = a^{x-y}
$$

$$
4.  \space (a^x)^y = a^{x*y}
$$

$$
5. \space a^0 = 1
$$

<br />\
Another important topic to understand is how to solve for $x$ taken to an exponent. Let us take the equation $x^{0.7} = 5$, and solve for x

$$
x^{0.7} = 5
$$

$$
(x^{0.7})^{\frac{1}{0.7}} = 5^{\frac{1}{0.7}}
$$

$$
x = 5^{\frac{1}{0.7}} = 5^{1.4828}
$$

<br />

We can generalise this to the following:

$$
x^n = a, x = a^{\frac{1}{n}}
$$

<br />

### Logarithms {#3002}

Log functions can be thought of as the inverse for exponential functions. The relationship between the two is as follows:

$$
y = log_a (x) \leftarrow \rightarrow a^y = x
$$

<br />

$a$ is the base of the logarithm. There are two common bases that we will use in Political Science:

-   Base 10 ( $a = 10$ ): $log_{10} (x)$ is often just written as $log (x)$, without a base.

-   Base $e$ ( $a = e$ ): $log_e (x)$ is often written as $ln(x)$, also called a natural log.

Specifically in the fields of statistics and social science, we also write base $e$ $log_e(x)$ as just $log(x)$

-   This is because we will primarily be using natural logs in statistics.

<br />

Below are some key properties of logarithmic functions, that work with any base (as long as the base is consistent).

$$
1. \space log(xy) = log(x) + log(y)
$$

$$
2. \space log(x^y) = y * log(x)
$$

$$
3. \space log( \frac{1}{x} ) = -log(x)
$$

$$
4. \space log( \frac{x}{y} ) = log(x) - log(y)
$$

$$
5. \space log(1) = log(e^0)= 0
$$

<br />

If needed, we can also change the base of our logarithms with the following formula:

$$
log_b (x) = \frac{log_a (x)}{log_a (b)}
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/#maths)

# Summation and Product Notation {#summation}

[Summation Notation](#4001) \| [Product Notation](#4002)

### Summation Notation {#4001}

Summation Notation is a short-hand way of expressing the sums of many values.

Summation Notation is quite important in Political Science, as minimising the **sum of squared errors** is a key topic in Regression and advanced Data Science Techniques.

<br />

Summation Notation is defined as the following:

$$
\sum\limits_{i=1}^{n} x_i = x_1 + x_2 + x_3 + ... + x_n
$$

-   $i=1$ indicates that we start summing at the index $i=1$. Sometimes, you will see $i = 0$, and rarely, $i$ will be equal to something else.

-   $n$ is the value at which we stop summing. This is generally the sample size in statistics.

-   $x_i$ is the $x$ value at index value $i$. When $i = 1$, $x$ is $x_1$, when $i = 2$, $x$ is $x_2$, and so on.

-   What does index mean? Well, lets say you have a sample with 100 observations, so sample size $n=100$. Then, $x_1$ is the $x$ value of the 1st observation, $x_2$ is the $x$ value of the 2nd observation, and so on, until you reach the final observation $x_n$.

<br />

These are the properties of Summation Notation, where $c$ is some constant number:

$$
1. \space \sum\limits_{i=1}^{n} cx_i = c \sum\limits_{i=1}^{n} x_i
$$

$$
2. \space \sum\limits_{i=1}^{n} (x_i + y_i) = \sum\limits_{i=1}^{n} x_i + \sum\limits_{i=1}^{n} y_i
$$

$$
3. \space\sum\limits_{i=1}^{n} c = n * c
$$

<br />

### Product Notation {#4002}

Product notation is a short-hand way of expressing the products of many values.

Product notation is quite important in Political Science, specifically in **Maximum Likelihood Estimation (MLE)**, the primary way of determining coefficient values in a Logistic Regression.

<br />

Product Notation is defined as the following:

$$
\prod\limits_{i=1}^{n} x_i = x_1 * x_2 * x_3 * x_4 * ... x_n
$$

-   $i=1$ indicates that we start multiplying at the index $i=1$. Sometimes, you will see $i = 0$, and rarely, $i$ will be equal to something else.

-   $n$ is the value at which we stop multiplying. This is generally the sample size in statistics.

-   $x_i$ is the $x$ value at index value $i$. When $i = 1$, $x$ is $x_1$, when $i = 2$, $x$ is $x_2$, and so on.

-   What does index mean? Well, lets say you have a sample with 100 observations, so sample size $n=100$. Then, $x_1$ is the $x$ value of the 1st observation, $x_2$ is the $x$ value of the 2nd observation, and so on, until you reach the final observation $x_n$.

<br />

These are the properties of Product Notation, where $c$ is some constant number:

$$
1. \space \prod\limits_{i=1}^{n} cx_i = c^n * \prod\limits_{i=1}^{n} x_i
$$

$$
2. \space \prod\limits_{i=1}^{n} c = c^n
$$

<br />

We can also transition between [Summation Notation](#4001) and Product Notation with Logarithms, which is important in Maximum Likelihood Estimation (MLE).

$$
log( \prod\limits_{i=1}^{n} x_i ) = log(x_1 * x_2 * x_3 * ... * x_n)
$$

$$
= log(x_1) + log(x_2) + log(x_3) + ... + log(x_n)
$$

$$
= \sum\limits_{i=1}^{n} log(x_i)
$$

<br />

We can also add a constant $c$ for a more general rule:

$$
log( \prod\limits_{i=1}^{n} cx_i) = log(cx_1 * cx_2 * ... * cx_n)
$$

$$
= log(c^n * x_1 * x_2 *... *x_n)
$$

$$
= log(c^n) + log(x_1) + log(x_2) + ... + log(x_n)
$$

$$
= n log(c) + \sum\limits_{i=1}^{n} log(x_i)
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/#maths)
