---
title: 'Derivatives II: Applications'
output: html_document
date: "2024-08-31"
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
  line-height: 150%;
}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Course Homepage](https://politicalscience.github.io/#maths)

## Table of Contents {#contents}

-   [Maxima and Minima](#maxima)

-   [Partial Derivatives](#partial)

<br />

------------------------------------------------------------------------

[Course Homepage](https://politicalscience.github.io/#maths) \| [Table of Contents](#contents)

# Maxima and Minima {#maxima}

[Slope and Concavity](#1001) \| [Maxima and Minima](#1002)

### Slope and Concavity {#1001}

From the previous lesson [Derivatives I: Calculating Derivatives](https://politicalscience.github.io/math/derivatives.html), we know that a derivative is a function $f'(x)$, whose value at $x$ is the rate of change of $f(x)$ at $x$.

From $f'(x)$ is the rate of change of $f(x)$ at $x$, we know the following:

1.  If $f'(x) < 0$, then $f(x)$ is decreasing
2.  If $f'(x) > 0$, then $f(x)$ is increasing
3.  If $f(x) = 0$, then $f(x)$ is neither increasing or decreasing.

<br />

Concavity is whether a curve opens upward or downward. A function is **concave up** when the slope is increasing, and a function is **concave down** when the slope is decreasing.

How do we know if the slope is increasing or decreasing at some point on $x$?

-   Well, the derivative is, by definition, the rate of change of a function at x.

-   So, the rate of change, of the slope (rate of change) of the original $f$, tells us the rate of change of the slope of $f$

-   The rate of change, of the rate of change, is simply the derivative of the derivative, or, in other words, the second-order derivative $f''(x)$ of $f(x)$

<br />

Thus, from $f''(x)$ as the rate of change of the rate of change of $f(x)$ at $x$, we know the following:

1.  If $f''(x) < 0$, then $f(x)$ is concave down
2.  If $f''(x) > 0$, then $f(x)$ is concave up
3.  If $f''(x) = 0$, then $f(x)$ is neither concave up or down

<br />

Let us take a look at a few examples.

Example 1: Take $f(x) = x^2 + 2$. When is $f(x)$ increasing, decreasing, and is it concave up or down?

-   Let us first find $f'(x)$. Using power rule, we know $f'(x) = 2x$

-   So when is $f(x)$ increasing or decreasing.

    -   When $f'(x) > 0$, then $f(x)$ is increasing. $f'(x) = 2x$ is greater than 0 for range $(0 < x < ∞)$

    -   When $f'(x) < 0$, then $f(x)$ is decreasing. $f'(x) = 2x$ is less than 0 for the range $(-∞ < x < 0)$

-   What is the concavity of $f'(x)$? We know we can tell this with $f''(x)$.

    -   To find $f''(x)$, we take the derivative of $f'(x)$.

    -   $f'(x) = 2x$, so by power rule, we know $f''(x) = 2$

    -   $2 > 0$, so the function is concave up.

    -   This makes sense, since if we visualise the graph of $f(x) = x^2 + 2$, it is a parabola opening upward

<br />

### Maxima and Minima {#1002}

To understand maxima and minima, we must first look at **critical points**.

Critical points are defined as one of the following, given $D$ is the domain where function $f$ is defined:

1.  Any point of $D$ where $f'(x)$ = 0
2.  Any point of $D$ where $f'(x)$ does not exist (any $D$ where $f$ is not differentiable)
3.  Any endpoint that is in $D$

<br />

Maxima and Minima are a subset of the critical points - i.e., the are included in the critical points, but they do not make up all the critical points.

There are two types of Maxima. A Maximum of $f$ exists at $x=x_0$ by the following definitions:

1.  Local Maxima: where $f(x_0) > f(x)$ for all $x$ in some interval containing $x_0$
2.  Global Maxima: where $f(x_0) > f(x)$ for all $x$ in the domain $D$ of $f$

There are two types of Minima. A Mininum of $f$ exists at $x=x_0$ by the following definitions:

1.  Local Minima: where $f(x_0) < f(x)$ for all $x$ in some interval containing $x_0$
2.  Global Minima: where $f(x_0) < f(x)$ for all $x$ in the domain $D$ of $f$

<br />

When identifying maxima and minima, we first identify local ones, before we identify global ones. We can use the **Second Derivative Test of Maxima/Minima** to tell whether a point is a maximum or minium of $f(x)$

-   Local Maximum exists at $x_0$ if $f'(x_0) = 0$ and $f''(x_0) < 0$

-   Local Mininum exists at $x_0$ if $f'(x_0) = 0$ and $f''(x_0) > 0$

If $f'(x_0) = 0$ and $f''(x_0) = 0$, we might have a global maxima/minima, however, we cannot be sure.

-   Why? Well it is possible for no global max or min to exist - such as a function that goes from $-∞$ to $∞$

However, there are 3 situations where we can identify global max and min when this condition is met.

1.  Functions with only one critical point/only one local maximum/mininum. When this happens, we know that point is the global max or min.
2.  Globally concave up or concave down: If $f''(x)$ never is zero, then there cannot be more than one critical point. That critical point is the global maximum if $f''(x) < 0$, and global mininum if $f''>0$
3.  Functions over a closed and bounded intervals must have both a global maximum or global mininum.

If $f'(x_0) = 0$, yet no maxima/minima are at $x_0$, this is considered a **saddle point**.

<br />

Of course, if you have a graphing programme like desmos, you can also quickly identify maxmima/minima.

<br />

Let us take a look at the following example: Find any critical points, and identify if they are a maximum, mininum, or saddle point, of the function $f(x) = x^2 + 2$

-   We know the following criteria about critical points:

    1.  Any point of $D$ where $f'(x)$ = 0

    2.  Any point of $D$ where $f'(x)$ does not exist (any $D$ where $f$ is not differentiable)

    3.  Any endpoint that is in $D$

-   Let us first find $f'(x)$. Using power rule, we know $f'(x) = 2x$

-   We can quickly eliminate criteria 2 and 3, as $f'(x) = 2x$ is defined from $(-∞,∞)$, and there is no interval given so no endpoints in $D$.

-   Now, we should solve for the zeroes: $f(x) = 0$

    -   $0 = 2x$, thus $f(x) = 9$ when $x = 0$

-   Thus, we know there is a critical point at $x=0$

-   Now, is this a local maxima or minima?

    -   Through power rule, we know $f''(x) = 2$

    -   Thus, we know there is a local mininum, since the conditions $f'(x_0) = 0$ and $f''(x_0) > 0$ are met.

-   Now is there a global mininum? Yes, since there is only one critical point and one local mininum, it must be the global mininum.

<br />

------------------------------------------------------------------------

[Course Homepage](https://politicalscience.github.io/#maths) \| [Table of Contents](#contents)

# Partial Derivatives {#partial}

[Partial Derivatives](#2001) \| [Application: Marginal Rate of Technical Substitution](#2002)

### Partial Derivatives {#2001}

Suppose that we have a function $f$ with inputs of two or more variables.

-   We want to determine the rate of change relative to one of the variables.

-   To do so, we would employ a partial derivative - since we are only interested in the rate of change relative to one of the variables.

<br />

A partial derivative of the variable $x_i$ is defined mathematically as:

$$
\frac{\partial}{\partial x_i} f(x_1,...,x_i,...,x_n) = \lim\limits_{h \rightarrow 0} \frac{f(x_1,...,x_i + h,...,x_n) - f(x_1,...,x_i,...,x_n)}{h}
$$

<br />

-   Where $x_1, ..., x_n$ are all different input variables of function $f$

-   Where we are interested in the rate of change relative to variable $x_i$ specifically, so we are finding the derivative in respect to $x_i$ specifically: $\frac{d}{dx_i}$

-   Thus, we treat $x_i,...,x_n$ that are not $x_i$ simply as constants (we don't find the derivative in respect to those, treat them like you would treat a constant $c$, like $5$).

Note: we use $\frac{\partial}{\partial x}$ instead of $\frac{d}{dx}$ to indicate partial derivatives (Cyrillic $\partial$ instead of Latin $d$)

<br />

For example, let us take the following function of input variables $x, z$:

$$
f(x,z) = 5x^2z^3 + 2x+ 3z +5
$$

<br />

We can take the derivative of either $x$ or $z$, holding the other variable constant.

<br />

Let us look at a few examples:

**Example 1: Given the function** $f(x,z) = 5x^2z^3 + 2x+ 3z +5$**, find the derivative in respect to** $x$

*We can use the sum rule and power rule to take the derivative of this. Treat all* $z$ *as just some constant (this includes* $z^k$*, which in this scenario, is just a constant to the power of something, also a constant).*

$$
f(x,z) = 5x^2z^3 + 2x+ 3z +5
$$

$$
\frac{\partial}{\partial x} f(x, z) = \frac{\partial}{\partial x}[5x^2z^3] + \frac{\partial}{\partial x} [2x] + \frac{\partial}{\partial x} [3z] + \frac{\partial}{\partial x}[5]
$$

$$
\frac{\partial}{\partial x} f(x, z) = 10z^3 x + 2 +0 + 0
$$

$$
\frac{\partial}{\partial x} f(x,z) = 10z^3 x + 2
$$

<br />

**Example 2: Given the function** $f(x,z) = 5x^2z^3 + 2x + 3z + 5$**, find the derivative in respect to** $z$

*We can use the sum rule and power rule to take the derivative of this. Treat all* $x$ *as just some constant (this includes* $x^k$*, which in this scenario, is just a constant to the power of something, also a constant).*

$$
f(x,z) = 5x^2z^3 + 2x + 3z + 5
$$

$$
\frac{\partial}{\partial z} f(x, z) = \frac{\partial}{\partial z}[5x^2z^3] + \frac{\partial}{\partial z} [2x] + \frac{\partial}{\partial z} [3z] + \frac{\partial}{\partial z}[5]
$$

$$
\frac{\partial}{\partial z}f(x,z) = 15x^2z^2 + 0 + 3 + 0
$$

$$
\frac{\partial}{\partial z}f(x,z) = 15x^2z^ + 3
$$

<br />

### Application: Marginal Rate of Technical Substitution {#2002}

Finally, let us look at an application - Marginal Rate of Technical Subsitution (MRTS).

Marginal Rate of Technical Subsitution (MRTS) is an economic concept, describing the ability of a producer to subsitute one input for another, while mantaining the same quantity produced.

For example, producers often debate between two production inputs: how much labour they should hire, and how many machines they should use.

-   Thus, it is important to know what different combinations of labour and machines produce the same amount of output (ex. ).

This is illustrated by a Cobbs-Douglas function, which is a production function $Q$

-   Output of function $Q$ is quantity produced

-   inputs of function $Q$ are inputs for production $x$ and $y$ (in economics, often labour and capital)

<br />

From the Cobbs-Douglas function, we can get the marginal product of X and Y.

Marginal product of X, is the change in total output resulting from the next unit of X used.

-   Basically, what is the benefit to production, when you introduce a unit of X.

Marginal Product of X, is the partial derivative of Cobbs-Douglas function $Y$, only in respect to $x$. Vice versa for Y

-   In essense, $MP_x = \frac{\partial}{\partial x}Q(x,y)$, and $MP_y = \frac{\partial}{\partial y}Q(x,y)$

-   This makes sense - $Q$ is a function of production, so the derivative is the rate of change of production. We want to know how much an additional $x$ or $y$ changes production, which is what the derivative is telling us.

<br />

If we hold the output of $Q$ constant, then we can see how we can substitute labour and capital, while achieving the same amount of production.

-   $Q$ being constant essentially means, the same quantity of production.

<br />

-   Knowing the different combinations of Labour and Capital that produce the same quantity output, allows you to know your "options" of meeting a certain production target, allowing you to chose which "option" is the most cost efficient.

-   For example, pretend that maybe 5 workers and 3 machines, and 6 machines and 2 workers, produce the same amount of output of $Q$.

Marginal Rate of Technical Substitution (MRTS) tells us, at what rate can we exchange $x$ to $y$, while holding $Q$ fixed.

-   Essentially, the Marginal Rate of Technical Subsitution is the rate at which $x$ must decrease, and $y$ must increase, to retain the same level of production.

Marginal Rate of Technical Subsitution is the ratio of the marginal products: $MRTS(x, y) = \frac{MP_x}{MP_y}$

<br />

Now, let us apply this to an example to better understand this. Take this production function $Q$ for quantity produced, which has inputs $x$ and $y$:

$$
Q(x,y)=2x^{0.3}y^{0.7}
$$

Now, let us find the Marginal Product of X, which is the derivative of $Q$ in respect to $x$. We use the power rule, keeping $y$ as a constant.

$$
MP_x = \frac{\partial}{\partial x}[2x^{0.3}y^{0.7}] 
$$

$$
MP_x = 0.6y^{0.7}x^{-0.7}
$$

$$
MP_x = \frac{0.6y^{0.7}}{x^{0.7}}
$$

<br />

Now, let us find the Marginal Product of Y, which is the derivative of $Q$ in respect to $y$. We use the power rule, keeping $x$ as a constant.

$$
MP_y = \frac{\partial}{\partial y} [2x^{0.3}y^{0.7}]
$$

$$
MP_y = 1.4x^{0.3}y^{-0.3}
$$

$$
MP_y = \frac{1.4x^{0.3}}{y^{0.3}}
$$

<br />

Now, let us find the marginal product of technical substitution (MRTS)

$$
MRTS(x,y) = \frac{MP_x}{MP_y}
$$

$$
MRTS(x,y) = \frac{0.6y^{0.7}}{x^{0.7}} ÷ \frac{1.4x^{0.3}}{y^{0.3}}
$$

$$
MRTS(x,y) = \frac{0.6y^{0.7}}{x^{0.7}} * \frac{y^{0.3}}{1.4x^{0.3}}
$$

$$
MRTS(x,y) = \frac{0.6*y^{0.7}*y^{0.3}}{x^{0.7}*x^{0.3}*1.4}
$$

$$
MRTS(x,y) = \frac{0.6y}{1.4x} = \frac{0.429y}{x}
$$

<br />

------------------------------------------------------------------------

[Course Homepage](https://politicalscience.github.io/#maths) \| [Table of Contents](#contents)
