---
title: 'Derivatives I: Calculating Derivatives'
output: html_document
date: "2024-08-30"
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
  line-height: 150%;
}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Course Homepage](https://politicalscience.github.io/#maths)

## Table of Contents {#contents}

-   [Simple Derivatives](#simple)

-   [Composite Functions and Chain Rule](#chain)

-   [Derivatives of Exponential and Natural Log](#exp)

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/#maths)

# Simple Derivatives {#simple}

[Definition of Derivative](#1001) \| C[alculating Simple Derivatives](#1002)

### Definition of Derivative {#1001}

A derivative is a function $f'(x)$, whose value at $x$ is the rate of change of $f(x)$ at $x$.

-   Basically, $f'(x)$ is the measure of the "slope" at any point of $x$ of $f(x)$

-   For linear functions, $f'(x)$ is a constant equivalent to the slope of the line.

-   For curved functions, $f'(x)$ is the slope of the line tangent to the curve at point $x$

<br />

A more formal definition of the derivative of $f$ at point $x$ is:

$$
f'(x) = \lim\limits_{h \rightarrow 0} \frac{f(x+h)-f(x)}{(x+h)-x} = \lim\limits_{h \rightarrow 0} \frac{f(x+h)-f(x)}{h}
$$

<br />

If $f'(x)$ exists at a point $x$, then $f$ is said to be differentiable at $x$.

If $f'(x)$ exists for every point in an interval, then $f$ is differentiable along that interval.

For $f'(x)$ to exist and $f$ to be differentiable, $f$ must be both continuous and smooth at $x$.

-   I.e. $f$ must have a value at $f(x)$, and should not have any sharp edges at $x$

<br />

So far, we have used the apostrophe $f'(x)$ to identify a derivative. Other alternative notation includes:

-   Prime or Lagrange Notation: $y'$, $f'(x)$

-   Operator Notation: $Dy$, $Df(x)$

-   Leibniz's Notation: $\frac{dy}{dx}$

<br />

It is also possible to take the derivative, of a derivative.

-   These are called Higher-Order Derivatives

For example, take $f(x) = x^3$

-   1st Derivative: $f'(x) = 3x^2$

-   2nd Derivative: $f''(x) = 6x$

-   3rd Derivative: $f'''(x) = 6$, and so on...

<br />

### Calculating Simple Derivatives {#1002}

There are a few main rules in calculating simple derivatives. With these main rules, most simple derivatives are calculable.

Suppose that $f$ and $g$ are both differentiable at $x$, and that $\alpha$ is a constant:

$$
1. \space Power \space Rule: [x^k]'=kx^{k-1} 
$$

$$
2. \space Sum \space Rule: [f(x) ± g(x)]' = f'(x) ± g'(x)
$$

$$
3. \space Constant \space Rule:[\alpha f(x)]' = \alpha f'(x)
$$

$$
4. \space Product \space Rule:[f(x)g(x)]' = f'(x)g(x) + f(x)g'(x) 
$$

$$
5. \space Quotient \space Rule: [f(x)/g(x)]' = \frac{f'(x)g(x) - f(x)g'(x)}{[g(x)]^2}, \space given \space g(x)≠0
$$

$$
6. \space Linear \space Rule: [mx]' = m, \space given \space m \space is\space a \space constant
$$

$$
7.  \space Linear \space Rule: [c]' = 0, \space given \space c \space is\space a \space constant
$$

<br />

Now let us look at a few examples:

Example 1: Find $f'(x)$ if $f(x) = 5x^4$

1.  Constant rule with $\alpha = 5$: $f'(x) = 5 * [x^4]'$
2.  Power rule $k=4$ the second part: $f'(x) =5 * 4x^3$
3.  Now, simplify: $f'(x) = 20x^3$

<br />

Example 2: Find $f'(x)$ if $f(x) = 5x^4 - 6x^3 + x^2 - 4x + 6$

-   We know that the sum rule says: $[f(x) ± g(x)]' = f'(x) ± g'(x)$

-   So, we know in this case: $f'(x) = [5x^4]' - [6x^3]' + [x^2]' - [4x]' + [6]'$

-   Now, we apply the constant and power rule like in example 1 to every individual monomial: $f'(x) = 20x^3 - 18x^2 + 2x - 4 + 0$

-   Simplify: $f'(x) = 20x^3 - 18x^2 + 2x - 4$

<br />

Example 3: Find $f'(x)$ if $f(x) = (x^3)(2x^4)$

-   We actually have two ways to find the derivative.

-   Let us first use the product rule: $[f(x)g(x)]' = f'(x)g(x) + f(x)g'(x)$

    -   We can make $f(x) = x^3$, and $g(x) = 2x^4$

    -   Then using constant and power rule like in example 1 to both monomials: $f'(x) = 3x^2$, and $g'(x) = 8x^3$

    -   Then, product rule: $[f(x)g(x)]' = (3x^2)(2x^4) + (x^3)(8x^3)$

    -   $[f(x)g(x)]' = 3*2*x^2*x^4 + 8*x^3*x^3$

    -   $[f(x)g(x)]' = 6x^6 + 8x^6 = 14x^6$

    -   Thus, $f'(x) = 14x^6$

-   We can check our answer with the constant + power rule method:

    -   First, let us simplify $f(x)$: $f(x) = (x^3)(2x^4) = 2x^7$

    -   Now, apply constant and power rule like in example 1: $f'(x) = 14x^6$

-   We get $f'(x) = 14x^6$ with both methods.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/#maths)

# Composite Functions and Chain Rule {#chain}

[Composite Functions](#2001) \| [Chain Rule](#2002)

### Composite Functions {#2001}

Composite functions are when we substitute one function into another.

-   For example, take $f(x) = x^2$, and $g(x) = 2x$

-   We could insert $g(x)$ as the input of $f(x)$

-   This would get us $f[g(x)] = (2x)^2$

<br />

We use the following notation to indicate composite functions:

$$
(f \circ g)(x) = f[g(x)]
$$

<br />

Please note, $(f \circ g)(x)$ and $(g \circ f)(x)$ are different functions.

$$
(g \circ f)(x) = g[f(x)]
$$

<br />

To from $(f \circ g)(x)$, the range of $g$ (the outputs of function $g$ ) must be contained, at least in part, within the domain of $f$.

-   Why? Well if none of the outputs of $g$ are in the domain of $f$, that means none of the inputs of $f(x)$ will be within its domain, meaning that there are no valid outputs of $(f \circ g)(x)$

-   The domain of $(f \circ g)(x)$ is all the points in the domain of $g$, for which the output of $g(x)$ is also the domain of $f$.

<br />

### Chain Rule {#2002}

Chain Rule solves derivatives of $f$ that are in the form of composite functions. Chain Rule States:

$$
[(f \circ g)(x)]' = f'[g(x)] * g'(x)
$$

<br />

We can also create a Generalised Power Rule dealing with composite function $(f \circ g)(x)$ when $f(x)$ takes the form of $x^k$

$$
\frac{d}{dx} [g(x)]^k = k[g(x)]^{k-1} g'(x)
$$

<br />

Now let us look at a few examples:

Example 1: find $f'(x)$ if $f(x) = (2x)^2$

-   We have two ways to find the derivative.

-   Let us first use the chain rule: $[(f \circ g)(x)]' = f'[g(x)] * g'(x)$

    -   $f(x) = (2x)^2$ is the composite function $(f \circ g)(x)$ if $f(x) = x^2$ and $g(x) = 2x$

    -   Then, by power rule, $f'(x) = 2x$, and $g'(x) = 2$

    -   Now, apply chain rule: $[(f \circ g)(x)]' = 2(2x)*2$

    -   Simplify: $[(f \circ g)(x)]' = 8x$

-   We can also use the constant + power rule:

    -   Let us first rewrite $f(x)$: $f(x) = (2x)^2 = (2x)(2x) = 4x^2$

    -   Now, let us apply constant + power rule: $f'(x) = 8x$

-   We get $f'(x) = 8x$ with both methods.

<br />

Example 2: find $f'(x)$ if $f(x) = (3x^2 + 5x - 7)^6$

-   We have two ways to find the derivative.

-   First, let us use the chain rule: $[(f \circ g)(x)]' = f'[g(x)] * g'(x)$

    -   $f(x) = (3x^2 + 5x - 7)^6$ is the composite function $(f \circ g)(x)$ if $f(x) = x^6$ and $g(x) = 3x^2 + 5x - 7$

    -   Using power rule, we know $f'(x) = 6x^5$

    -   Using Sum Rule with constant + power rule on each monomial, we know that $g'(x)=6x + 5$

    -   Now, apply chain rule: $[(f \circ g)(x)]' = 6(3x^2+5x-7)^5*(6x+5)$

-   Second, let us use the generalised power rule: $\frac{d}{dx} [g(x)]^k = k[g(x)]^{k-1} g'(x)$

    -   In this format, we know $g(x)$ is what is in the base of the polynomial: $g(x) = 3x^2 + 5x - 7$

    -   Now, apply generalised power rule where $k=6$ : $\frac{d}{dx} [g(x)]^k = 6(3x^2+5x-7)^5 * (6x+5)$

-   For both, we get $f'(x) = 6(3x^2+5x-7)^5 * (6x+5)$

-   This isn't a very elegant solution, but it is difficult to simplify. We could multiply out the $(6x+5)$ to get $f'(x) = 36x(3x^2+5x-7)^5+30(3x^2+5x-7)^4$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/#maths)

# Derivatives of Exponentials and Natural Logs {#exp}

Derivatives of Exponentials \| Derivatives of Natural Logs

### Derivatives of Exponentials

Here are the main properties for derivatives of exponential functions with base $e$

$$
1. \space \frac{d}{dx} e^x = e^x 
$$

$$
2. \space \frac{d}{dx} \alpha e^x = \alpha e^x
$$

$$
3. \space \frac{d}{dx} e^{u(x)} = e^{u(x)}u'(x)
$$

<br />

One final property for non-base $e$, for any positive base $b$:

$$
\frac{d}{dx} b^x = (\ln{b})(b^x)
$$

<br />

Now let us look at a few examples:

Example 1: Find $f'(x)$ if $f(x) = e^{-3x}$

-   We can use the rule: $\frac{d}{dx} e^{u(x)} = e^{u(x)}u'(x)$

-   We know $u(x)$ in this case: $u(x) = -3x$

-   Using the linear rule, $u'(x) = -3$

-   Thus, applying the format $\frac{d}{dx} e^{u(x)} = e^{u(x)}u'(x)$, we know: $f'(x) = e^{-3x}*-3$

-   Simplified: $f'(x) = -3e^{-3x}$

<br />

Example 2: Find $f'(x)$ if $f(x) = e^{x^2}$

-   We can use the rule: $\frac{d}{dx} e^{u(x)} = e^{u(x)}u'(x)$

-   We know that $u(x)$ in this case: $u(x) = x^2$

-   Using power rule, $u'(x) = 2x$

-   Thus, applying the format $\frac{d}{dx} e^{u(x)} = e^{u(x)}u'(x)$, we know: $f'(x) = e^{x^2}*2x$

-   Simplified: $f'(x) = 2xe^{x^2}$

<br />

### Derivatives of Natural Logs

Here are the main properties of the derivatives of natural logs:

$$
1. \space \frac{d}{dx} \ln{x} = \frac{1}{x}
$$

$$
2. \space \frac{d}{dx} \ln{x^k} = \frac{d}{dx} k \ln{x} = \frac{k}{x} 
$$

$$
3. \space \frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}
$$

<br />

Now let us look at a few examples:

Example 1: Find $f'(x)$ if $f(x) = \ln(x^2+9)$

-   We can use the rule: $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$

-   We know that $u(x)$ in this case: $u(x) = x^2+9$

-   Using power rule, $u'(x) = 2x$

-   Thus, applying the format $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$, we know: $f'(x) = \frac{2x}{x^2+9}$

<br />

Example 2: Find $f'(x)$ if $f(x) = \ln{(\ln{x})}$

-   We can use the rule: $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$

-   We know that $u(x)$ in this case: $u(x) = \ln x$

-   Using the rule $\frac{d}{dx} \ln{x} = \frac{1}{x}$, we know that $u'(x) = \frac{1}{x}$

-   Thus, applying the format $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$, we know: $f'(x) = \frac{1}{x} * \frac{1}{\ln x}$

-   Simplified: $f'(x) = \frac{1}{x \ln x}$

<br />

Example 3: Find $f'(x)$ if $f(x) = \ln e^x$

-   We have two ways of solving this question:

-   We can use the rule: $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$

    -   We know that $u(x)$ in this case: $u(x) = e^x$

    -   Using the rule $\frac{d}{dx} e^x = e^x$, we know $u'(x) = e^x$

    -   Thus, applying the format $\frac{d}{dx} \ln{u(x)} = \frac{u'(x)}{u(x)}$, we know: $f'(x) = \frac{e^x}{e^x}$

    -   Simplifying: $f'(x) = 1$

-   Or, we can remember the definition of logarithms: $y = log_a (x) \leftarrow \rightarrow a^y = x$

    -   Our equation is $y = \log_e e^x$, which means $a = e$ and $x = e^x$, so it would be the same as $e^y = e^x$

    -   Thus, $y=x$.

    -   Then, we take the derivative: $\frac{dy}{dx} = 1$

    -   Thus, $f'(x) = 1$

-   We get the same answer $f'(x) = 1$ for both.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/#maths)
