---
title: "Maths for Political Science"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
---

[Homepage](https://politicalscience.github.io)

These notes covers some of the key topics in algebra, calculus, and linear algebra needed to understand the methods behind political science.

<br />

**Prerequisites**: Algebra to the level of a typical secondary education.

<br />

### Chapter 1: Topics in Algebra

*Foundations of higher level mathematics and basics commonly used.*

| Lesson | Topics |
|-----------------------------------------|-------------------------------|
| [1.1 Functions](https://politicalscience.github.io/math/1-1.html) | Dimensionality, Definition of Functions, Roots, Limits, Continuity |
| [1.2 Exponents and Logarithms](https://politicalscience.github.io/math/1-2.html) | Exponent Rules, Logarithm Rules |
| [1.3 Sum and Product Notation](https://politicalscience.github.io/math/1-3.html) | Summation Notation, Product Notation |

<br />

### Chapter 2: Single Variable Calculus

*Selected topics from Single Variable Calculus, usually equivalent to the US Calculus I & II, or AP Calculus AB & BC. Not all calculus topics are covered (l'hopital's rule and taylor series for example).*

| Lesson | Topics |
|---------------------------------------|---------------------------------|
| [2.1 Introduction to Derivatives](https://politicalscience.github.io/math/2-1.html) | Definition of Derivative, Calculating Simple Derivatives |
| [2.2 Chain Rule Derivatives](https://politicalscience.github.io/math/2-2.html) | Composite Functions, Chain Rule |
| [2.3 Exponent and Log Derivatives](https://politicalscience.github.io/math/2-3.html) | Derivatives of Exponential Functions, Derivatives of Logarithms |
| [2.4 Partial Derivatives](https://politicalscience.github.io/math/2-4.html) | Partial Derivatives, Application in Regression, Application in Economics |
| [2.5 Indefinite Integrals](https://politicalscience.github.io/math/2-5.html) | Indefinite Integrals, Calculating Integrals |
| [2.6 Definite Integrals](https://politicalscience.github.io/math/2-6.html) | Riemann Sum and Rieman Integral, Fundamental Theorem of Calculus |
| [2.7 Integrating by Substitution](https://politicalscience.github.io/math/2-7.html) | U-Subsitution |
| [2.8 Integrating by Parts](https://politicalscience.github.io/math/2-8.html) | Integration by Parts for Indefinite and Definite Integrals |

<br />

### Chapter 3: Optimisation

*Using calculus methods to optimise equations - useful in both Statistics (minimising error) and Game Theory (after all, game theory is about payoff/utility maximisation).*

| Lesson | Topics |
|------------------------------------|------------------------------------|
| [3.1 Maxima and Minima](https://politicalscience.github.io/math/3-1.html) | Slope and Concavity, Critical Points, Global and Local Maxima and Minima |
| [3.2 Unconstrained Optimisation](https://politicalscience.github.io/math/3-2.html) | Optimisation in Decision Theory, Optimisation in Linear Regression |
| 3.3 Constrained Optimisation | Equality Constraints, Langrangian Function |

<br />

### Chapter 4: Intro to Linear Algebra

*Statistics relies quite heavily on Linear Algebra, so it is useful to understand.*

| Lesson | Topics |
|------------------------------------|------------------------------------|
| [4.1 Vectors](https://politicalscience.github.io/math/4-1.html) | Introduction to Linear Algebra, Vectors and Scalars, Graphical Representation of Vectors |
| [4.2 Vector Algebra](https://politicalscience.github.io/math/4-2.html) | Vector Addition, Scalar Multiplication, Dot Product |
| [4.3 Matrices](https://politicalscience.github.io/math/4-3.html) | Introduction to Matrices, Types of Matrices |
| [4.4 Matrix Algebra](https://politicalscience.github.io/math/4-4.html) | Transpose, Addition and Subtraction, Scalar Mutliplication, Plain Multiplication, Kronecker Product |
| 4.5 Matrix Operators |  |
| 4.6 Properties |  |
| 4.7 OLS Regression |  |

<br />

### Chapter 5: Intro to Multivariate Calculus

*Useful for multivariate statistics and Game Theory.*

| Lesson                             | Topics |
|------------------------------------|--------|
| 5.1 Functions of Several Variables |        |
| 5.2 Further Partial Derivatives    |        |
| 5.3 Multidimensional Integrals     |        |

<br />

------------------------------------------------------------------------

[Political Science Academy Homepage](https://politicalscience.github.io)