---
title: "Maths for Political Science"
output: html_document
date: "2024-09-02"
---

```{=html}
<style type="text/css">
  body{
  font-size: 12pt;
  line-height: 150%;
  }
  .main-container {
  max-width: 800px !important;
  margin: auto;
  }
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Political Science Academy Homepage](https://politicalscience.github.io)

While most political scientists will not need to be math wizards, it is useful to have a baseline understanding of some math to help with the statistics and data science approaches commonly used in political science.This course covers some of the key topics in algebra, calculus, and linear algebra needed to understand the methods behind political science.

The point of this course is not meant to be a thorough explanation of math topics - it is instead to install practical skills which will be useful in research. Thus, I will not be going through many proofs of concepts.

<br />

**Prerequisites**: Algebra to the level of a typical secondary education.

Note: You don't need to study this course from beginning to end - you can focus on particular areas where you may struggle with.

<br />

### Chapter 1: Topics in Algebra

| Lesson                                                                                  | Topics                                                             |
|-----------------------------|-------------------------------------------|
| [**1.1 Introduction to Sets**](https://politicalscience.github.io/math/1-1.html)        | Definition of Sets, Set Notation, Set Operations                   |
| [**1.2 Functions**](https://politicalscience.github.io/math/1-2.html)                   | Dimensionality, Definition of Functions, Roots, Limits, Continuity |
| [**1.3 Exponents and Logarithms**](https://politicalscience.github.io/math/1-3.html)    | Exponent Rules, Logarithm Rules                                    |
| [**1.4 Sum and Production Notation**](https://politicalscience.github.io/math/1-4.html) | Summation Notation, Product Notation                               |

<br />

### Chapter 2: Single Variable Calculus

| Lesson                                                                                   | Topics                                                                   |
|-----------------------|-------------------------------------------------|
| [**2.1 Introduction to Derivatives**](https://politicalscience.github.io/math/2-1.html)  | Definition of Derivative, Calculating Simple Derivatives                 |
| [**2.2 Chain Rule Derivatives**](https://politicalscience.github.io/math/2-2.html)       | Composite Functions, Chain Rule                                          |
| [**2.3 Exponent and Log Derivatives**](https://politicalscience.github.io/math/2-3.html) | Derivatives of Exponential Functions, Derivatives of Logarithms          |
| [**2.4 Maxima and Minima**](https://politicalscience.github.io/math/2-4.html)            | Slope and Concavity, Critical Points, Global and Local Maxima and Minima |
| [**2.5 Partial Derivatives**](https://politicalscience.github.io/math/2-5.html)          | Partial Derivatives, Application in Regression, Application in Economics |

<br />

### Chapter 3: Optimisation

<br />

### Chapter 4: Linear Algebra

<br />

### Chapter 5: Multivariate Calculus

<br />

------------------------------------------------------------------------

[Political Science Academy Homepage](https://politicalscience.github.io)
