---
title: "Linear Regression Analysis"
subtitle: "Module 5 (Section 1: Core Statistical Methods)"
format:
    html:
        theme: flatly
        max-width: 800px
        toc: TRUE
        toc-depth: 3
        toc-location: left
        toc-title: Chapters
        toc-expand: TRUE
---

# Preface

Linear Regression is arguable the most essential tool in all of statistics. It is the dominant tool in finding relationships between variables, and it also serves as the framework for almost all advanced statistical methods and data science. This module is a rigorous analysis of the linear regression model, describing specification, estimation, assumptions, different types of explanatory variables, and different types of data.

[Prerequisites]{.underline}: Modules 1-4

------------------------------------------------------------------------

[Handbook Homepage](https://politicalscience.github.io)

# Chapter 1: Basics of Linear Regression

### 1.1: Introduction to the Linear Model

Before we start analysing the linear regression model, let us specific some notation

-   The response variable (dependent variable) is notated as $Y$. For this module, we will only explore models with one $Y$ variable

-   The explanatory variables are notated as $X$. Often, we will have more than one explanatory variable, so we will add subscripts $X_1, X_2, ..., X_k$. Sometimes, we will shorthand all $X$ variables into a vector $\overrightarrow{X} = (X_1, X_2, ... ,X_k)$

<br />

A [regression model]{.underline} is actually a specification of a conditional distribution of $Y$ given some values of $\overrightarrow{X}$. In more intuitive terms, it states the distribution of values that the response variable $Y$ will have depends on the value of the explanatory variables $\overrightarrow{X}$

-   For example, let us say $X$ is age and $Y$ is income. The regression model is a specification of the distribution of $Y$ income, at a specific age $X = x$.

-   I say distribution, because obviously, not every person with the same age has the same income - there is some probability distribution of incomes, given knowing someone's age.

<br />

[Linear Regerssion Models]{.underline} take the following form:

$$
E(Y|\overrightarrow{X}) = \alpha + \beta_1 X_1 + \beta_2 X_2 + ... + \beta_k X_k
$$

-   $E(Y|\overrightarrow{X})$ is the expected value of the conditional distribution of $Y$, given some $X$ - so essentially, the mean/expectation of the conditional distribution we just discussed.

-   $\beta_1, \beta_2, ... \beta_k$ are the regression coefficients, each attached to some $X$ variable. For simplicity, we can notate them as a vector $\overrightarrow{\beta} = (\beta_1, \beta_2, ..., \beta_k)$

-   Coefficient $\beta_j$ of explanatory variable $X_j$ describes the direction and magnitude of the relationship between $X_j$ and $Y$, holding all other $\overrightarrow{X}$ not $X_j$ constant.

-   $\alpha$, sometimes denoted $\beta_0$, is the constant or intercept term - where $\alpha = E(Y|\overrightarrow{X} = 0)$ - or in other words, $\alpha$ gives the prediction of $Y$ when all explanatory variables $\overrightarrow{X}$ are equal to 0.

<br />

Formally, to run a linear regression, response variable $Y$ should be continuous - have infinite possible numbers.

-   However, in reality, we often use linear regression on count $Y$, ordinal $Y$, and even binary $Y$, despite the fact that better regression techniques exist for these types of $Y$

For explanatory variables $\overrightarrow{X}$, there are no real restrictions. We will cover how to deal with different types of explanatory variables later in the module.