---
title: "Introduction and Static Games"
subtitle: "Module 9 (Section 2: Formal Mathematical Modelling)"
format:
    html:
        theme: sketchy
        max-width: 800px
        toc: TRUE
        toc-depth: 3
        toc-location: left
        toc-title: Chapters
        toc-expand: TRUE
---

# Preface

In political science, we are often interested in explaining the world around us. The world is incredibly complex - however, models, which make key simplifications, can make understanding the world around us much easier.

This module is an introduction to Formal Mathematical Modelling of political situations, often also called Game Theory or Formal Theory, focusing on the "simplest" type of model: static games.

[Prerequisites]{.underline}: Section 0: Essentials

<br />

------------------------------------------------------------------------

[Handbook Homepage](https://politicalscience.github.io)

# Chapter 1: Basics of Games

### 1.1: Game Theory and Mathematical Modelling

Building models is an exceptionally powerful tool in Political Science. The world is very very complex, especially in the social sciences, where human behaviour can be difficult to predict or anticipate.

Models make key simplifications of reality, often called assumptions, in order to teach us something about the world. A great example of a model is the standard street map on google maps. This street map is not a complete representation of the world - it doesn't show hills, it doesn't show the height of buildings, it doesn't show road markings. Most noticeably, it represents the spherical world on a flat surface. As you can see, it omits a lot of data on the real world.

Yet, despite omitting much of the real world, simple street maps are significantly better for driving navigation than, for example, a full 3D replica of the world. This is the power of models - through simplification, and only focusing on what we care about, it can help us learn something we did not know previously.

There are many different approaches to modelling in the social sciences.

1.  Decision theory: modelling how one individual, who aims to maximise his objective, makes his decisions
2.  Competitive equilibrium: price and quantities, as often seen in economics
3.  Game Theory: social interactions that are characterised by strategic interdependence

<br />

[Game Theory]{.underline} is the study of mathematical models of both conflict and cooperation between rational decision making. Essentially, we model situations where one person's decisions affect the other people's outcomes.

A few properties of game theory is as follows:

1.  Payoffs are interdependent - one person's actions affect other people's payoffs/gains
2.  There is common knowledge of the rules of the game - basically, everyone knows, that everyone knows, the "rules" of the game
3.  A player is rational - they aim to maximise their payoff/gain
4.  A player is aware of the other players, and predicts what other players will do, and will react to other players' decisions
5.  The optimal action of a player, depends on the beliefs of what others will do.

<br />

The key point about Game Theory, as I have repeated multiple times, is interdependence - where one person's actions affect other people's payoffs/gains. This is often called [strategic interaction]{.underline}. Here are a few examples of strategic interaction.

1.  In football, when a penalty taker is opposed to a goalie. The penalty taker wants to score, and will try to anticipate where the goalkeeper will dive. The Penalty taker tries to anticipate where the goalkeeper will dive, and shoot the other way. One persons' actions will affect the other person's response, and their payoffs
2.  Chess - the optimal move of a player, depends on how the other player moves. If the opponent plays a Sicilian defense, you have to adapt. When you move a piece, you have to think about how your opponent will respond.
3.  Businesses - you have to react to your competition. If you want to raise prices, you have to first consider how the competition will react. If the competition cuts prices, you have to decide how to react. However, often times, these occur at the same time - there is no time to read and react - you have to anticipate

There are also examples of non-strategic interaction, where game theory does not apply

1.  If there is only 1 player, then there is no strategic interaction
2.  If there is perfect competition in a market, there is no strategic interaction. This is because, in economics, perfect competition means that there are so many buyers and sellers, than any seller's decisions are negligible, so they are price takers, and cannot set their own prices. Since they are not effecting the market or each other, there is no strategic interaction.

<br />

Through creating mathematical models, we can predict how players will react in a political situation. WIth this insight, we can create causal hypothesis, which can be tested using statistical methods in section 1. Knowing how people we act in situations also helps policymakers design policy that encourages certain actions, and avoid counterproductive incentives and loopholes.

<br />

### 1.2: Structure of a Game

A game, as defined in game theory, is a situation where the actions of one person, noticeably affect the welfare of another. Game Theory assumes that a rational individual will try to predict what other players will do in response to their actions, and choose the actions that maximises their own utility/payoff given those predictions.

To explore games, we have to define the structure of a game, and some common notation. Here are a few core properties of games:

<br />

[The Players]{.underline}: These are the parties that make the relevant decisions.

-   They can be individuals, but also firms, politicians, parties, and so on.

<br />

[Strategies]{.underline}: a strategy is a [complete plan of action]{.underline}.

-   A player will have a set of possible decisions to take. If the game is repeated or the player has multiple turns, each turn to make a move will have a set of decisions they could take.

-   [A strategy is a complete plan of action, meaning that it contains how a player will behave in every possible scenario in that game]{.underline}.

-   For example, a strategy in chess, would be a plan of how you respond to every possible move in the game.

<br />

[Payoffs]{.underline}: are a measure of what a player achieves, given their objectives, for every possible outcome of the game. These are generally a number which is defined by some payoff function

-   So, any possible outcome (the result of any different set of actions by all players), will have a payoff associated with it, for each player

-   Payoffs aren't just money - they include everything a player values, such as compassion, non-monetary payment, happiness, etc.

-   Game theory assumes that players will always seek the highest payoff.

<br />

The [normal form representation]{.underline} of a game includes the players, all possible strategies, and all possible payoffs. The normal form, and all the information within it, is assumed to be [common knowledge]{.underline} - that all players know this information, and that they know others know this information

<br />

### 1.3: Types of Games

There are many types of games in game theory.

[Static Games]{.underline} are games where he players determine their actions simultaneously. This doesn't necessarily mean they move at the same time - rather, this means that they move, without knowing what strategy the other has chosen. Thus, players will need to anticipate their opponents strategies, and counter them with their move.

[Dynamic Games]{.underline} are games where players move in a sequence/order, such as chess. Since players do not move at the same time, they can observe the strategy the other has chosen, and react to that strategy.

<br />

[Zero-Sum Games]{.underline} are when players are in direct conflict with each other - one player's gain, comes directly from the expense of the other player(s). Basically, there must be winners and losers in a zero sum game.

[Non-Zero-Sum Games]{.underline} are when one player's gain, does not come strictly at the expense of their opponents. This often occurs when players have some interests in common. Thus, outcomes that benefit everybody are possible, but they do not always occur (as we will see later).

<br />

[One Shot Games]{.underline} are games that are only played once. Thus, since they only occur once, there is no concern about a player's reputation. Thus, people often act more ruthless in one-shot games.

[Repeated Games]{.underline} are played more than once. This gives players a opportunity to cultivate a reputation. It also allows other players to punish a player that "betrayed" them.

<br />

[Cooperative Games]{.underline} are when players are able to come to a [binding agreement]{.underline}. Binding is the important part here - it means that there is some third party (like police/courts) that can force players to act in accordance to the agreement, even if that means it is no longer in the interests of the player to keep the agreement.

[Non-Cooperative Games]{.underline} are when agreements between players cannot be enforced by a third party. That does not mean agreements are impossible - but, it means that as soon as an agreement becomes non-beneficial to one or more of the players, the players will break off that agreement.

<br />