---
title: "Game Theory and Political Economics"
subtitle: "Methods for Political Science: Notes and Guides on Quantitative Methods"
format:
    html:
        page-layout: article
        grid:
          sidebar-width: 300px
          body-width: 750px
          margin-width: 250px
          gutter-width: 2em
        fontsize: 12.5pt
        theme: yeti
        toc: TRUE
        toc-depth: 2
        toc-location: left
        toc-expand: true
        toc-title: "Game Theory and Political Economics"
        mainfont: "Computer Modern"
        title-block-banner: true
        classoption: fleqn
        html-math-method: katex
---

[Homepage](https://politicalscience.github.io)

# Overview

This is a full course on game theory, political economics, and the economic/mathematical modelling of political and social phenomena. This course will introduce how to build formal mathematical models of political and social situation, and how to evaluate these models.

This course is divided into 3 main parts. The first part introduces the essential game theory topics needed. The second part introduces applications of models in real-world research. The final part discusses more complex games and topics.

**Prerequisites**: I highly recommend one has a solid understanding of calculus and basic statistical theory. Specifically, I assume knowledge through the first part of the quantitative methods (for social scientists) course covering single variable calculus and introductory statistical theory.

<br />

[Homepage](https://politicalscience.github.io)

# Part 1: Game Theory and Economic Models

This part of the course will focus on techniques of causal estimation and causal inference, which is important in establishing causal relationships for social science research.

| Chapter                                                            | Topics Covered |
|---------------------------------|---------------------------------------|
| 1: Essential Microeconomic Theory and Introduction to Game Theory. |                |
| 2: Static Games and Pure Strategy Nash Equilibrium                 |                |
| 3: Mixed Strategy Nash Equilibrium                                 |                |
| 4: Downsian Spatial Model of Electoral Competition                 |                |
| 5: Further Spatial Models with Applications in Political Economics |                |
| 6: Dynamic Games and Subgame Perfect Nash Equilibria               |                |
| 7: Applications of Dynamic Games in Political Economics            |                |
| 8: Repeated Games and the Potential of Cooperation                 |                |
| 9: Incomplete and Imperfect Information                            |                |
| 10: Bayesian Games and Bayesian Perfect Equilibrium                |                |
| 11: Signalling Games                                               |                |

<br />

[Homepage](https://politicalscience.github.io)

# Part 2: Economic Models of Political Phenomena

This part of the course will implement many of the techniques we have learned into ground-breaking research and models. It is highly recommended that you have a strong econometrics background as well before taking this part.

| Chapter | Topics Covered |
|---------|----------------|
| 1: Hi   |                |

<br />

[Homepage](https://politicalscience.github.io)

# Part 3: Advanced Topics in Game Theory

This part of the course will discuss advanced topics in game theory.

| Chapter | Topics Covered |
|---------|----------------|
| 1: Hi   |                |

: <br />
