---
title: "Information and Elections: How does Fake News Affect Outcomes?"
subtitle: "Kevin's Guide to Political Science"
format:
    html:
        page-layout: article
        grid:
          sidebar-width: 350px
          body-width: 700px
          margin-width: 250px
          gutter-width: 2em
        fontsize: 12pt
        theme: default
        toc: TRUE
        toc-depth: 3
        toc-location: left
        toc-expand: true
        toc-title: "Table of Contents"
        mainfont: "Computer Modern"
        title-block-banner: true
        classoption: fleqn
        html-math-method: katex
editor: visual
---

# Introduction

In recent years, fake news has become a major topic of discussion in political science. The proliferation of social media has made the spread of misinformation incredibly prevalent.

But how does misinformation affect electoral outcomes?

One potential way is that it weakens the ability of citizens to understand the world around them. This can have pretty dramatic effects on electoral results.

The model below will explore how the presence of misinformation can actually cause people to vote against their own interests.

<br />

<br />

# Model of Information in Elections

Let us say we have an electorate of a country. This electorate consists of two groups $J \in \{C, E\}$, where $C$ represents the "commoners", and $E$ represents the elite.

-   Let us define the proportion of elites $E$ in the population as $\sigma$, and thus, the proportion of commoners $C$ is $1 - \sigma$.
-   We will restrict $\sigma < \frac{1}{2}$ as elites should make up less than a majority of the population.

<br />

Both groups $J \in \{C, E \}$ have their own state of the world, $\omega_J \in \{0, 1 \}$. This state of the world tells each group $J \in \{C, E \}$ what policy would be more beneficial to them.

-   So for example, $\omega_C = 0$ would indicate that the commoners would be better off with policy $0$. $\omega_C = 1$ would indicate that commoners would be better off with policy $1$.
-   Note - it is possible for $\omega_C = \omega_E$, or $\omega_C ≠ \omega_E$.

Each state of the world has a 50% chance of occurring:

$$
\begin{split}
Pr(\omega_E = 1) & = Pr(\omega_C = 1) = \frac{1}{2} \\
Pr(\omega_E = 0) & = Pr(\omega_C = 0) = \frac{1}{2}
\end{split}
$$

<br />

There are two candidates $K \in \{A, B \}$ that are competing for office. Each candidate wants to win the election.

Each candidate $K$ observes the state of both the elite world $\omega_E$ and the commoner world $\omega_C$. Then, each candidate $K$ chooses a policy $x_K \in \{0, 1 \}$.

-   For example, imagine the candidates are choosing between tarrifs or free trade, or pro vs. anti-immigration.

The chosen policy will determine how many citizens vote for them (see below for more details on citizens).

Candidates are only interested in winning the election - they do not care about what policy they choose. Thus, the payoff function of the candidates are:

$$
U_k = \begin{cases}
1 \quad \text{if they win the election} \\
0 \quad \text{if they lose the election}
\end{cases}, \quad K \in \{A, B\}
$$

<br />

Citizens (both elites and commoners) wish to choose a policy that aligns with the policy that is most beneficial to them, as determined by the state of the world $\omega_J$.

However, voters do not observe the state of the world $\omega_J$. They instead receive signals $s_{i,J}$ about the world $\omega_J$.

-   Imagine the signals are like reading the news, or doing research. This allows the citizens to learn more about what policies would benefit them (and learn more about their state of the world $\omega_J$).
-   For elites $J = E$, their signal $s_{i,E}$ is perfect informative - it always tells them the correct state of their world $\omega_E$ (so they know for 100% the policy they will benefit from). That means $s_{i,E} = \omega_E$.
-   For commoners, their signal is not as informative. $s_{i, C}$ is only correct $p$ probability of the time. Or in other worlds, $Pr(s_{i, C} = \omega_C) = p$. That implies the signal tells them the wrong state of the world $1-p$ of the time.
-   We will assume that the signal for commoners is somewhat informative, so $p > \frac{1}{2}$ (more than 50% chance the signal is correct).

<br />

Each voter $i$ also receives a valence shock $\delta_i$, which describes how much they favour candidate $A$ over $B$ for factors not regarding policy choice $x_K$ of either party.

-   $\delta_i$ is randomly selected from a uniform distribution $[-\bar\delta, \bar\delta]$. Negative values mean they do not favour $A$ over $B$ (so they like $B$ more). Positive values mean they favour $A$ over $B$.
-   We will assume $\delta_i$ is sufficiently small: $\delta < p$.

<br />

Each voter $i$ can vote for a candidate $K \in \{A, B\}$. Their utility of voting for either candidate $K$, is a combination of both if $K$'s chosen policy $x_K$ matches their preferred policy given by state of the world $\omega_J$, and the valence shock $\delta_i$.

$$
U_{i, J}(A) = \begin{cases}
1 + \delta \quad \text{if } x_A = \omega_J \\
0 + \delta \quad \text{if } x_A ≠ \omega_J
\end{cases}, \quad J \in \{C, E \}
$$

$$
U_{i, J}(B) = \begin{cases}
1 - \delta \quad \text{if } x_B = \omega_J \\
0 - \delta \quad \text{if } x_B ≠ \omega_J
\end{cases}, \quad J \in \{C, E \}
$$

<br />

The game has the following timing:

1.  Nature draws the states of the world $\omega_E, \omega_C \in \{0, 1\}$.
2.  Candidates $A$ and $B$ see both $\omega_E$ and $\omega_C$. Each citizen $i$ in group $J$ receives a signal $s_{i, J} \in \{0, 1\}$.
3.  Candidates $A$ and $B$ simultaneously choose policy $x_A, x_B \in \{0, 1\}$.
4.  All citizens observe their valence shock $\delta_i$.
5.  All citizens simultaneously vote for $A$ or $B$. The candidate with the most votes wins.

<br />

<br />

# Equilibrium

I will present a proposition regarding an equilibrium to the game. We will then provide a proof to the proposition.

::: callout-important
## Proposition

There exists an equilibrium in which both candidates match the commoner's state of the world $x_A = x_B = \omega_C$, if and only if $\sigma + (1- \sigma)(1-p) ≤ \frac{1}{2}$.
:::

This proposition implies that there exists no profitable deviation for any player, if and only if $\sigma + (1- \sigma)(1-p) ≤ \frac{1}{2}$.

<br />

Let us do a **proof by contradiction**. Let us assume that there is a profitable deviation from $x_A = x_B = \omega_C$ for at least one player, given $\sigma + (1- \sigma)(1-p) ≤ \frac{1}{2}$.

<br />

First, let us calculate the probability of winning the election for either party at $x_A = x_B = \omega_C$.

-   The voters will see that both parties are proposing the same platform $x_A = x_B$.
-   Thus, voters (no matter their signal) are indifferent to the two parties platforms, since the parties platforms are identical.
-   Thus, the choice of who to vote for, for all voters $i$, will depend on their valence shock $\delta_i$.
-   Recall that $\delta_i$ is randomly selected from uniform distribution $[-\bar{\delta}, \bar{\delta}]$. This implies that $E[\delta_i] = 0$, and 50% of drawn valence shocks will be positive, and 50% will be negative. Thus, an equal amount of voters will favour $A$ to $B$ compared to favouring $B$ to $A$.
-   Thus, after voters vote for their preferred candidate based on valence $\delta_i$, both candidates will receive the same amount of votes (tie).
-   This means both candidates have 50% probability of winning the election.

<br />

No profitable deviation exists for any voter in this scenario, given they are already voting for who they prefer based on $\delta_i$. Thus, any profitable deviation must come from the candidates.

Thus, for a profitable deviation for either candidate to exist, they will have to have a more than 50% chance of winning the election (which implies they have to win the election, since 50% is a tie, and there is nothing between 50 - 100%).

<br />

Now, let us assume one party $K \in \{A, B \}$ deviates away from $x_A = x_B = \omega_C$. I will denote the non-deviating party as $-K$. That will mean $x_K ≠ x_{-K}$, and imply that $x_K ≠ \omega_C$, and $x_{-k} = \omega_C$.

We have two potential worlds for this deviation. One where $\omega_C = \omega_E$, and one where $\omega_C ≠ \omega_E$. Let us test both worlds.

<br />

**Case 1:** $\omega_C = \omega_E$:

In this case, we know $\omega_C = \omega_E = x_{-K}$, and $x_K$ is not equal to any of them. Who will the voters vote for?

We know that for the elites $E$, who make up $\sigma$ proportion of the population, have a perfectly informative signal $s_{i, E}$. Thus, all elites know $\omega_E$, and will vote for $-K$ since $x_{-k} = \omega_E$. Thus, $-K$ picks up $\sigma$ proportion of votes.

<br />

For the commoners, who make up $1-\sigma$ of the population, have a signal $s_{i,C}$ that is only correct $p$ of the time, so $p$ proportion of commoners receive the correct signal, and $1-p$ proportion of commoners receive the wrong signal.

With the signal, both groups (wrong and correct) signal can update the prior beliefs on the state of the world. Remember, the prior (known to all) is that each state of the world has 50% chance of occuring.

<br />

Let us pretend the real state of the world $\omega_C = a$. Let us define the wrong state of the world as $b$. For the $p$ proportion of commoners who received the correct signal, their belief that $\omega_C = a$ is updated to the posterior using Bayes' rule:

$$
\begin{split}
& P(\omega_C = a | s_{i,C} = a) \\
&= \frac{P (s_{i,C} = a|\omega_C = a)P(\omega_C = a)}{P (s_{i,C} = a|\omega_C = a)P(\omega_C = a)+P (s_{i,C} = b|\omega_C = a)P(\omega_C = b)} \\
& = \frac{(p)(\frac{1}{2})}{p(\frac{1}{2}) + (1-p)(\frac{1}{2})} \\
& = p
\end{split}
$$

We know $p>\frac{1}{2}$ (given by the problem), so that means that the proportion $p$ of commoners who received the correct signal, believe that the state of the $\omega_c = a$ with more than 50% of probability (and $a$ is indeed the true state of the world $\omega_C$.

-   Thus, this group will vote for $-K$, and this group accounts for $(1-\sigma)p$ proportion of total votes.

Now, for the $1-p$ proportion of commoners who received the wrong signal, their belief $\omega_C = a$ can also be updated to the posterior using Bayes' rule:

$$
\begin{split}
& P(\omega_C = a | s_{i,C} = b) \\
&= \frac{P (s_{i,C} = b|\omega_C = a)P(\omega_C = a)}{P (s_{i,C} = a|\omega_C = a)P(\omega_C = a)+P (s_{i,C} = b|\omega_C = a)P(\omega_C = b)} \\
& = \frac{(1-p)(\frac{1}{2})}{p(\frac{1}{2}) + (1-p)(\frac{1}{2})} \\
& = 1-p
\end{split}
$$

We know $p>\frac{1}{2}$ (given by the problem), so that means $1- p ≤ \frac{1}{2}$. Thus, the proportion $1-p$ of commoners who received the wrong signal, believe that the state of the $\omega_c = a$ with less than 50% of probability (and $a$ is indeed the true state of the world $\omega_C$). Thus, they actually believe more that the state of the world is the wrong $b$.

-   Thus, this group will vote for $K$, and this group accounts for $(1- \sigma)(1-p)$ proportion of total votes.

<br />

Thus, tallying up the votes, we get:

-   $K$ (candidate that has deviated): $(1-\sigma)(1-p)$ votes.
-   $-K$: $\sigma + (1-\sigma)p$ votes.

For this to be a profitable deviation for candidate $K$, they must win the election. To win an election, you must win more than $\frac{1}{2}$ of votes. Thus, for this to be a profitable deviation:

$$
(1-\sigma)(1-p) > \frac{1}{2}
$$

This is actually impossible - even if $\sigma = 0$, we know $p > \frac{1}{2}$ (given), so this statement above will never be true. Thus, no profitable deviation exists in this case where $\omega_C = \omega_E$.

<br />

**Case 2:** $\omega_C ≠ \omega_E$:

In this case, we know $\omega_C = x_{-K}$, and $x_K = \omega_E$. Who will the voters vote for?

We know that for the elites $E$, who make up $\sigma$ proportion of the population, have a perfectly informative signal $s_{i, E}$. Thus, all elites know $\omega_E$, and will vote for $K$ since $x_{K} = \omega_E$. Thus, $K$ picks up $\sigma$ proportion of votes.

<br />

For the commoners, who make up $1-\sigma$ of the population, have a signal $s_{i,C}$ that is only correct $p$ of the time, so $p$ proportion of commoners receive the correct signal, and $1-p$ proportion of commoners receive the wrong signal.

With the signal, both groups (wrong and correct) signal can update the prior beliefs on the state of the world. Remember, the prior (known to all) is that each state of the world has 50% chance of occuring.

<br />

Let us pretend the real state of the world $\omega_C = a$. Let us define the wrong state of the world as $b$. For the $p$ proportion of commoners who received the correct signal, their belief that $\omega_C = a$ is updated to the posterior using Bayes' rule:

$$
\begin{split}
& P(\omega_C = a | s_{i,C} = a) \\
&= \frac{P (s_{i,C} = a|\omega_C = a)P(\omega_C = a)}{P (s_{i,C} = a|\omega_C = a)P(\omega_C = a)+Pr (s_{i,C} = b|\omega_C = a)P(\omega_C = b)} \\
& = \frac{(p)(\frac{1}{2})}{p(\frac{1}{2}) + (1-p)(\frac{1}{2})} \\
& = p
\end{split}
$$

We know $p>\frac{1}{2}$ (given by the problem), so that means that the proportion $p$ of commoners who received the correct signal, believe that the state of the $\omega_c = a$ with more than 50% of probability (and $a$ is indeed the true state of the world $\omega_C$.

-   Thus, this group will vote for $-K$, and this group accounts for $(1-\sigma)p$ proportion of total votes.

Now, for the $1-p$ proportion of commoners who received the wrong signal, their belief $\omega_C = a$ can also be updated to the posterior using Bayes' rule:

$$
\begin{split}
& P(\omega_C = a | s_{i,C} = b) \\
&= \frac{P (s_{i,C} = b|\omega_C = a)P(\omega_C = a)}{P (s_{i,C} = a|\omega_C = a)P(\omega_C = a)+P (s_{i,C} = b|\omega_C = a)P(\omega_C = b)} \\
& = \frac{(1-p)(\frac{1}{2})}{p(\frac{1}{2}) + (1-p)(\frac{1}{2})} \\
& = 1-p
\end{split}
$$

We know $p>\frac{1}{2}$ (given by the problem), so that means $1- p ≤ \frac{1}{2}$. Thus, the proportion $1-p$ of commoners who received the wrong signal, believe that the state of the $\omega_c = a$ with less than 50% of probability (and $a$ is indeed the true state of the world $\omega_C$). Thus, they actually believe more that the state of the world is the wrong $b$.

-   Thus, this group will vote for $K$, and this group accounts for $(1- \sigma)(1-p)$ proportion of total votes.

<br />

Thus, tallying up the votes, we get:

-   $K$ (candidate that has deviated): $\sigma + (1-\sigma)(1-p)$ votes.
-   $-K$: $(1-\sigma)p$ votes.

For this to be a profitable deviation for candidate $K$, they must win the election. To win an election, you must win more than $\frac{1}{2}$ of votes. Thus, for this to be a profitable deviation:

$$
\sigma + (1-\sigma)(1-p) > \frac{1}{2}
$$

Remember our assumption for our proof by contradiction from earlier:

> Let us do a proof by contradiction. Let us assume that there is a profitable deviation from $x_A = x_B = \omega_C$ for at least one player, given $\sigma + (1- \sigma)(1-p) ≤ \frac{1}{2}$.

Our conclusion for case 2 directly contradicts this. There is no profitable deviation by our original assumption.

Thus, we have proven by contradiction, our original proposition.

::: callout-important
## Proven Proposition

There exists an equilibrium in which both candidates match the commoner's state of the world $x_A = x_B = \omega_C$, if and only if $\sigma + (1- \sigma)(1-p) ≤ \frac{1}{2}$.
:::

<br />

<br />

# Interpretation of the Result

So we have proven that there exists an equilibrium in which both candidates match the commoner's state of the world $x_A = x_B = \omega_C$, if and only if $\sigma + (1- \sigma)(1-p) ≤ \frac{1}{2}$.

What does this mean in terms of fake news impacting elections?

Well, first of all, what does an equilibrium at $x_A = x_B = \omega_C$ mean?

-   This means that both parties are converging to the most beneficial policy for the common voter.
-   This implies that there is an equilibrium where parties want to help the common voter achieve their most beneficial policy.

However, this is only an equilibria when $\sigma + (1- \sigma)(1-p) ≤ \frac{1}{2}$. If this is not the case, then a party will profitable deviate to the preference of the elite voters, and win the election.

-   This will mean the commoners, who make up the majority of the population, will not get their most beneficial policy.

<br />

So, when does the condition $\sigma + (1- \sigma)(1-p) ≤ \frac{1}{2}$ get violated? We can quickly see by the equation, that this is dependent on two variables, $\sigma$ and $p$:

-   If $\sigma$ is very large, then this condition is violated (and thus, one party will deviate to the elites preferences, and win the election).
-   If $p$ is very small, then this condition is violated (and thus, one party will deviate to the elites preferences, and win the election).

We are not to concerned with $\sigma$, since most countries have very small elites. Let us focus on $p$.

<br />

What is $p$? $p$ is the probability that the signal $s_{i,C}$ to the commoners is correctly telling them what policy would benefit them the most.

In the real world, $s_{i,C}$ would be the common people reading the news, researching politics, in order to understand what policies would best benefit them.

Thus, $p$ is the probability that the voters are getting the [correct]{.underline} information on what policies will benefit them.

If fake news is very present in a society, the signal $s_{i,C}$ of what the most benefical policy for the commoners is becomes much more muddy. Thus, $p$ drops.

Thus, the increase of fake news decreases the accuracy of the signal, decreasing $p$, and actually causes a party to deviate to the elite's preferred policy and win the election.

As a result, this model indicates how misinformation can actually result in common people losing power to elite forces in a country.
