---
title: "1.2 Key Conepts in Probability"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 1.2, Introductory Statistical Inference"
---

[Course Homepage](https://politicalscience.github.io/math)

## Table of Contents {#contents}

1.  [Axioms of Probability](#axioms)
2.  [Basic Rules of Probability](#rules)
3.  [Independence](#independence)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Axioms of Probability {#axioms}

Probability is a model of uncertainty.

Many events and outcomes that we study are random, and thus, the outcomes of these events are random.

Many methods in political science rely on randomness. For example, most statistical methods rely on the assumption of random samples to represent the population. Other uses of randomness include Bayesian games in Game Theory.

<br />

**Kolmogrov's axioms**, also known as the Axioms of Probabiltiy, ad the fundamental backbones of probability theory. The three axioms are as follows:

1.  For any event $A$, $Pr(A) ≥ 0$
    -   In more intuitive terms, the probability of an event is a non-negative real number.
2.  $Pr(S) = 1$ where $S$ is the sample space of all possible events.
    -   In more intuitive terms, if $S$ is all possible events, then $Pr(S)=1$ because something has to happen (anything that could happen is contained within $S$)
3.  For any sequence of mutually exclusive events $A_1, A_2...$, $Pr \left( \bigcup\limits_{i=1}^{k} A_i \right) = \sum\limits_{i=1}^{k}Pr(A_i)$
    -   More intuitively, if we have a group of mutually exclusive events, the probability of the union (combination) of these events occurring, is the same as the sum of the individual probabilities of these exclusive events.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Basic Rules of Probability {#rules}

Using the three previously described axioms, these are the most useful rules of probability:

1.  $Pr(\varnothing)=0$
    -   The probability of nothing occurring is 0
2.  For any event $A$, $0 ≤ Pr(A) ≤ 1)$
    -   The probability of any event must be between 0 and 1
3.  $Pr(A^C) = 1 - Pr(A)$
    -   The probability of not-A occuring, is the same as 1 minus the probability of A
    -   Since total probability of all possibilities must add up to 1, so A + not-A must be 1, as not-A includes all other possibilities aside from A
4.  If $A \subset B$, then $Pr(A) ≤ Pr(B)$
    -   If A is a subset of B, then the probability of A must be less than B.
    -   This matches very closely with one of the rules of sets we previously discussed.
5.  For any 2 events $A$ and $B$, $Pr(A \cup B) = Pr(A) + Pr(B) - Pr(A \cap B)$
    -   Basically, the combined probability of events $A$ and $B$ occuring are the individual probabilities added together, then subtracting the intersection of the two probabilities.
    -   Why? Well when we add $Pr(A)$ and $Pr(B)$, the events that fit into both sets are counted twice. So, we have to subtract the intersection once to avoid double-counting.
6.  For any set of events (don't have to be mutually exclusive), the following must be true: $Pr \left( \bigcup\limits_{i=1}^{k} A_i \right) ≤ \sum\limits_{i=1}^{k}Pr(A_i)$
    -   Why? We previously established in the axioms, that for mutually exclusive events, $Pr \left( \bigcup\limits_{i=1}^{k} A_i \right) = \sum\limits_{i=1}^{k}Pr(A_i)$
    -   If we have some non-mutually-exclusive events, that means there are some intersections between the event probabilities.
    -   This means that the sum of the individual probabilities of the events should be over-counting the intersection (see rule 5), and thus, the sum of the individual probabilities should be higher.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)

# Independence {#independence}

Independence means that the occurrence of one event $A$, does not affect the probability of the occurrence of event $B$. If this criteria is met, then the events $A$ and $B$ are independent.

<br />

An example of independence is the following scenario.

-   Pretend we have two events: Event $A$ is flipping a coin and getting heads, and event $B$ is rolling a 6-sided dice and getting 5.

-   $Pr(B)$, The probability of rolling a 5 on a 6-sided dice, is $1/6$

-   If event $A$ occurs and we see the coin lands on heads, the probability of rolling a 5 on a 6-sided dice is still $1/6$

-   Event $A$ occurring did not change the probability of event $B$. Thus, these two events are independent.

<br />

An example of a non-independent set of events is the following scenario:

-   Imagine we have a box with 5 apples and 4 oranges.

-   Event $A$ is when we select an apple and eat it, and event $B$ is when we select an orange and eat it.

-   The probability initially, of event $B$, is $Pr(B) = 4/9$, since there are 4 oranges out of 9 total objects.

-   However, if event $A$ were to occur, then there would only be 8 objects remaining. Then, the probability of selecting an orange would now be $Pr(B) = 4/8$

-   Notice how the occurrence of $A$, changed the probability of B $Pr(B)$ from $4/9$ to $4/8$. This is an example of **non-independent** events.

<br />

Independence is important for Political Science. Independence is often an assumption in many of our models, and if that assumption is not met, we may have to do additional work to ensure our models are accurate.

<br />

#### Properties of Independent Events

If $A$ and $B$ are independent, then there are a few properties that apply:

1.  $Pr(A|B) = Pr(A)$ and $Pr(B|A) = Pr(B)$
    -   $Pr(A|B)$ means the probability of A, given B occurs
    -   Since $A$ and $B$ are independent events, $B$ occurring does not change the probability of $A$ occurring.
    -   Vice versa for $Pr(B)$
2.  $Pr(A \cap B) = Pr(A) * Pr(B)$
    -   The probability of two independent events both occurring, is the product of the individual probabilities
3.  $Pr \left( \bigcap\limits_{i=1}^{k} A_i\right) = \prod\limits_{i=1}^{k} Pr(A_i)$
    -   This is just property #2 restated for more than 2 events. Essentially, the probability of multiple independent events occurring, is the product of each event's individual probability.
4.  If A and B are mutually exclusive, they are not independent
    -   $A$ and $B$ being mutually exclusive means that if one occurred, the other cannot.
    -   This is because, if $A$ occurred, we know that $B$ cannot occur. Thus, knowing $A$ changes the probability of $B$.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/math)