---
title: "1.3 Counting"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 1.3, Introductory Statistical Inference"
---

[Course Homepage](https://politicalscience.github.io/stats)

## Table of Contents {#contents}

1.  [Fundamental Counting Principle](#counting)
2.  [Permutations](#permutations)
3.  [Combinations](#combinations)
4.  [Sampling Counting](#sampling)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Fundamental Counting Principle {#counting}

Counting is important, as to figure out probabilities, we will need to know how many total possibilities there are, and how many possibilities fit the criteria for our event.

<br />

The Fundamental Counting Principle, often called the multiplication rule, is the way we find out how many possibilities can exist from a series of choices.

The theorem states that if there are $a$ number of ways of doing something, and $b$ number ways of doing another thing, then there are $a*b$ ways of performing both actions.

-   This can be extended to how every many amounts of "things" you want to do - they are all multiplied.

<br />

For example, let us say you are planning a vacation:

-   You have 15 different hotels you could chose from

-   You have 6 different rental cars you could rent

-   You have 8 different flights you could take.

Thus, the total possible amount of different vacations is $15*6*8=720$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Permutations {#permutations}

Permutations and [Combinations](#combinations) are different way of counting depending on if order matters.

-   For example, if you have a salad with lettuce, olives, and chicken, that is the same as having a salad with olives, chicken, and lettuce. The actual order of our ingredients doesn't matter.

-   However, if you have a password of "1234", you can't input the password "2341" and expect it to work. Order matters here.

<br />

Combinations and Permutations, by default, assume sampling without replacement.

-   This means, once one object has been chosen, that object cannot be chosen again.

-   For example, if we are looking to give 3 people out of 10 some money, if it is sampling without replacement, we cannot give the same person money multiple times.

<br />

When order doesn't matter, we use Combinations to count.

When order does matter, we use Permutations to count.

<br />

To see more on combinations, go to the section on [combinations without replacement](#combinations).

<br />

#### Permutations

Permutations are used in sampling without replacement, when order does matter. For more information, see the [combinations](#combinations) section.

Perumations take the following formula:

$$
_nP_r = \frac{n!}{(n-r)!}
$$

-   Where $n$ is the number of choices

-   Where $r$ is the number of choices we are selection.

<br />

#### Example

We have 8 competitors in a race, and have to select 3 for gold, silver, and bronze (order matters). How many ways are there to do so?

-   Order matters here - why? Well, Gold for player 1, Silver for player 2, and Bronze for player 3, is a different outcome than Gold for player 2, Silver for player 3, and Bronze for player 1.

Thus, we use permutations for this example.

<br />

Let us first count the possibilities in a more intuitive way, utilising the [fundamental principle of counting](#counting):

-   We originally have 8 competitors, so we have 8 options for the gold.

-   To chose the silver medal, since one of the competitors already has the gold, we only have 7 options remaining.

-   To chose the bronze medal, since two of the competitors already have the gold and silver, we only have 6 options remaining.

Thus, the fundamental principle of counting says that there are $8*7*6 = 336$ ways to do so.

<br />

But, you might be like, $8*7*6$ looks very different than the formula $_nP_r = \frac{n!}{(n-r)!}$ for permutations we have above.

<br />

Well, actually no - the formula produces the same answer!

-   We know that there are 8 competitors, so the number of choices is $n = 8$

-   We are selecting 3 medals (in order), so we use a permutation with $r = 3$

<br />

Now, let us plug it in to the equation:

$$
_nP_r = \frac{n!}{(n-r)!}
$$

$$
= \frac{8!}{(8-3)!} = \frac{8!}{5!}
$$

$$
= \frac{8*7*6*5*4*3*2*1}{5*4*3*2*1}
$$

$$
= 8*7*6
$$

So, we do indeed get the same answer as the fundamental counting theory method we did above.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Combinations {#combinations}

Combinations are used when sampling with replacement, and order doesn't matter. They take the following formula:

$$
_nC_r = {n \choose r} = \frac{n!}{(n-r)!*r!}
$$

-   Where $n$ is the number of choices

-   Where $r$ is the number of choices we are selecting

<br />

#### Example

We want to select 3 books, from a bookshelf of 8 books. How many ways are there to do so?

-   Order doesn't matter here - why? Well, selecting the 3 books of $A, B, C$, is the same as the 3 books of $C, B, A$. Order doesn't matter, we just need 3 books.

Thus, we use a combination here.

<br />

Let us first count the possibilities in a more intuitive way, utilising the [fundamental principle of counting](#counting):

-   We have 8 choices for selecting the first book.

-   Since we have already selected and removed a book, we only have 7 choices for the second book

-   Since we have already selected and removed 2 books, we only have 6 choices for the third book.

<br />

So far, things look very similar to [permutations](#permutations). But, there is an issue with doing the simple product of possibilities $8*7*6$ that we did with permutations:

-   We are actually overcounting the possibilities - because order doesn't matter, while our above equation considers each different order a unique outcome.

-   Thus, we need to account for this overcounting.

<br />

How do we account for this overcounting?

-   Well, since we are selecting 3 books, we know that there are $3*2*1$ ways to arrange them.

-   Since for position 1, we can choose any of the 3 books. For position 2, only 2 of those books remain. For position 3, only one book remains.

So, we get the number of possibilities $= \frac{8*7*6}{3*2*1}$

<br />

But, you might be like, $\frac{8*7*6}{3*2*1}$ looks very different than the formula $_nC_r = \frac{n!}{(n-r)!*r!}$ for combinations we have above.

<br />

Well, actually no - the formula produces the same answer!

-   We know that there are 8 possible books, so the number of choices is $n = 8$

-   We are selecting 3 books, so we use a combination with $r = 3$

<br />

Now, let us plug it in to the equation:

$$
_nC_r = \frac{n!}{(n-r)!*r!}
$$

$$
= \frac{8!}{(8-3)!*3!} = \frac{8!}{5!} * \frac{1}{3!}
$$

$$
= \frac{8*7*6*5*4*3*2*1}{5*4*3*2*1} * \frac{1}{3*2*1}
$$

$$
=8*7*6 * \frac{1}{3*2*1} = \frac{8*7*6}{3*2*1}
$$

So, we do indeed get the same answer as the fundamental counting theory method we did above.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Sampling Counting {#sampling}

The below table summarises the counting methods we have previously introduced. See [Permutations](#permutations) and [Combinations](#combinations) for more information.

<br />

If there are $n$ total objects, and we select $k$ of them, how many different outcomes are possible:

|   | Order Matters | Order Doesn't Matter |
|------------------------|:----------------------:|:----------------------:|
| **With Replacement** | $n^k$ | $_{n+k-1} C _k = \frac{(n+k-1)!}{(n-1)!k!}$ |
| **Without Replacement** | $_n P _r = \frac{n!}{(n-k)!}$ | $_n C _k = \frac{n!}{(n-k)!k!}$ |

: <br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)