---
title: "1.4 Conditional Probability and Bayes' Law"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 1.4, Introductory Statistical Inference"
---

[Course Homepage](https://politicalscience.github.io/stats)

## Table of Contents {#contents}

1.  [Conditional Probability](#conditional)
2.  [Multiplicative Law](#multiplicative)
3.  [Bayes' Rule](#bayes)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Conditional Probability {#conditional}

Conditional Probability describes the probability of an event, given that another event has occurred. Conditional probability takes the following form:

$$
Pr(A|B) = \frac{Pr(A \cap B)}{Pr(B)}
$$

-   $Pr(A|B)$ is the probability of event $A$ occurring, given event $B$ has occurred.

-   $Pr(A \cap B)$ is the probability that an event that is in the intersection of $A$ and $B$ occurs - i.e., when event $A$ also falls into event $B$

-   $Pr(B)$ is the probability that event B occurs. It is in the denominator, since we are assuming it already has occurred, and we are concerned with $Pr(A \cap B)$ after $Pr(B)$ has occurred.

<br />

#### Example

We roll a 6-sided dice. The outcome is (somehow) known to be an odd-number. What is the probability of the outcome being 1?

Let us first define terms in the framework of conditional probability

-   Event $A$ is rolling a 1, so $Pr(A)$ is the probability of rolling a 1.

-   Event $B$ is rolling an odd number, so $Pr(B)$ is the probability of rolling an odd number.

-   $Pr(A \cap B)$ is the probability that the outcome is in both $A$ and $B$, which means the outcome must be both odd, and the number 1.

-   $Pr(A|B)$ is the probability of $A$ occurring given $B$ occurred, the premise of the question.

<br />

Now, let us find the probability of the relevant terms:

-   $Pr(A \cap B) = 1/6$

    -   The total number of outcomes is 6, as it is a 6 sided die.

    -   The intersection of $B$ the outcome of odd number, and $A$ the outcome of #1, is just $A$ the outcome of #1, since the other odd numbers don't fit into category $A$ thus wouldn't be in the intersection. Thus, the numerator is 1.

-   $Pr(B) = 1/2$

    -   The total number of outcomes is 6, as it is a 6 sided die.

    -   $B$, the outcome of being an odd-number, will have a numerator of 3, as there are 3 odd numbers between 1 and 6 inclusive.

    -   We can simplify $3/6$ to $1/2$

<br />

Now, let us fit this into the framework of Conditional Probability:

$$
Pr(A|B) = \frac{Pr(A \cap B)}{Pr(B)}
$$

$$
Pr(A|B) = \frac{1/6}{1/2} = \frac{1}{6} * \frac{2}{1}
$$

$$
Pr(A|B) = \frac{1}{3}
$$

This makes sense, as there are 3 odd numbers, and #1 is one of the 3.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Multiplicative Law {#multiplicative}

The multiplicative law of probability illustrates the probability of the intersection of two events $A$ and $B$ as follows:

$$
Pr(A \cap B) = Pr(A) * Pr (B|A) = Pr(B) * Pr(A|B)
$$

<br />

How do we know this? Well, we can derive this from the definition of [conditional probability](#conditional) by solving for $Pr(A \cap B)$:

$$
Pr(A|B) = \frac{Pr(A \cap B)}{Pr(B)}
$$

$$
Pr(A \cap B) = Pr(A|B) * Pr(B)
$$

<br />

That proves the $Pr(A \cap B) =  Pr(B) * Pr(A|B)$ part of the equation. But, we still have the $= Pr(A) * Pr (B|A)$ part to prove.

<br />

Let us first find the conditional probability of $B$ given $A$, once again using the definition of conditional probability, but renaming set $A$ as $B$ and $B$ as $A$.

$$
Pr(B|A) = \frac{Pr(B \cap A)}{Pr(A)}
$$

$$
Pr(B \cap A) = Pr(B|A) * Pr(A)
$$

<br />

So we have established the following two truths:

$$
Pr(A \cap B) = Pr(A|B) * Pr(B)
$$

$$
Pr(B \cap A) = Pr(B|A) * Pr(A)
$$

We also know from the lesson on [sets](https://politicalscience.github.io/stats/1-1.html), that the commutative property states:

$$
A \cap B = B \cap A
$$

<br />

Thus, $Pr(A \cap B) = Pr(B \cap A)$, and thus:

$$
Pr(A|B) * Pr(B) = Pr(B|A) * Pr(A)
$$

Who both equal:

$$
=Pr(A \cap B)=Pr(B \cap A)
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Bayes' Rule {#bayes}

So, in the section on [conditional probability](#conditional), we have established that:

$$
Pr(A|B) = \frac{Pr(A \cap B)}{Pr(B)}
$$

<br />

And, in the section on the [multiplicative law](#multiplicative), we have established that:

$$
Pr(A \cap B) = Pr(A) * Pr (B|A) = Pr(B) * Pr(A|B)
$$

<br />

So lets put these two ideas together. Let us substitution the multiplicative law into the conditional probability definition.

This gives us Bayes' Rule (also called Bayes' Theorem or Bayes' Law):

$$
Pr(A|B)=\frac{Pr(B|A)*Pr(A)}{Pr(B)}
$$

<br />

Each part of Bayes' Rule has its own name:

-   $Pr(A|B)$ is the conditional probability.

-   $Pr(B|A)$ is called the posterior probability

-   $Pr(A)$ is the prior probability

-   $Pr(B)$ is the marginal probability

<br />

In many applications of Bayes' rule, such as Bayesian Inference (used in many techniques including the machine learning technique of Naive Bayes Classifier), the numerator $P(B)$ is constant.

So, especially when $P(B)$ is difficult to calculate, you will often see the following equation:

$$
P(A|B) \propto Pr(B|A)*Pr(A)
$$

Where $\propto$ indicates "proportional to".

<br />

#### Extensions:

Sometimes, $P(B)$ is not obvious. We can rewrite the denominator $P(B)$ in the following ways:

<br />

If the event $A$ only has two states (binary, example - yes/no, off/on, etc.), then Bayes' rule can also be written as:

$$
P(A|B) = \frac{Pr(B|A)*Pr(A)}{Pr(B|A)Pr(A)+Pr(B|A^C)Pr(A^C)}
$$

<br />

In the event $A$ has $k$ number of states, then Bayes' rule can also be written as, if we are interested in the outcome category $i$ of event $A$:

$$
Pr(A_i|B) = \frac{Pr(B|A_i)*Pr(A_i)}{\sum\limits_{j=1}^k Pr(B|A_j)Pr(A_j)}
$$

<br />

How did we get these? The law of total probability, which I will not discuss in this lesson, but provides a framework for rewriting the denominator of Bayes' Rule.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)