---
title: "2.1 Discrete Distributions"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 2.1, Introductory Statistical Inference"
---

[Course Homepage](https://politicalscience.github.io/stats)

## Table of Contents {#contents}

1.  [Discrete Random Variable](#discrete)
2.  [Probability Mass Function](#mass)
3.  [Cumulative Density Function](#density)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Discrete Random Variable {#discrete}

**Randomness** indicates that there is some probability that an event will occur, and it is not for-sure going to happen (deterministic).

<br />

A **random variable** is a variable that describes unobserved events. These unobserved events have some randomness - a probability to occur, but they have not yet happened, so it is not deterministic.

For example, if you flip a coin 10 times, and count the number of heads:

-   Its possible to get 5 heads, or 6 heads, or 4 heads, or any amount. We are not sure of what will happen.

-   But, there are probabilities associated with each event.

<br />

**Discrete Random Variables** are random variables, whose outcomes can only assume a finite, or countable infinite number of distinct values:

-   So, there are distinct outcomes (like categories) that can occur, rather than all real numbers.

-   Example: the number of wars per year (only integers that are countable)

-   Example: Heads or tails (only 2 distinct category), or number of heads or tails from a certain number of spins (only integers that are countable).

<br />

The distinction between discrete random variables and continuous random variables will be illustrated in the [next lecture](https://politicalscience.github.io/stats/2-2.html).

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Probability Mass Function {#mass}

A Probability Mass Function $p(y)$ is used to define discrete random variables, and assigns probabilities to a countable number of distinct $y$ values.

-   The function tells us the probability of outcome $y$ occurring when we input $y$ and evaluate.

<br />

Probability Mass Functions can take several different notations:

$$
p(y) = (pmf) = Pr(Y=y)
$$

<br />

#### Properties of Mass Functions

There are a few properties that probability mass functions must meet:

1st, the function's output must always be between 0 and 1, since probability of an event occuring must always be between 0 and 1.

$$
0≤p(y)≤1
$$

2nd, the sum of all potential $p(y)$ with all $y$ outcomes should be equal to 1. This is because the set $Y$ should contain every possible outcome, and something must happen so probability of the sum of all $y$ must be 1.

$$
\sum\limits_{y} p(y) = 1
$$

<br />

#### Example:

For a fair 6-sided dice, there is an equal probability of rolling any number: $1/6$. Thus, the Probability Mass Function is as follows:

$$
p(y) = 1/6, \text{as p(y) does not depend on y, all y are 1/6}
$$

<br />

We will discuss different types of discrete distributions in a later lesson.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Cumulative Density Function {#density}

The cumulative density function measures the cumulative density of an event.

-   $Y$ is the set of outcomes, $y$ is an element in the set (specific possible outcome)

-   So, instead of measuring the probability of event $Y=y$ occuring, we measure the probability $Y ≤y$ occuring.

-   For example, if $y = 3$, instead of measuring the probability of exactly $y=3$ like a probability mass function, we instead measure the cumulative probabiltiy of $y=0, y=1, y=2$ and $y=3$.

<br />

Cumulative Dnesity Functions take the following form:

$$
Pr(Y≤y)=\sum\limits_{i≤y}p(i)
$$

Or in intuitive terms, the sum of all $p(y)$ outputs for $y$ and lower outcomes.

<br />

#### Properties of Cumulative Density Functions

A Cumulative Density Function (CDF) must satisfy the following properties:

1.  The CDF must not decrease
    -   Cumulative probability can't go down, since probability must be positive, and adding another probability must increase the output of the CDF.
2.  $\lim\limits_{y \rightarrow -∞} CDF = 0$, $\lim\limits_{y \rightarrow ∞} CDF = 1$
    -   The sum of no outcomes should be 0 probability, since no outcomes are occurring.
    -   The sum of all the outcomes should be 1, because if only one outcome can occur at a time, sum of the probabilities cannot be over 1.

<br />

Finally, a useful property is that:

$$
P(Y>y) = 1 - P(Y≤y)
$$

Since $Y>y$ and $Y≤y$ include all possible outcomes in set $Y$, which should be equal to 1.

<br />

#### Example:

For a fair 6-sided dice, there is an equal probability of rolling any number: $1/6$. Thus, the cumulative density function is as follows:

$$
Pr(Y≤y)=\sum\limits_{i≤y} 1/6
$$

<br />

So, the outputs would be:

-   For $y=1$, that means the cumulative probability of $y=1$ only, which is $1/6$

-   For $y=2$ that means the cumulative probability of $y=1$ and $y=2$, which is $1/6+1/6=1/3$

-   For $y=3$, that means the cumulative probability of $y=1, y=2$, and $y=3$, which is $1/6+1/6+1/6=1/2$

-   And so on....

-   The final possible outcome, $y=6$, should equal 1, as that is the cumulative probability of all possible outputs in the set $Y$.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)