---
title: "2.2 Continuous Distributions"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 2.2, Introductory Statistical Inference"
---

[Course Homepage](https://politicalscience.github.io/stats)

## Table of Contents {#contents}

1.  [Continuous Random Variables](#continuous)
2.  [Probability Density Function](#density)
3.  [Cumulative Density Function](#cumulative)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Continuous Random Variables {#continuous}

**Randomness** indicates that there is some probability that an event will occur, and it is not for-sure going to happen (deterministic).

<br />

A **random variable** is a variable that describes unobserved events. These unobserved events have some randomness - a probability to occur, but they have not yet happened, so it is not deterministic.

<br />

**Continuous Random Variables** are random variables, whose outcomes can assume any real number $y \in (-∞, ∞)$

-   So, there are an infinite number of possible outcomes.

-   Example: time it takes to drive to school (can take any real numbers above 0)

<br />

The important distinction between continuous random variables and [discrete random variables](https://politicalscience.github.io/stats/2-1.html) is how we measure the probability:

-   Continuous random probability is measured over intervals.

    -   This is because it doesn't make sense to see the probability of taking exactly 23.583 minutes to drive to school... that doesn't tell us anything.

    -   We are more interested in for example, the probability of taking less than 24 minutes to drive to school.

-   Discrete Random Variables are measured at points

    -   Since we have a limited set of outcomes, we can measure the probability at a specific point.

    -   For example, how many heads we might get if we flip a coin 5 times.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Probability Density Function {#density}

For continuous random variables, instead of a probability mass function, we us the probability density function $f(y)$

-   Like a probability mass function, $f(y)$ tells us the probability of the outcome $y$ occurring.

-   However, as we specified earlier, we aren't interested in this. We are interested of the probability of a range of $y$ occurring. Shortly, we will discuss how to find probability of intervals of outcomes occurring.

<br />

#### Properties of Probability Density Functions

The probability density function $f(y)$ should fit the following properties:

1.  $f(y) ≥ 0$, as probability of outcome $y$ cannot be negative
2.  $\int\limits_{-∞}^{∞}f(y)dy = 1$, as the total probability of all outcomes should be 1.

<br />

#### Finding Probabilities with the Density Function

How do we normally find the probability of a range of $y$ values?

-   Well, how would we find the probability of one $y$ value? The function $f(y)$ at one point $y$.

-   The value of $f(y)$, at least graphically, is the height of the function from the $x$ axis.

-   Basically, the probability of $y$ occuring, is the distance between $f(y)$ and the $x$ axis.

<br />

So, we know how to find the probability of one outcome $y$. How do we find the probability of a range of outcomes? Let us define the range as all outcomes between $a$ and $b$

-   Well, we know the probability of $y$ occuring, is the distance between $f(y)$ and the $x$ axis.

-   This means, that the probability of the range $(a,b)$ occuring is the distnace between $f(y)$ and the $x$ axis for the entire range $y=(a,b)$

In other other words, the probability of the range $y=(a,b)$, is the area under the curve $f(y)$ between $a$ and $b$.

<br />

What is the area under the curve $f(y)$ between $a$ and $b$? The [definite integral](https://politicalscience.github.io/math/2-6.html) of $f(y)$ between $a$ and $b$!

-   If you are unfamiliar with definite integrals, check out the [Maths for Political Science](https://politicalscience.github.io/math/) course.

<br />

Thus, if we are interested in the probability of the outcomes being in an interval defined by set $A$ as being between $a$ and $b$, $A=[a,b]$:

$$
Pr(Y \in A) = \int\limits_{a}^{b} f(y)dy
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Cumulative Density Function {#cumulative}

The cumulative density function finds the probability of a range of outcomes, as described above.

-   The probability of a range, as shown above, is the definite integral of $f(y)$

<br />

The cumulative density function always has the lower bound of $-∞$, and an upper value of $y$ (that we select to input).

-   Essentially, it measures the probability of outcomes $y$ and below occurring.

Thus, the cumulative density function takes the following form:

$$
F(y)=Pr(Y≤y)=\int\limits_{-∞}^{y} f(s)ds
$$

Where $f(s)$ is the probability density function.

<br />

#### Properties of Cumulative Density Functions

A Cumulative Density Function (CDF) must satisfy the following properties:

1.  The CDF must not decrease
    -   Cumulative probability can't go down, since probability must be positive, and adding another probability must increase the output of the CDF.
2.  $\lim\limits_{y \rightarrow -∞} CDF = 0$, $\lim\limits_{y \rightarrow ∞} CDF = 1$
    -   The sum of no outcomes should be 0 probability, since no outcomes are occurring.
    -   The sum of all the outcomes should be 1, because if only one outcome can occur at a time, sum of the probabilities cannot be over 1.

<br />

Finally, a useful property is that:

$$
P(Y>y) = 1 - P(Y≤y)
$$

Since $Y>y$ and $Y≤y$ include all possible outcomes in set $Y$, which should be equal to 1.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)