---
title: "2.3 Expectations of Random Variables"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
subtitle: "Lesson 2.3, Introductory Statistical Inference"
---

[Course Homepage](https://politicalscience.github.io/stats)

## Table of Contents {#contents}

1.  [Expectations of Discrete Random Variables](#discrete)
2.  [Expectations of Continuous Random Variables](#continuous)
3.  [Properties of Expected Values](#properties)
4.  [Variance](#variance)

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Expectations of Discrete Random Variables {#discrete}

Expectations, also known as the Expected Value, is the expected value of the variable when we consider all outcomes and their possibilities.

<br />

For Discrete Random Variables, the expected value is the weighted average of all possible outcome values in set $Y$:

$$
E(Y)=\sum\limits_{y} yP(Y=y) = \sum\limits_{y} yp(y)
$$

<br />

Or more intuitively:

-   It is the weighted average (weights by probability) of all possible outcomes.

-   This is not necessarily the number we would expect $Y$ to take, but the average value of $Y$ after a large number of repetitions of the scenario.

<br />

#### Example

What is the expected value of a fair 6-sided dice?

-   Well what are the possible outcomes in set $Y$?

-   $Y$ contains the outcomes $\{1, 2, 3, 4, 5, 6 \}$

-   Each outcome has a $1/6$ probability of occurring.

<br />

Now, let us put it into the expected value formula:

$$
E(Y)=\sum\limits_{y} yP(Y=y) = \sum\limits_{y} yp(y)
$$

$$
= 1(1/6) + 2(1/6) + 3(1/6) + 4(1/6) + 5(1/6) + 6(1/6)
$$

$$
= 1/6+1/3+1/2+2/3+5/6+1
$$

$$
= 3.5
$$

Thus, the expected value of a fair 6-sided dice is 3.5.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Expectations of Continuous Random Variables {#continuous}

Expectations, also known as the Expected Value, is the expected value of the variable when we consider all outcomes and their possibilities.

<br />

The expected value for Continuous Random Variables is very similar to the expected value for Discrete Random Variables.

-   We also want to take the weighted average of the probailities.

-   However, there is one issue - there are an infinite amount of possible outcomes in a continuous random variable.

-   So, to take the expected value of a continuous random variable, we will use integration:

$$
E(Y)=\int\limits_{y} yf(y)dy
$$

<br />

#### Example

What is the expected value, given the probability density function $f(y)=1/1.5$, between $0<y<1.5$?

<br />

To do this, let us use the above expected value formula:

$$
E(Y)=\int\limits_{y} yf(y)dy
$$

<br />

We know through the fundamental theorem of calculus, that:

$$
\int\limits_a^b f(x)dx = F(b) - F(a)
$$

<br />

So let us first find the integral of $yf(y)=1/1.5y$

$$
yf(y) = \frac{1}{1.5}y = \frac{2}{3}y
$$

$$
F(y)=\int f(y)dy = \int \left[ \frac{2}{3}y \right]dy
$$

$$
F(y)=\int f(y)dy = \frac{2}{3} * \frac{1}{1+1} y^{1+1}
$$

$$
F(y)=\frac{2}{3} * \frac{1}{2} y^2
$$

$$
F(y) = \frac{1}{3}y^2
$$

<br />

Now let us evaluate the definite integral in the range $0<y<1.5$:

$$
E(Y) = \int\limits_{0}^{1.5} yf(y)dy =  \frac{1}{3}y^2 \rvert_{0}^{1.5}
$$

$$
E(Y) = \frac{1}{3}(1.5)^2 - \frac{1}{3} (0)^2
$$

$$
E(Y) = \frac{1}{3}(\frac{3}{2})^2
$$

$$
E(Y) = \frac{1}{3} * \frac{9}{4}
$$

$$
E(Y) = \frac{3}{4} = 0.75
$$

So, the expected value of $f(y)=1/1.5$, between $0<y<1.5$ is 0.75.

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Properties of Expected Values {#properties}

There are a few properties of expected values:

<br />

1st, the expected value of a constant $c$, is $c$

$$
E(c) = c
$$

<br />

2nd, the expected value of the expected value, is the expected value:

$$
E \left[ E[Y] \right] = E[Y]
$$

<br />

3rd, the expected value of a probability density/mass function with a common factor, is equivalent to the expected value of that probability function without that common factor multiplied by the common factor:

$$
E[c*g(Y)] = c*E[g(Y)]
$$

<br />

4th, if $X$ and $Y$ are independent events, the following is true:

$$
E[XY] = E[X]*E[Y]
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)

# Variance {#variance}

Expected Value is a measure of spread - how much does the distribution spread around the mean.

-   For example, a distribution with a small variance will have a short distance between the centre and either end of the distribution.

-   For example, a distribution with a large variance will have a large distance between the centre and either end of the distribution.

Variance will become very useful as we go into statistical inference, hypothesis testing, and other more advanced methods.

<br />

There are two main measures of spread: Variance $\sigma ^2$ and Standard Deviation $\sigma$.

**Variance** is defined by the following formula:

$$
\sigma^2 = E[(Y-E(Y))^2] = E(Y^2) - [E(Y)]^2
$$

<br />

**Standard Deviation** is simply the square root of variance:

$$
\sigma = \sqrt{\sigma ^2}
$$

<br />

------------------------------------------------------------------------

[Table of Contents](#contents) \| [Course Homepage](https://politicalscience.github.io/stats)