---
title: "Introductory Statistical Inference"
format:
    html:
        theme: darkly
        max-width: 800px
        fontsize: 12pt
---

[Political Science Academy Homepage](https://politicalscience.github.io)

This is an introduction to statistical thinking and probability theory for Political Science. This course is about building the foundations for the applied methods taught in subsequent courses.

Probability theory and statistical theory is essential for regression analysis, causal inference, and game theory.

<br />

Prerequisites: Officially, none, but some understanding of [Maths for Political Science](https://politicalscience.github.io/math/) up to single variable calculus would be helpful.

<br />

### Chapter 1: Basics of Probability

| Lesson | Topics |
|-----------------------------------------|-------------------------------|
| [1.1 Sets](https://politicalscience.github.io/stats/1-1.html) | Sets, Set Notation, Set Operators, Set Properties |
| [1.2 Key Concepts in Probabilty](https://politicalscience.github.io/stats/1-2.html) | Axioms of Probability, Rules of Probability, Independence |
| [1.3 Counting](https://politicalscience.github.io/stats/1-3.html) | Fundamental Principle of Counting, Permutations, Combinations |
| [1.4 Conditional Probability and Bayes' Rule](https://politicalscience.github.io/stats/1-4.html) | Conditional Probability, Multiplicative Law, Law of Total Probability, Bayes' Rule |

<br />

### Chapter 2: Random Variables

| Lesson | Topics |
|-----------------------------------------|-------------------------------|
| [2.1 Discrete Distributions](https://politicalscience.github.io/stats/2-1.html) | Discrete Random Variable, Proabability Mass Function, Cumulative Density Function. |
| [2.2 Continuous Distributions](https://politicalscience.github.io/stats/2-2.html) | Continuous Random Variable, Probability Density Function, Cumulative Density Function |
| [2.3: Expectations of Random Variables](https://politicalscience.github.io/stats/2-3.html) | Expectations of Random Variables, Functions, Properties of Expected Value, Variance |
| [2.4 Types of Distributions](https://politicalscience.github.io/stats/2-4.html) | Uniform Distribution, Normal Distribution, Binomial Distribution, Poisson Distribution |
| [2.5 Joint Distributions](https://politicalscience.github.io/stats/2-5.html) | Joint Probability Distribution, Marginal Probability Distribution, Conditional Probability Distribution. |

<br />

### Chapter 3: Statistical Inference

| Lesson | Topics |
|-----------------------------------------|-------------------------------|
| 2.1 Summary Statistics | Measurements of Central Tendency, Measurements of Spread |
| 2.2 Samples and Populations | Sampling, Inference, Central Limit Theorem |
| 2.3 Intro to Hypothesis Testing | Hypothesis Testing, Chi-Square Tests, Difference in Means, Confidence Intervals |