---
title: "Econometric Methods (for Social Scientists)"
subtitle: "Methods for Political Science: Notes and Guides on Quantitative Methods"
format:
    html:
        page-layout: article
        grid:
          sidebar-width: 300px
          body-width: 750px
          margin-width: 250px
          gutter-width: 2em
        fontsize: 12.5pt
        theme: yeti
        toc: TRUE
        toc-depth: 2
        toc-location: left
        toc-expand: true
        toc-title: "Econometric Methods (for Social Scientists)"
        mainfont: "Computer Modern"
        title-block-banner: true
        classoption: fleqn
        html-math-method: katex
---

[Homepage](https://politicalscience.github.io)

# Overview

This is a full course on econometrics for social scientists. This course will introduce how to analyse real-world data to come to conclusions. Topics include estimating causal effects, causal inference, forecasting & prediction, as well as measurement problems.

This course is divided into 3 main parts, each which focus on a major topic in econometrics. It is recommended that you start in order.

**Prerequisites**: I highly recommend one has a solid understanding of calculus and basic statistical theory. Specifically, I assume knowledge through the first part of the quantitative methods (for social scientists) course covering single variable calculus and introductory statistical theory.

This course will also provide code for implementation of methods in R. However, this course is not a course in the R-programming language. I assume a basic understanding of variables, functions, data frames, and packages.

<br />

# Part 1: Methods for Causal Inference and Estimation

This part of the course will focus on techniques of causal estimation and causal inference, which is important in establishing causal relationships for social science research.

| Chapter                                                                                                                    | Summary                                                                                                                                                    |
|-------------------------------|-----------------------------------------|
| [1: Relationships between Variables with Regression](https://politicalscience.github.io/metrics/causal/1.html)             | Analysing the simple linear regression model, including specification, estimation, interpretation, and transformations.                                    |
| [2: Causal Relationships and Confounding Variables](https://politicalscience.github.io/metrics/causal/2.html)              | Discussing the potential outcomes framework, observed outcomes, causal estimands, and why correlation is not causation due to confounders.                 |
| [3: Randomised Controlled Trials and Basics of Causal Inference](https://politicalscience.github.io/metrics/causal/3.html) | Introducing the gold standard of causal estimation: randomised controlled trials, and introducing the concepts of causal inference and hypothesis testing. |
| [4: Causal Inference through Multiple Linear Regression](https://politicalscience.github.io/metrics/causal/4.html)         | Exploring the multiple linear regression and ordinary least squares (OLS) estimator, and the assumptions and properties needed for causal inference.       |
| 5: Instrumental Variables and 2-Stage Least Squares                                                                        |                                                                                                                                                            |
| 6: Fixed Effects and Analysis of Panel and Longitudinal Data                                                               |                                                                                                                                                            |
| 7: Differences-in-Differences Designs                                                                                      |                                                                                                                                                            |
| 8: Regression Discontinuity Designs                                                                                        |                                                                                                                                                            |
| 9: Probability Models and the Maximum Likelihood Estimator                                                                 |                                                                                                                                                            |
| 10: Further Discrete Choice Regression Designs                                                                             |                                                                                                                                                            |
| 11: Subclassification, Matching, and Weighting Designs                                                                     |                                                                                                                                                            |
| 12: Surveys and Experimental Design                                                                                        |                                                                                                                                                            |

<br />

[Homepage](https://politicalscience.github.io)

# Part 2: Time-Series Forecasting and Machine Learning Prediction Methods

This part of the course will focus on techniques of forecasting and prediction, including prediction methods from data science and forecasting methods from time series analysis.

| Chapter                                                       | Topics Covered                                                                             |
|-----------------------------|------------------------------------------|
| 1: Non-Linear Prediction Methods for Non-Linear Relationships | Polynomials, Step Functions, Splines, Local Linear Regression, Generalised Additive Models |
| 2: Tree-Based Prediction Methods                              | Regression Trees, Bagging, Random Forests, Importance Plots                                |
| 3: Model Selection for Prediction                             | Cross-Validation,                                                                          |
| 4: Classification Methods                                     | Logistic Classifier, Naive Bayes, Bagging and Random Forest, Classification Metrics        |
| 5: Cross-Validation                                           |                                                                                            |

Time series stuff

<br />

[Homepage](https://politicalscience.github.io)

# Part 3: Multivariate Measurement of Latent Variables and Textual Data

This part of the course will focus on measurement problems relating to latent (unobserved) variables and textual data.

| Chapter                                              | Topics Covered |
|------------------------------------------------------|----------------|
| 1: Exploratory Factor Analysis and Latent Variables  |                |
| 2: Confirmatory Factor Analysis                      |                |
| 3: Latent Trait Models                               |                |
| 4: Latent Class Models                               |                |
| 5: Structural Equation Modelling of Latent Variables |                |
| 6: Further Topics in Structural Equation Modelling   |                |
| 7: Principle Components Analysis                     |                |
| 8: Cluster Analysis                                  |                |
| 9: Textual Data Measurement with Dictionary Methods  |                |
| 10: Textual Classification and Similarity Metrics    |                |
| 11: Structural Topic Modelling of Textual Data       |                |
